#config_version=5

mode:
  start_events: metroid_base_started, metroid_open_doors
  stop_events: metroid_base_ended, metroid_close_doors
  priority: 600


timers:
  hot_spring_countdown:
    start_value: 0
    end_value: 1
    tick_interval: 0.5s
    control_events:
      - event: hot_spring_multiball_should_start
        action: restart

accruals:
  hot_spring_multiball_accrual:
    events:
      - room_2p_scoop_shot_hit
      - room_2l_scoop_shot_hit
    events_when_complete: hot_spring_multiball_should_start
    disable_events: logicblock_hot_spring_multiball_accrual_complete

counters:
  hot_springs_add_ball_counter:
    count_events: hot_spring_add_a_ball_hit
    events_when_hit: hot_spring_should_add_a_ball
    events_when_complete: hot_spring_balls_exhausted
    starting_count: 2
    count_complete_value: 0
    direction: down
    enable_events: hot_spring_multiball_should_start
    disable_events: mode_hot_spring_multiball_started, multiball_hot_spring_multiball_ended
    persist_state: true
    disable_on_complete: true

multiballs:
  hot_spring_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 30s
    start_events: hot_spring_multiball_should_start
    add_a_ball_events: hot_spring_should_add_a_ball


shot_profiles:
  hot_spring_shot:
    states:
      - name: lit
        show: blink_light
        speed: 2
        loops: -1
        sync_ms: 1000


shots:
  hot_spring_add_a_ball:
    switch: s_captive_ball
    profile: hot_spring_shot
    enable_events: hot_spring_multiball_should_start
    disable_events: hot_spring_balls_exhausted, mode_hot_spring_multiball_started, multiball_hot_spring_multiball_ended
    show_tokens:
      led: led_captive_ball
      color: 'FF0000'
  hot_spring_jackpot_shot_1:
    switch: s_left_passage
    profile: hot_spring_shot
    enable_events: hot_spring_multiball_should_start
    disable_events: mode_hot_spring_multiball_started, multiball_hot_spring_multiball_ended
    show_tokens:
      led: led_enter_secret_passage
      color: 'A040FF'
  hot_spring_jackpot_shot_2:
    hit_events: left_orbit_hit
    profile: hot_spring_shot
    enable_events: hot_spring_multiball_should_start
    disable_events: mode_hot_spring_multiball_started, multiball_hot_spring_multiball_ended
    show_tokens:
      led: led_enter_left_orbit
      color: 'C000FF'
  hot_spring_jackpot_shot_3:
    switch: s_side_ramp_made
    profile: hot_spring_shot
    enable_events: hot_spring_multiball_should_start
    disable_events: mode_hot_spring_multiball_started, multiball_hot_spring_multiball_ended
    show_tokens:
      led: led_enter_side_ramp
      color: 'FF8ADD'
  hot_spring_jackpot_shot_4:
    hit_events: right_orbit_hit
    profile: hot_spring_shot
    enable_events: hot_spring_multiball_should_start
    disable_events: mode_hot_spring_multiball_started, multiball_hot_spring_multiball_ended
    show_tokens:
      led: led_enter_right_orbit
      color: '6900FF'


event_player:
  timer_hot_spring_countdown_complete: hot_spring_room_exit
  hot_spring_multiball_should_start:
    cmd_play_overlay_music:
      music: music_multiball
    chozo_multiball_disable:
  multiball_hot_spring_multiball_ended: room_2l_enter, cmd_stop_overlay_music, chozo_multiball_enable
