#config_version=5
mode:
  start_events: mode_base_started
  stop_events: skillshot_monitor_should_end
  priority: 500

shot_groups:
  # this should get smaller as more skillshots added
  skillshot_unused_shot_group:
    shots:
      - scoop_shot
      - ramp_shot
      - side_ramp_shot
      - secret_passage_shot
      - upper_right_sling_shot
      - upper_left_sling_shot
      - left_sling_shot
      - right_sling_shot
      - pop_1_shot
      - pop_2_shot
      - pop_3_shot
      - left_outlane_shot
      - right_outlane_shot
      - left_inlane_shot
      - right_inlane_shot
      - spinner_shot
      - pop_subway_shot
      - rollover_shot
      - shatz_shot
      - captive_shot

show_player:
  skillshot_unused_shot_group_hit:
    skillshot_missed:
      loops: 0
      priority: -10
      events_when_completed: skillshot_monitor_should_end
  skillshot_drops_made_1:
    skillshot_drops_one_made:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_drops_made_2:
    skillshot_drops_two_made:
      loops: 0
      events_when_completed: skillshot_drops_release_should_start
  skillshot_drops_made_3:
    skillshot_drops_three_made:
      loops: 0
      events_when_completed: skillshot_drops_release_should_start
  skillshot_purple_success:
    skillshot_purple_made:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_purple_failure:
    skillshot_purple_missed:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_bombs_success:
    skillshot_bombs_made:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_bombs_failure:
    skillshot_bombs_missed:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_missiles_upgrade:
    skillshot_missiles_made:
      loops: 0
  skillshot_missiles_success:
    skillshot_missiles_made_normal:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_missiles_success_super:
    skillshot_missiles_made_super:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_missiles_failure:
    skillshot_missiles_missed:
      loops: 0
      events_when_completed: skillshot_monitor_should_end
  skillshot_unskilled_success:
    skillshot_unskilled_made:
      loops: 0
      events_when_completed: skillshot_monitor_should_end

event_player:
  skillshot_unused_shot_group_hit: skillshot_stage_one_end
  skillshot_drops_made_1: skillshot_stage_one_end
  skillshot_drops_made_2: skillshot_stage_one_end
  skillshot_drops_made_3: skillshot_stage_one_end
  skillshot_drops_one_behind_hit: skillshot_stage_one_end
  skillshot_drops_two_behind_hit: skillshot_stage_one_end
  skillshot_drops_three_behind_hit: skillshot_stage_one_end
  skillshot_purple_success: skillshot_stage_one_end
  skillshot_purple_failure: skillshot_stage_one_end
  skillshot_bombs_success: skillshot_stage_one_end
  skillshot_bombs_failure: skillshot_stage_one_end
  skillshot_missiles_success: skillshot_stage_one_end
  skillshot_missiles_success_super: skillshot_stage_one_end
  skillshot_missiles_failure: skillshot_stage_one_end
  skillshot_unskilled_success: skillshot_stage_one_end
  skillshot_side_success: skillshot_stage_one_end
  ball_will_end: skillshot_stage_one_end

