#config_version=5

mode:
  start_events: wall_jump_mode_should_start
  priority: 100

counters:
  wall_jump_counter:
    count_events: s_upper_sling_active
    starting_count: 10
    count_complete_value: 0
    direction: down
    events_when_complete: wall_jump_should_activate
    enable_events: mode_wall_jump_started, wall_jump_deactivated
    reset_events: game_start, wall_jump_deactivated
    persist_state: true
    disable_on_complete: true

timers:
  wall_jump_activation_timer:
    end_value: 80
    tick_interval: 0.25s
    restart_on_complete: false
    control_events:
      - event: wall_jump_should_activate
        action: restart

show_player:
  wall_jump_should_activate:
    blink_light:
      key: wall_jump_blink
      loops: -1
      speed: 10
      show_tokens:
        led: led_wall_jump
        color: "FF6000"
  timer_wall_jump_activation_timer_complete:
    wall_jump_blink:
      action: stop
  mode_wall_jump_ending:
    wall_jump_blink:
      action: stop

event_player:
  wall_jump_should_activate: upper_slingshot_should_disable
  timer_wall_jump_activation_timer_tick{ticks == 0}: left_sling_flipper_should_enable
  timer_wall_jump_activation_timer_tick{ticks == 79}: left_sling_flipper_should_disable
  timer_wall_jump_activation_timer_complete: wall_jump_deactivated
  wall_jump_deactivated: upper_slingshot_should_enable
  s_left_flipper_active{device.timers.wall_jump_activation_timer.running}: wall_jump_used