#config_version=5

# https://commons.wikimedia.org/wiki/File:%D0%9F%D0%BB%D0%B5%D1%81%D0%B5%D0%BD%D1%8C_%D0%BD%D0%B0_%D1%82%D1%80%D1%83%D0%BF%D0%B5_%D0%BC%D1%83%D1%85%D0%B8.jpg

mode:
  start_events: room_1s_continue, room_1s_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1r_enter, room_1t_enter
  priority: 300

shots:
  room_1s_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: room_1s_open_doors
    disable_events: room_1s_exit_east_shot_hit
    reset_events: room_1s_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_1s_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: room_1s_open_doors
    disable_events: room_1s_exit_west_shot_hit
    reset_events: room_1s_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue

slides:
  room_1s_blighted_canopy_backglass_slide:
    widgets:
      - type: image
        image: room_1s_blighted_canopy_backglass
    transition: fade
    transition_out: fade
  room_1s_blighted_canopy_splash_slide:
    widgets:
      - type: image
        image: room_1s_blighted_canopy_splash

slide_player:
  mode_room_1s_blighted_canopy_started:
    room_1s_blighted_canopy_backglass_slide:
      target: backglass
    room_1s_blighted_canopy_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1s_blighted_canopy_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '00FF00'
        color2: '00FFFF'
  show_mode_status_report:
    room_1s_blighted_canopy_status_report:
      loops: 0
  flipper_cradle_release:
    room_1s_blighted_canopy_status_report:
      action: stop

event_player:
  mode_room_1s_blighted_canopy_started:
    cmd_backbox_show:
      show_type: plasma
      color1: "001080"
      color2: "002070"
      color3: "003060"
      color4: "004050"
      color5: "005040"
      color6: "006030"
      color7: "007020"
      color8: "008010"
      decay_g: 2.0
      decay_b: 1.7
    drop_targets_continue:
    room_1s_open_doors:
    cmd_map_position:
      room: '1s'
      visit: True
  room_1s_exit_east_shot_hit.1: drop_targets_save
  room_1s_exit_east_shot_hit.2: room_1t_enter
  room_1s_exit_west_shot_hit.1: drop_targets_save
  room_1s_exit_west_shot_hit.2: room_1r_enter

variable_player:
  mode_room_1s_blighted_canopy_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1s
      action: set
