#config_version=5

# https://commons.wikimedia.org/wiki/File:%D0%9F%D0%BB%D0%B5%D1%81%D0%B5%D0%BD%D1%8C_%D0%BD%D0%B0_%D1%82%D1%80%D1%83%D0%BF%D0%B5_%D0%BC%D1%83%D1%85%D0%B8.jpg

mode:
  start_events: room_1s_continue, room_1s_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1r_enter, room_1t_enter, room_1s_exit
  priority: 300

shot_profiles:
  room_1s_light_jackpot:
    states:
      - name: lit
        show: blink_light
        loops: -1
        speed: 2
        show_tokens:
          color: '10FFA0'

shots:
  room_1s_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: mode_room_1s_blighted_canopy_started, room_1s_exit_east_shot_hit, metroid_close_doors
    reset_events: mode_room_1s_blighted_canopy_started, room_1s_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_1s_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1s_exit_west_shot_hit, metroid_close_doors
    reset_events: room_1s_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1s_light_jackpot_1_shot:
    switches: s_ramp_enter
    profile: room_1s_light_jackpot
    enable_events: mode_room_1s_enable_light_jackpot_shots
    disable_events: mode_room_1s_blighted_canopy_started, room_1s_light_jackpot_1_shot_hit, mode_room_1s_disable_light_jackpot_shots
    reset_events: mode_room_1s_blighted_canopy_started, room_1s_light_jackpot_1_shot_hit, mode_room_1s_disable_light_jackpot_shots
    show_tokens:
      led: led_enter_ramp
  room_1s_light_jackpot_2_shot:
    switch: s_scoop
    profile: room_1s_light_jackpot
    enable_events: mode_room_1s_enable_light_jackpot_shots
    disable_events: mode_room_1s_blighted_canopy_started, room_1s_light_jackpot_2_shot_hit, mode_room_1s_disable_light_jackpot_shots
    reset_events: mode_room_1s_blighted_canopy_started, room_1s_light_jackpot_2_shot_hit, mode_room_1s_disable_light_jackpot_shots
    show_tokens:
      led: led_enter_scoop
  room_1s_light_jackpot_3_shot:
    hit_events: left_orbit_hit
    profile: room_1s_light_jackpot
    enable_events: mode_room_1s_enable_light_jackpot_shots
    disable_events: mode_room_1s_blighted_canopy_started, room_1s_light_jackpot_3_shot_hit, mode_room_1s_disable_light_jackpot_shots
    reset_events: mode_room_1s_blighted_canopy_started, room_1s_light_jackpot_3_shot_hit, mode_room_1s_disable_light_jackpot_shots
    show_tokens:
      led: led_enter_left_orbit
  room_1s_jackpot_shot:
    switch: s_side_ramp_made
    profile: room_1s_light_jackpot
    enable_events: mode_room_1s_enable_jackpot_shot
    disable_events: mode_room_1s_blighted_canopy_started, room_1s_jackpot_shot_hit
    reset_events: mode_room_1s_blighted_canopy_started, room_1s_jackpot_shot_hit
    show_tokens:
      led: led_enter_side_ramp

slides:
  room_1s_blighted_canopy_backglass_slide:
    widgets:
      - type: image
        image: room_1s_blighted_canopy_backglass
    transition: fade
    transition_out: fade
  room_1s_blighted_canopy_splash_slide:
    widgets:
      - type: image
        image: room_1s_blighted_canopy_splash

slide_player:
  mode_room_1s_blighted_canopy_started:
    room_1s_blighted_canopy_backglass_slide:
      target: backglass
    room_1s_blighted_canopy_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1s_blighted_canopy_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '00FF00'
        color2: '00FFFF'
  show_mode_status_report:
    room_1s_blighted_canopy_status_report:
      loops: 0
  flipper_cradle_release:
    room_1s_blighted_canopy_status_report:
      action: stop
  room_1s_light_jackpot_1_shot_hit:
    special_score_green:
      loops: 0
  room_1s_light_jackpot_2_shot_hit:
    special_score_green:
      loops: 0
  room_1s_light_jackpot_3_shot_hit:
    special_score_green:
      loops: 0
  room_1s_jackpot_shot_hit:
    special_score_red:
      loops: 0

event_player:
  mode_room_1s_blighted_canopy_started:
    cmd_backbox_show:
      show_type: plasma
      color1: "001080"
      color2: "002070"
      color3: "003060"
      color4: "004050"
      color5: "005040"
      color6: "006030"
      color7: "007020"
      color8: "008010"
      decay_g: 2.0
      decay_b: 1.7
    drop_targets_continue:
    metroid_open_doors:
    mode_room_1s_enable_light_jackpot_shots:
    cmd_map_position:
      room: '1s'
      visit: True
    cmd_play_map_music:
      music: music_brinstar_side_entrance
  room_1s_light_jackpot_1_shot_hit: mode_room_1s_disable_light_jackpot_shots, mode_room_1s_enable_jackpot_shot
  room_1s_light_jackpot_2_shot_hit: mode_room_1s_disable_light_jackpot_shots, mode_room_1s_enable_jackpot_shot
  room_1s_light_jackpot_3_shot_hit: mode_room_1s_disable_light_jackpot_shots, mode_room_1s_enable_jackpot_shot
  room_1s_jackpot_shot_hit: mode_room_1s_enable_light_jackpot_shots
  room_1s_exit_east_shot_hit.1: drop_targets_save
  room_1s_exit_east_shot_hit.2: room_1t_enter
  room_1s_exit_west_shot_hit.1: drop_targets_save
  room_1s_exit_west_shot_hit.2: room_1r_enter

variable_player:
  mode_room_1s_blighted_canopy_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1s
      action: set
  room_1s_light_jackpot_1_shot_hit:
    room_1s_jackpot: 100000
    score: (50000 + (current_player.area_bonus_nw * 25000)) * current_player.multiplier
    room_special_score:
      int: (50000 + (current_player.area_bonus_nw * 25000)) * current_player.multiplier
      action: set
  room_1s_light_jackpot_2_shot_hit:
    room_1s_jackpot: 200000
    score: (70000 + (current_player.area_bonus_nw * 25000)) * current_player.multiplier
    room_special_score:
      int: (70000 + (current_player.area_bonus_nw * 25000)) * current_player.multiplier
      action: set
  room_1s_light_jackpot_3_shot_hit:
    room_1s_jackpot: 300000
    score: (90000 + (current_player.area_bonus_nw * 25000)) * current_player.multiplier
    room_special_score:
      int: (90000 + (current_player.area_bonus_nw * 25000)) * current_player.multiplier
      action: set
  room_1s_jackpot_shot_hit:
    score: (current_player.room_1s_jackpot + (current_player.area_bonus_ne * 100000)) * current_player.multiplier
    room_special_score:
      int: (current_player.room_1s_jackpot + (current_player.area_bonus_ne * 100000)) * current_player.multiplier
      action: set
