#config_version=5

mode:
  start_events: room_2q_continue, room_2q_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2n_enter
  priority: 300

shot_profiles:
  room_2q_weak_spot:
    states:
      - name: lit
        sync_ms: 4000
        show: fade_one_light
  room_2q_strong_spot:
    states:
      - name: lit
        sync_ms: 4000
        show: fade_one_light

shots:
  room_2q_boss_weak_back_ramp_shot:
    switch: s_ramp_enter
    profile: room_2q_weak_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_enter_ramp
      color: red
  room_2q_boss_weak_side_ramp_shot:
    switch: s_side_ramp_made
    profile: room_2q_weak_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_enter_side_ramp
      color: red
  room_2q_boss_strong_rollover_shot:
    switch: s_rollover_button
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_rollover
      color: blue
  room_2q_boss_strong_scoop_shot:
    switch: s_scoop
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_enter_scoop
      color: blue
  room_2q_boss_strong_secret_shot:
    switch: s_left_passage
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_enter_secret_passage
      color: blue
  room_2q_boss_strong_right_orbit_shot:
    hit_events: right_orbit_hit
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_enter_right_orbit
      color: blue
  room_2q_boss_strong_left_orbit_shot:
    hit_events: left_orbit_hit
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_enter_left_orbit
      color: blue
  room_2q_boss_strong_captive_shot:
    switch: s_captive_ball
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_captive_ball
      color: blue
  room_2q_boss_strong_center_1_shot:
    switch: s_purple_1
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_upgrade_bank_1
      color: blue
  room_2q_boss_weak_center_2_shot:
    switch: s_purple_2
    profile: room_2q_weak_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_upgrade_bank_2
      color: red
  room_2q_boss_strong_center_3_shot:
    switch: s_purple_3
    profile: room_2q_strong_spot
    enable_events: mode_room_2q_ridley_battle
    disable_events: mode_room_2q_ridley_over
    show_tokens:
      led: led_upgrade_bank_3
      color: blue


animations:
  room_2q_ridley_standard:
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
      repeat: true

slides:
  room_2q_ridley_backglass_slide:
    widgets:
      - type: image
        image: room_2q_ridley_backglass
        x: 280
        y: 690
        animations:
          show_slide: room_2g_draygon_standard
    transition: fade
    transition_out: fade
  room_2q_ridley_splash_slide:
    widgets:
      - type: image
        image: room_2q_ridley_splash

slide_player:
  mode_room_2q_ridley_started:
    room_2q_ridley_backglass_slide:
      target: backglass
    room_2q_ridley_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2q_ridley_started:
    room_2q_gi:
      loops: -1
      speed: 30
  show_mode_status_report:
    room_2q_ridley_status_report:
      loops: 0
  flipper_cradle_release:
    room_2q_ridley_status_report:
      action: stop
  ridley_hit_strong:
    room_2q_ridley_hit_strong_lights:
      loops: 0
      speed: 40

sounds:
  ridley_hit_strong:
    file: ridley_hit_strong.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

sound_player:
  ridley_hit_strong: ridley_hit_strong

event_player:
  mode_room_2q_ridley_started:
    cmd_backbox_show:
      show_type: fire
      invert: True
    drop_targets_continue:
    metroid_exclusive_started:
    mode_room_2q_ridley_battle:
    cmd_map_position:
      room: '2q'
      visit: True
  room_2q_boss_weak_back_ramp_shot_hit: ridley_hit_strong
  room_2q_boss_weak_side_ramp_shot_hit: ridley_hit_strong
  room_2q_boss_weak_center_2_shot_hit: ridley_hit_strong

variable_player:
  mode_room_2q_ridley_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2q
      action: set
