#config_version=5

# https://commons.wikimedia.org/wiki/File:Museum_of_Science,_Boston,_MA_-_IMG_3166.JPG
# Most likely OK

mode:
  start_events: room_1i_continue, room_1i_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1h_enter, room_1j_enter, room_1k_enter, room_1i_exit
  priority: 300

shots:
  room_1i_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: mode_room_1i_computing_started
    disable_events: room_1i_exit_south_shot_hit
    reset_events: room_1i_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1i_exit_west_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: mode_room_1i_computing_started
    disable_events: room_1i_exit_west_shot_hit
    reset_events: room_1i_exit_west_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_1i_exit_east_shot:
    switches: s_ramp_enter
    profile: exit_door_optimum
    enable_events: mode_room_1i_computing_started
    disable_events: room_1i_exit_east_shot_hit
    reset_events: room_1i_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue

slides:
  room_1i_computing_backglass_slide:
    widgets:
      - type: image
        image: room_1i_computing_backglass
    transition: fade
    transition_out: fade
  room_1i_computing_backglass_powered_slide:
    widgets:
      - type: image
        image: room_1i_computing_backglass_powered
    transition: fade
    transition_out: fade
  room_1i_computing_splash_slide:
    widgets:
      - type: image
        image: room_1i_computing_splash

slide_player:
  mode_room_1i_computing_started_no_charge:
    room_1i_computing_backglass_slide:
      target: backglass
  mode_room_1i_computing_started_charge:
    room_1i_computing_backglass_powered_slide:
      target: backglass
  mode_room_1i_computing_started:
    room_1i_computing_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1i_computing_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1i_computing_status_report:
      loops: 0
  flipper_cradle_release:
    room_1i_computing_status_report:
      action: stop

event_player:
  mode_room_1i_computing_started:
    drop_targets_continue:
    cmd_map_position:
      room: '1i'
      visit: True
  mode_room_1i_computing_started_no_charge:
    cmd_backbox_show:
      show_type: twinkle
      background_color: '000000'
      twinkle_color: '100808'
      twinkle_count: 10
      steps: 30
    cmd_play_map_music:
      music: music_wrecked_ship
  mode_room_1i_computing_started_charge:
    cmd_backbox_show:
      show_type: spectrum
      color1: '400000'
      color2: '101010'
      color3: '004000'
    cmd_play_map_music:
      music: music_wrecked_ship_generator
  mode_room_1i_computing_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1i_computing_started_no_charge
  mode_room_1i_computing_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1i_computing_started_charge
  room_1i_exit_south_shot_hit.1: drop_targets_save
  room_1i_exit_south_shot_hit.2: room_1k_enter
  room_1i_exit_west_shot_hit.1: drop_targets_save
  room_1i_exit_west_shot_hit.2: room_1h_enter
  room_1i_exit_east_shot_hit.1: drop_targets_save
  room_1i_exit_east_shot_hit.2: room_1j_enter

variable_player:
  mode_room_1i_computing_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1i
      action: set
