#config_version=5
mode:
  start_events: skillshot_should_start
  stop_events: skillshot_stage_one_end
  priority: 500

shots:
  skillshot_drops_one:
    switch: s_drop_target_1
    enable_events: skillshot_drops_enable_1
    disable_events:
      - timer_skillshot_drops_first_up_stopped
      - mode_skillshot_drops_started
  skillshot_drops_two:
    switch: s_drop_target_2
    enable_events: skillshot_drops_enable_2
    disable_events:
      - timer_skillshot_drops_second_up_stopped
      - mode_skillshot_drops_started
  skillshot_drops_three:
    switch: s_drop_target_3
    enable_events: skillshot_drops_enable_3
    disable_events:
      - timer_skillshot_drops_third_up_stopped
      - mode_skillshot_drops_started

timers:
  skillshot_drops_reset_all:
    end_value: 2
    tick_interval: .25s
    control_events:
      - event: mode_skillshot_drops_started
        action: restart
  skillshot_drops_first_up:
    end_value: 2
    tick_interval: 1s
    control_events:
      - event: timer_skillshot_drops_reset_all_stopped
        action: restart
      - event: timer_skillshot_drops_third_down_stopped
        action: restart
      - event: skillshot_drops_test_capture_middle
        action: pause
        value: 0
      - event: skillshot_drops_test_capture_back
        action: pause
        value: 0
  skillshot_drops_first_down:
    end_value: 2
    tick_interval: .25s
    control_events:
      - event: timer_skillshot_drops_first_up_stopped
        action: restart
      - event: skillshot_drops_test_capture_middle
        action: pause
        value: 0
      - event: skillshot_drops_test_capture_back
        action: pause
        value: 0
  skillshot_drops_second_up:
    end_value: 2
    tick_interval: 1s
    control_events:
      - event: timer_skillshot_drops_first_down_stopped
        action: restart
      - event: skillshot_drops_test_capture_middle
        action: pause
        value: 0
      - event: skillshot_drops_test_capture_back
        action: pause
        value: 0
  skillshot_drops_second_down:
    end_value: 2
    tick_interval: .25s
    control_events:
      - event: timer_skillshot_drops_second_up_stopped
        action: restart
      - event: skillshot_drops_test_capture_middle
        action: pause
        value: 0
      - event: skillshot_drops_test_capture_back
        action: pause
        value: 0
  skillshot_drops_third_up:
    end_value: 2
    tick_interval: 1s
    control_events:
      - event: timer_skillshot_drops_second_down_stopped
        action: restart
      - event: skillshot_drops_test_capture_middle
        action: pause
        value: 0
      - event: skillshot_drops_test_capture_back
        action: pause
        value: 0
  skillshot_drops_third_down:
    end_value: 2
    tick_interval: .25s
    control_events:
      - event: timer_skillshot_drops_third_up_stopped
        action: restart
      - event: skillshot_drops_test_capture_middle
        action: pause
        value: 0
      - event: skillshot_drops_test_capture_back
        action: pause
        value: 0
  skillshot_drops_test_back_locked:
    start_value: 1
    end_value: 2
    tick_interval: 1.0s
    control_events:
      - event: skillshot_drops_test_capture_back
        action: restart
      - event: mode_skillshot_drops_started
        action: stop
  skillshot_drops_test_middle_locked:
    start_value: 1
    end_value: 2
    tick_interval: 1.0s
    control_events:
      - event: skillshot_drops_test_capture_middle
        action: restart
      - event: mode_skillshot_drops_started
        action: stop
      - event: skillshot_drops_test_capture_back
        action: stop

sound_player:
  skillshot_drops_made_1: skillshot
  skillshot_drops_made_2: skillshot
  skillshot_drops_made_3: skillshot

event_player:
  mode_skillshot_drops_started: drop_target_mode_should_end
  timer_skillshot_drops_reset_all_started: cmd_drop_all_drops
  timer_skillshot_drops_first_up_started: cmd_drop_one_up, skillshot_drops_1_should_enable
  timer_skillshot_drops_first_down_started: cmd_drop_one_down
  timer_skillshot_drops_second_up_started: cmd_drop_two_up, skillshot_drops_2_should_enable
  timer_skillshot_drops_second_down_started: cmd_drop_two_down
  timer_skillshot_drops_third_up_started: cmd_drop_three_up, skillshot_drops_3_should_enable
  timer_skillshot_drops_third_down_started: cmd_drop_three_down
  skillshot_drops_1_should_enable: skillshot_drops_enable_1
  skillshot_drops_2_should_enable: skillshot_drops_enable_2
  skillshot_drops_3_should_enable: skillshot_drops_enable_3
  skillshot_drops_one_hit: skillshot_drops_made_1
  s_behind_drop_1_active: cmd_drop_one_up, skillshot_drops_test_capture_middle
  s_behind_drop_2_active: cmd_drop_two_up, skillshot_drops_test_capture_back
  timer_skillshot_drops_test_back_locked_complete{device.switches.s_behind_drop_2.state or device.switches.s_behind_drop_1.state}: skillshot_drops_made_3
  timer_skillshot_drops_test_middle_locked_complete{device.switches.s_behind_drop_1.state}: skillshot_drops_made_2
  timer_skillshot_drops_test_back_locked_complete{not device.switches.s_behind_drop_2.state}: skillshot_drops_failed
  timer_skillshot_drops_test_middle_locked_complete{not device.switches.s_behind_drop_1.state}: skillshot_drops_failed

show_player:
  skillshot_drops_enable_1:
    blink_light:
      key: skillshot_drops_blink_1
      loops: -1
      speed: 2
      show_tokens:
        led: led_drop_1
        color: ff0000
  timer_skillshot_drops_first_up_stopped:
    skillshot_drops_blink_1:
      action: stop
  skillshot_drops_enable_2:
    blink_light:
      key: skillshot_drops_blink_2
      loops: -1
      speed: 2
      show_tokens:
        led: led_drop_2
        color: ff0000
  timer_skillshot_drops_second_up_stopped:
    skillshot_drops_blink_2:
      action: stop
  skillshot_drops_enable_3:
    blink_light:
      key: skillshot_drops_blink_3
      loops: -1
      speed: 2
      show_tokens:
        led: led_drop_3
        color: ff0000
  timer_skillshot_drops_third_up_stopped:
    skillshot_drops_blink_3:
      action: stop

variable_player:
  skillshot_drops_one_hit:
    score: 100000 * current_player.multiplier
  skillshot_drops_two_hit:
    score: 150000 * current_player.multiplier
  skillshot_drops_three_hit:
    score: 200000 * current_player.multiplier
