#config_version=5
mode:
    start_events: select_landing_site_maridia_selected, room_2a_continue
    stop_events: game_ending, ball_ending
    priority: 300

timers:
  room_2a_do_not_sink:
    direction: down
    start_value: 10
    end_value: 0
    tick_interval: 1s
    control_events:
      - event: mode_room_2a_shifting_sands_started
        action: start
      - event: room_2a_bank_1_shot_hit
        action: add
        value: 4
      - event: room_2a_bank_2_shot_hit
        action: add
        value: 4
      - event: room_2a_bank_3_shot_hit
        action: add
        value: 2
      - event: room_2a_bank_4_shot_hit
        action: add
        value: 8
      - event: mode_room_2a_shifting_sands_started
        action: reset

shots:
  room_2a_bank_1_shot:
    switch: s_missile_bank_1, s_missile_bank_2, s_missile_bank_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_2_shot_hit, room_2a_bank_3_shot_hit, room_2a_bank_4_shot_hit
    disable_events: room_2a_bank_1_shot_hit
    reset_events: room_2a_bank_1_shot_hit
    show_tokens:
      led_1: led_missile_bank_1
      led_2: led_missile_bank_2
      led_3: led_missile_bank_3
      color_1: '808010'
      color_2: stop
  room_2a_bank_2_shot:
    switch: s_lower_right_bank_1, s_lower_right_bank_2, s_lower_right_bank_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_1_shot_hit, room_2a_bank_3_shot_hit, room_2a_bank_4_shot_hit
    disable_events: room_2a_bank_2_shot_hit
    reset_events: room_2a_bank_2_shot_hit
    show_tokens:
      led_1: led_bomb_bank_1
      led_2: led_bomb_bank_2
      led_3: led_bomb_bank_3
      color_1: '808010'
      color_2: stop
  room_2a_bank_3_shot:
    switch: s_purple_1, s_purple_2, s_purple_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_1_shot_hit, room_2a_bank_2_shot_hit, room_2a_bank_4_shot_hit
    disable_events: room_2a_bank_3_shot_hit
    reset_events: room_2a_bank_3_shot_hit
    show_tokens:
      led_1: led_upgrade_bank_1
      led_2: led_upgrade_bank_2
      led_3: led_upgrade_bank_3
      color_1: '808010'
      color_2: stop
  room_2a_bank_4_shot:
    switch: s_left_target_1, s_left_target_2, s_left_target_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_1_shot_hit, room_2a_bank_2_shot_hit, room_2a_bank_3_shot_hit
    disable_events: room_2a_bank_4_shot_hit
    reset_events: room_2a_bank_4_shot_hit
    show_tokens:
      led_1: led_side_1
      led_2: led_side_2
      led_3: led_side_3
      color_1: '808010'
      color_2: stop

shot_profiles:
  room_2a_strobe:
    states:
    - name: lit
      show: blink_3_lights
      loops: -1

show_player:
  mode_room_2a_shifting_sands_started:
    gi_solid:
      loops: -1
      show_tokens:
        color: 'a78600'

slides:
  room_2a_backglass_slide:
    widgets:
      - type: image
        image: room_2a_shifting_sands_backglass
    transition: fade
    transition_out: fade
  room_2a_splash_slide:
    widgets:
      - type: image
        image: room_2a_splash
  room_2a_score_slide:
    widgets:
    - type: text
      text: (score)
      number_grouping: true
      min_digits: 2
      style: dmd_med
      anchor_x: left
      anchor_y: top
      x: 1
      y: 30
    - type: text
      text: Time Remaining
      min_digits: 1
      style: dmd_small
      color: 'FF40FF'
      anchor_x: right
      anchor_y: top
      x: 126
      y: 30
    - type: text
      text: (player|room_2a_shifting_sands_room_2a_do_not_sink_tick)
      min_digits: 1
      style: dmd_big
      color: 'FF0000'
      anchor_x: right
      anchor_y: top
      x: 126
      y: 22
    - type: text
      text: PLAYER (number)
      y: 0
      x: 10
      style: dmd_med
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: BALL (ball)
      y: 0
      x: right-10
      anchor_x: right
      anchor_y: bottom
      style: dmd_med
  room_2a_time_plus_2:
    widgets:
    - type: text
      text: +2 Seconds
      style: dmd_big
      color: 'FF1030'
  room_2a_time_plus_4:
    widgets:
    - type: text
      text: +4 Seconds
      style: dmd_big
      color: 'FF1030'
  room_2a_time_plus_8:
    widgets:
    - type: text
      text: +8 Seconds
      style: dmd_big
      color: 'FF1030'

slide_player:
  mode_room_2a_shifting_sands_started:
    room_2a_backglass_slide:
      target: backglass
    room_2a_splash_slide:
      target: dmd
      expire: 1s
      priority: 500
    room_2a_score_slide:
      target: dmd
  room_2a_bank_1_shot_hit:
    room_2a_time_plus_4:
      target: dmd
      expire: 1s
      priority: 310
  room_2a_bank_2_shot_hit:
    room_2a_time_plus_4:
      target: dmd
      expire: 1.5s
      priority: 310
  room_2a_bank_3_shot_hit:
    room_2a_time_plus_2:
      target: dmd
      expire: 1s
      priority: 310
  room_2a_bank_4_shot_hit:
    room_2a_time_plus_8:
      target: dmd
      expire: 1s
      priority: 310


event_player:
  mode_room_2a_shifting_sands_started:
    cmd_backbox_show:
      show_type: pour
      count: 3
      min_length: 4
      max_length: 12
      color: "200C00"
  timer_room_2a_do_not_sink_complete:
    - room_2a_sink_into_sand

variable_player:
  mode_room_2a_shifting_sands_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2a
      action: set

