#config_version=5
mode:
    start_events: select_landing_site_maridia_selected, room_2a_continue, room_2a_enter
    stop_events: game_ending, ball_ending, metroid_base_ended, room_2a_sink_into_sand, room_1z_enter, room_2b_enter, room_1q_enter, room_2a_exit
    priority: 300

timers:
  room_2a_do_not_sink:
    direction: down
    start_value: 15
    end_value: 0
    tick_interval: 1s
    control_events:
      - event: mode_room_2a_shifting_sands_started
        action: start
      - event: ball_ending
        action: stop
      - event: mode_bonus_will_start
        action: stop
      - event: room_2a_bank_1_shot_hit
        action: add
        value: 4
      - event: room_2a_bank_2_shot_hit
        action: add
        value: 4
      - event: room_2a_bank_3_shot_hit
        action: add
        value: 2
      - event: room_2a_bank_4_shot_hit
        action: add
        value: 8
      - event: mode_room_2a_shifting_sands_started
        action: reset
      - event: flipper_cradle
        action: pause
      - event: flipper_cradle_release
        action: start
      - event: room_2a_shifting_sands_status_over
        action: start

shots:
  room_2a_bank_1_shot:
    switch: s_missile_bank_1, s_missile_bank_2, s_missile_bank_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_2_shot_hit, room_2a_bank_3_shot_hit, room_2a_bank_4_shot_hit
    disable_events: room_2a_bank_1_shot_hit
    reset_events: room_2a_bank_1_shot_hit
    show_tokens:
      led_1: led_missile_bank_1
      led_2: led_missile_bank_2
      led_3: led_missile_bank_3
      color_1: '808010'
      color_2: stop
  room_2a_bank_2_shot:
    switch: s_lower_right_bank_1, s_lower_right_bank_2, s_lower_right_bank_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_1_shot_hit, room_2a_bank_3_shot_hit, room_2a_bank_4_shot_hit
    disable_events: room_2a_bank_2_shot_hit
    reset_events: room_2a_bank_2_shot_hit
    show_tokens:
      led_1: led_bomb_bank_1
      led_2: led_bomb_bank_2
      led_3: led_bomb_bank_3
      color_1: '808010'
      color_2: stop
  room_2a_bank_3_shot:
    switch: s_purple_1, s_purple_2, s_purple_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_1_shot_hit, room_2a_bank_2_shot_hit, room_2a_bank_4_shot_hit
    disable_events: room_2a_bank_3_shot_hit
    reset_events: room_2a_bank_3_shot_hit
    show_tokens:
      led_1: led_upgrade_bank_1
      led_2: led_upgrade_bank_2
      led_3: led_upgrade_bank_3
      color_1: '808010'
      color_2: stop
  room_2a_bank_4_shot:
    switch: s_left_target_1, s_left_target_2, s_left_target_3
    profile: room_2a_strobe
    enable_events: mode_room_2a_shifting_sands_started, room_2a_bank_1_shot_hit, room_2a_bank_2_shot_hit, room_2a_bank_3_shot_hit
    disable_events: room_2a_bank_4_shot_hit
    reset_events: room_2a_bank_4_shot_hit
    show_tokens:
      led_1: led_side_1
      led_2: led_side_2
      led_3: led_side_3
      color_1: '808010'
      color_2: stop
  room_2a_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: mode_room_2a_shifting_sands_started
    disable_events: room_2a_exit_west_shot_hit
    reset_events: room_2a_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_2a_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: mode_room_2a_shifting_sands_started
    disable_events: room_2a_exit_east_shot_hit
    reset_events: room_2a_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_2a_exit_north_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_2a_shifting_sands_started
    disable_events: room_2a_exit_north_shot_hit
    reset_events: room_2a_exit_north_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue

shot_profiles:
  room_2a_strobe:
    states:
    - name: lit
      show: blink_3_lights
      loops: -1

show_player:
  mode_room_2a_shifting_sands_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: 'a78600'
        color2: 'FF8000'
  show_mode_status_report:
    room_2a_shifting_sands_status_report:
      loops: 0
      events_when_completed: room_2a_shifting_sands_status_over
  flipper_cradle_release:
    room_2a_shifting_sands_status_report:
      action: stop
  room_2a_bank_1_shot_hit:
    special_score_yellow:
      loops: 1
  room_2a_bank_2_shot_hit:
    special_score_yellow:
      loops: 1
  room_2a_bank_3_shot_hit:
    special_score_yellow:
      loops: 1
  room_2a_bank_4_shot_hit:
    special_score_yellow:
      loops: 1

slides:
  room_2a_backglass_slide:
    widgets:
      - type: image
        image: room_2a_shifting_sands_backglass
    transition: fade
    transition_out: fade
  room_2a_splash_slide:
    widgets:
      - type: image
        image: room_2a_splash
  room_2a_score_slide:
    widgets:
    - type: text
      text: (score)
      number_grouping: true
      min_digits: 2
      style: dmd_med
      anchor_x: left
      anchor_y: top
      x: 1
      y: 30
    - type: text
      text: Time Remaining
      min_digits: 1
      style: dmd_small
      color: 'FF40FF'
      anchor_x: right
      anchor_y: top
      x: 126
      y: 30
    - type: text
      text: (player|room_2a_shifting_sands_room_2a_do_not_sink_tick)
      min_digits: 1
      style: dmd_big
      color: 'FF0000'
      anchor_x: right
      anchor_y: top
      x: 126
      y: 22
    - type: text
      text: PLAYER (number)
      y: 0
      x: 10
      style: dmd_med
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: BALL (ball)
      y: 0
      x: right-10
      anchor_x: right
      anchor_y: bottom
      style: dmd_med
  room_2a_time_plus_2:
    widgets:
    - type: text
      text: +2 Seconds
      style: dmd_big
      color: 'FF1030'
      y: 22
    - type: text
      text: (player|room_special_score)
      color: 'FFFF00'
      style: dmd_big
      y: 10
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .1s
          - property: opacity
            value: 1
            duration: .1s
            repeat: -1
  room_2a_time_plus_4:
    widgets:
    - type: text
      text: +4 Seconds
      style: dmd_big
      color: 'FF1030'
      y: 22
    - type: text
      text: (player|room_special_score)
      color: 'FFFF00'
      style: dmd_big
      y: 10
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .1s
          - property: opacity
            value: 1
            duration: .1s
            repeat: -1
  room_2a_time_plus_8:
    widgets:
    - type: text
      text: +8 Seconds
      style: dmd_big
      color: 'FF1030'
      y: 22
    - type: text
      text: (player|room_special_score)
      color: 'FFFF00'
      style: dmd_big
      y: 10
      animations:
        pre_show_slide:
          - property: opacity
            value: 0
            duration: .1s
          - property: opacity
            value: 1
            duration: .1s
            repeat: -1

slide_player:
  mode_room_2a_shifting_sands_started:
    room_2a_backglass_slide:
      target: backglass
    room_2a_splash_slide:
      target: dmd
      expire: 1s
      priority: 500
    room_2a_score_slide:
      target: dmd
  room_2a_bank_1_shot_hit:
    room_2a_time_plus_4:
      target: dmd
      expire: 1s
      priority: 310
  room_2a_bank_2_shot_hit:
    room_2a_time_plus_4:
      target: dmd
      expire: 1s
      priority: 310
  room_2a_bank_3_shot_hit:
    room_2a_time_plus_2:
      target: dmd
      expire: 1s
      priority: 310
  room_2a_bank_4_shot_hit:
    room_2a_time_plus_8:
      target: dmd
      expire: 1s
      priority: 310


event_player:
  mode_room_2a_shifting_sands_started:
    cmd_backbox_show:
      show_type: pour
      count: 3
      min_length: 4
      max_length: 12
      color: "200C00"
    drop_targets_continue:
    cmd_map_position:
      room: '2a'
      visit: True
    cmd_stop_map_music:
  timer_room_2a_do_not_sink_complete:
    - room_2a_sink_into_sand
  room_2a_exit_west_shot_hit.1: drop_targets_save
  room_2a_exit_west_shot_hit.2: room_1z_enter
  room_2a_exit_east_shot_hit.1: drop_targets_save
  room_2a_exit_east_shot_hit.2: room_2b_enter
  room_2a_exit_north_shot_hit.1: drop_targets_save
  room_2a_exit_north_shot_hit.2: room_1q_enter
  mode_room_2a_shifting_sands_ending: drop_targets_save
  timer_room_2a_do_not_sink_tick{current_player.room_2a_seconds_survived > 29}:
    cmd_map_complete:
      room: '2a'

variable_player:
  mode_room_2a_shifting_sands_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2a
      action: set
    room_2a_alive_score:
      action: set
      int: 0
  room_2a_bank_1_shot_hit:
    score: (25000 + (current_player.area_bonus_w * 10000)) * current_player.multiplier
    room_special_score:
      int: (25000 + (current_player.area_bonus_w * 10000)) * current_player.multiplier
      action: set
  room_2a_bank_2_shot_hit:
    score: (50000 + (current_player.area_bonus_e * 10000)) * current_player.multiplier
    room_special_score:
      int: (50000 + (current_player.area_bonus_e * 10000)) * current_player.multiplier
      action: set
  room_2a_bank_3_shot_hit:
    score: (10000) * current_player.multiplier
    room_special_score:
      int: (10000) * current_player.multiplier
      action: set
  room_2a_bank_4_shot_hit:
    score: (150000 + (current_player.area_bonus_nw * 100000)) * current_player.multiplier
    room_special_score:
      int: (150000 + (current_player.area_bonus_nw * 100000)) * current_player.multiplier
      action: set
  timer_room_2a_do_not_sink_tick:
    room_2a_alive_score: 280
    room_2a_seconds_survived: 1
    score: current_player.room_2a_alive_score * current_player.multiplier

