#config_version=5
mode:
    start_events: select_landing_site_maridia_selected, room_2a_continue
    stop_events: game_ending, ball_ending
    # restart_on_next_ball: true
    priority: 300

slides:
  room_2a_backglass_slide:
    widgets:
      - type: image
        image: room_2a_shifting_sands_backglass
    transition: fade
    transition_out: fade
  room_2a_splash_slide:
    widgets:
      - type: image
        image: room_2a_splash

slide_player:
  mode_room_2a_shifting_sands_started:
    room_2a_backglass_slide:
      target: backglass
    room_2a_splash_slide:
      target: dmd
      expire: 1.5s

event_player:
  mode_room_2a_shifting_sands_started:
    cmd_backbox_show:
      show_type: pour
      count: 3
      min_length: 4
      max_length: 12
      color: "101000"

variable_player:
  mode_room_2a_shifting_sands_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2a
      action: set

