#config_version=5
mode:
    start_events: base_bits_medium, base_bits_large
    stop_events: multiball_twitch_bit_donation_multiball_ended
    priority: 400

multiballs:
  twitch_bit_donation_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 30s
    start_or_add_a_ball_events: mode_twitch_bits_multiball_started, base_bits_medium, base_bits_large

show_player:
  multiball_twitch_bit_donation_multiball_started:
    twitch_bit_donation_start_up:
      loops: 0
    blink_light:
      key: twitch_bit_donation_multiball_ball_save_blink
      loops: -1
      speed: 2
      show_tokens:
        led: led_ball_save
        color: '6441a4'
  multiball_twitch_bit_donation_multiball_shoot_again_ended:
    twitch_bit_donation_multiball_ball_save_blink:
      action: stop
  whole_playfield_shot_group_hit:
    twitch_bit_donation_hit:
      loops: 0

variable_player:
  whole_playfield_shot_group_hit:
    score: 500
