#config_version=5
mode:
    start_events: base_bits_medium, base_bits_large
    stop_events: multiball_twitch_bit_donation_multiball_ended
    priority: 400

multiballs:
  twitch_bit_donation_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 30s
    start_or_add_a_ball_events: mode_twitch_bits_multiball_started, base_bits_medium, base_bits_large

show_player:
  multiball_twitch_bit_donation_multiball_started:
    twitch_bit_donation_start_up:
      loops: 0
      tag: twitch_bit_donation_show
  whole_playfield_shot_group_hit:
    twitch_bit_donation_hit:
      loops: 0
      tag: twitch_bit_donation_show

variable_player:
  whole_playfield_shot_group_hit:
    score: 500
