#config_version=5
mode:
  start_events: skillshot_drops_release_should_start
  stop_events: timer_skillshot_drops_release_super_skill_stopped, skillshot_drops_release_should_end
  priority: 500

show_player:
  mode_skillshot_drops_release_started:
    skillshot_drops_release_countdown:
      loops: 0
      events_when_completed: skillshot_drops_release_ball
  skillshot_drops_release_ball:
    skillshot_drops_release_go:
      loops: 0
    blink_2_lights:
      key: skillshot_drops_release_flipper_show
      loops: -1
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_upper_flipper_bottom
        led_2: gi_upper_flipper_top
        color_1: 'FFFFFF'
        color_2: '000000'
    small_theater_chase:
      key: skillshot_drops_release_ramp_show
      loops: -1
      speed: 6
      priority: 600
      show_tokens:
        color: '2000C0'
        led_1: led_enter_side_ramp
        led_2: gi_under_side_ramp
        led_3: led_pop_3
        led_4: led_enter_side_ramp
        led_5: gi_under_side_ramp
        led_6: led_pop_3
  side_ramp_shot_hit:
    skillshot_drops_release_success:
      loops: 0
      events_when_completed: skillshot_drops_release_should_end

timers:
  skillshot_drops_release_super_skill:
    end_value: 5
    tick_interval: 1s
    control_events:
      - event: skillshot_drops_release_ball
        action: restart

event_player:
  skillshot_drops_release_ball:
    - cmd_drop_three_up
    - cmd_drop_one_down
    - cmd_drop_two_down
  mode_skillshot_drops_release_stopping: skillshot_monitor_should_end

variable_player:
  side_ramp_shot_hit:
    score: 250000

sound_player:
  skillshot_drops_release_ball: shoot_the_side_ramp
  side_ramp_shot_hit: super_skillshot
