#config_version=5

mode:
  code: mpf.modes.high_score.code.high_score.HighScore
  priority: 2000
  start_events: game_ending, start_high_score
  game_mode: False
  use_wait_queue: true

sound_player:
  high_score_enter_initials: music_high_score
  mode_high_score_stopping:
    music_high_score:
      action: stop
      fade_out: 15s

high_score:
  _overwrite: True
  enter_initials_timeout: 300
  award_slide_display_time: 4s

  # define your high score categories and the awards
  categories: !!omap
  - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  - spinners:
      - SPIN JUMP CHAMP
  - ramps:
      - RAMP CHAMP
  - pops:
      - POP CHAMP
  - slingshots:
      - SLING CHAMP
  - orbits:
      - ORBIT CHAMP
  - lanes:
      - INSANE LANES
  - bridges:
      - BRIDGE DESTROYER
  - drops:
      - WALL BOMBER
  - missiles:
      - MISSILE COLLECTOR
  - power_bombs:
      - POWER BOMBER
  - rooms_visited:
      - EXPLORER
  - rooms_completed:
      - CONQUEROR

  # set the defaults
  defaults:
    score:
      - ARR: 5000000
      - EAS: 4000000
      - MWS: 3000000
      - KRD: 2000000
      - RID: 1000000
    spinners:
      - SA: 40
    ramps:
      - MB: 5
    pops:
      - RDY: 15
    slingshots:
      - WHT: 20
    orbits:
      - BLZ: 5
    lanes:
      - GRN: 10
    bridges:
      - GNZ: 1
    drops:
      - WHO: 3
    missiles:
      - DAD: 5
    power_bombs:
      - DPF: 5
    rooms_visited:
      - TNA: 5
    rooms_completed:
      - CNK: 1


