#config_version=5

mode:
  priority: 500
  start_events: game_ending, start_high_score
  use_wait_queue: true

high_score:
  _overwrite: True
  enter_initials_timeout: 60
  award_slide_display_time: 4s

  # define your high score categories and the awards
  categories: !!omap
  - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  - spinners:
      - SPIN JUMP CHAMP
  - ramps:
      - RAMP CHAMP
  - pops:
      - POP CHAMP

  # set the defaults
  defaults:
    score:
      - ARR: 500000
      - MWS: 400000
      - EAS: 300000
      - KRD: 200000
      - RID: 100000
    spinners:
      - SA: 40
    ramps:
      - MB: 10
    pops:
      - RDY: 25

# optional: change the slides (you can omit all the following)
slide_player:
  _overwrite: True
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display

slides:
  _overwrite: True
  high_score_enter_initials:
  - type: text
    style: tall_title
    font_size: 18
    text: PLAYER (player_num)
    color: ffff00
    x: 105
    y: 90

  - type: text
    style: tall_title
    font_size: 18
    text: (award)
    color: f0f0f0
    x: 105
    y: 70

  - type: text_input
    initial_char: A
    dynamic_x: false
    key: high_score
    style: tall_title
    font_size: 18
    max_chars: 3
    x: 105
    y: 20
    shift_left_event: sw_lower_left_flipper
    shift_right_event: sw_lower_right_flipper
    select_event: sw_start
    color: ff0000

  - type: text
    style: tall_title
    text: '<       >'
    font_size: 18
    x: 105
    y: 20
    color: ff0000


  - type: text
    text: ''
    key: high_score
    font_size: 18
    style: tall_title
    x: 105
    y: 50
    color: ff00ff
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.3s
        easing: in_out_quint
      - property: opacity
        value: 0
        duration: 0.3s
        repeat: true
        easing: in_out_quint

  high_score_award_display:
  - type: text
    text: (player_name)
    font_size: 18
    style: tall_title
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle
    color: 00ff00
    animations:
      show_slide:
      - property: opacity
        value: 1
        duration: 0.05s
      - property: opacity
        value: 0
        duration: 0.05s
        repeat: true
  - type: text
    text: (award)
    font_size: 18
    style: tall_title
    x: 105
    y: 110
    color: 0000ff
  - type: text
    text: (value)
    style: tall_title
    x: 105
    y: 30
    color: 4040FF
    font_size: 20
    number_grouping: true
    min_digits: 2