#config_version=5
mode:
    start_events: mode_base_starting
    priority: 100

show_player:
  pop_1_shot_hit:
    pop_bumpers_1:
      loops: 0
  pop_2_shot_hit:
    pop_bumpers_2:
      loops: 0
  pop_3_shot_hit:
    pop_bumpers_3:
      loops: 0

variable_player:
  pop_1_shot_hit:
    pops: 1
    score:
      int: (100 + (80 * current_player.pops)) * current_player.multiplier
  pop_2_shot_hit:
    pops: 1
    score:
      int: (100 + (80 * current_player.pops)) * current_player.multiplier
  pop_3_shot_hit:
    pops: 1
    score:
      int: (100 + (80 * current_player.pops)) * current_player.multiplier
