#config_version=5
mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 100

show_player:
  pop_1_shot_hit:
    pop_bumpers_1:
      key: pop_bumpers_image
      loops: 0
    blink_light:
      key: pop_bumpers_blink_1
      loops: 1
      speed: 20
      show_tokens:
        led: led_pop_2
        color: A000FF
  pop_2_shot_hit:
    pop_bumpers_2:
      key: pop_bumpers_image
      loops: 0
    blink_light:
      key: pop_bumpers_blink_2
      loops: 1
      speed: 20
      show_tokens:
        led: led_pop_3
        color: A000FF
  pop_3_shot_hit:
    pop_bumpers_3:
      key: pop_bumpers_image
      loops: 0
    blink_light:
      key: pop_bumpers_blink_3
      loops: 1
      speed: 20
      show_tokens:
        led: led_pop_1
        color: A000FF
  subway_sneak_hit:
    pop_sneak_lights:
      loops: 0
      speed: 30
      priority: 1000

sounds:
  pop_1:
    file: pop_1.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  pop_sneak:
    file: pop_sneak.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

sound_player:
  pop_1_shot_hit: pop_1
  pop_2_shot_hit: pop_1
  pop_3_shot_hit: pop_1
  subway_sneak_hit: pop_sneak

variable_player:
  pop_1_shot_hit:
    pops: 1
    score:
      int: (100 + (80 * current_player.pops)) * current_player.multiplier
  pop_2_shot_hit:
    pops: 1
    score:
      int: (100 + (80 * current_player.pops)) * current_player.multiplier
  pop_3_shot_hit:
    pops: 1
    score:
      int: (100 + (80 * current_player.pops)) * current_player.multiplier
  subway_sneak_hit:
    score: 50000 * current_player.multiplier
