#config_version=5

# https://commons.wikimedia.org/wiki/File:Ruins_at_Watadagaya,_Madirigiriya.jpg

mode:
  start_events: room_2o_continue, room_2o_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2k_enter, room_2n_enter, room_2p_enter, room_2o_exit
  priority: 300


shot_profiles:
  room_2o_increase_1:
    states:
      - name: lit
        show: three_color_blink
        speed: 2
        sync_ms: 500
        show_tokens:
          color1: green
          color2: blue
          color3: red
  room_2o_increase_2:
    states:
      - name: lit
        show: three_color_blink
        speed: 2
        sync_ms: 500
        show_tokens:
          color1: blue
          color2: red
          color3: green
  room_2o_increase_3:
    states:
      - name: lit
        show: three_color_blink
        speed: 2
        sync_ms: 500
        show_tokens:
          color1: red
          color2: green
          color3: blue
  room_2o_switch:
    states:
      - name: lit
        show: fade_one_light
        show_tokens:
          color: green


shots:
  room_2o_exit_north_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_2o_exit_north_shot_hit, metroid_close_doors
    reset_events: room_2o_exit_north_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_2o_exit_west_shot:
    switch: s_ramp_enter
    profile: exit_door_optimum
    enable_events: metroid_open_doors
    disable_events: room_2o_exit_west_shot_hit, metroid_close_doors
    reset_events: room_2o_exit_west_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_2o_exit_east_shot:
    hit_events: rollover_shot_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_2o_exit_east_shot_hit, metroid_close_doors
    reset_events: room_2o_exit_east_shot_hit
    show_tokens:
      led: led_rollover
      color: door_blue
  room_2o_increase_shot_1:
    switch: s_side_ramp_made
    profile: room_2o_increase_1
    enable_events: mode_room_2o_strange_ruins_started
    disable_events: mode_room_2o_strange_ruins_ending
    show_tokens:
      led: led_enter_side_ramp
  room_2o_increase_shot_2:
    hit_events: left_orbit_hit
    profile: room_2o_increase_2
    enable_events: mode_room_2o_strange_ruins_started
    disable_events: mode_room_2o_strange_ruins_ending
    show_tokens:
      led: led_enter_left_orbit
  room_2o_increase_shot_3:
    switch: s_left_passage
    profile: room_2o_increase_3
    enable_events: mode_room_2o_strange_ruins_started
    disable_events: mode_room_2o_strange_ruins_ending
    show_tokens:
      led: led_enter_secret_passage
  room_2o_switch_shot:
    switch: s_scoop
    profile: room_2o_switch
    enable_events: mode_room_2o_strange_ruins_started
    disable_events: mode_room_2o_strange_ruins_ending
    show_tokens:
      led: led_enter_scoop



slides:
  room_2o_strange_ruins_backglass_slide:
    widgets:
      - type: image
        image: room_2o_strange_ruins_backglass
    transition: fade
    transition_out: fade
  room_2o_strange_ruins_splash_slide:
    widgets:
      - type: image
        image: room_2o_strange_ruins_splash

slide_player:
  mode_room_2o_strange_ruins_started:
    room_2o_strange_ruins_backglass_slide:
      target: backglass
    room_2o_strange_ruins_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2o_strange_ruins_started:
    room_2o_strange_ruins_gi:
      loops: -1
      speed: 10
    light_bar_solid:
      loops: -1
      show_tokens:
        color: light_bar_basic
  show_mode_status_report:
    room_2o_strange_ruins_status_report:
      loops: 0
  flipper_cradle_release:
    room_2o_strange_ruins_status_report:
      action: stop

event_player:
  mode_room_2o_strange_ruins_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2o'
      visit: True
    cmd_play_map_music:
      music: music_norfair_deep_intro
    metroid_open_doors:
    drop_target_mode_should_end:
  room_2o_exit_north_shot_hit: room_2k_enter, drop_target_mode_should_start
  room_2o_exit_west_shot_hit: room_2n_enter, drop_target_mode_should_start
  room_2o_exit_east_shot_hit: room_2p_enter, drop_target_mode_should_start

variable_player:
  mode_room_2o_strange_ruins_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2o
      action: set
