#config_version=5

mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 800

sounds:
  boss_hit_power_bomb:
    file: boss_hit_power_bomb.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  boss_hit_missile:
    file: boss_hit_missile.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

achievements:
  boss_ridley:
    show_tokens:
      led: led_boss_1
      color: 'C00000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: ridley_defeated
    select_events: room_2q_enter
    enable_events: boss_achievement_initialize
    sync_ms: 1000
  boss_draygon:
    show_tokens:
      led: led_boss_2
      color: '008080'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: xxxx_i_dont_work
    select_events: room_2g_enter
    enable_events: boss_achievement_initialize
    sync_ms: 1000
  boss_phantoon:
    show_tokens:
      led: led_boss_3
      color: '808000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: xxxx_i_dont_work
    select_events: room_1j_enter
    enable_events: boss_achievement_initialize
    sync_ms: 1000
  boss_kraid:
    show_tokens:
      led: led_boss_4
      color: '008000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: xxxx_i_dont_work
    select_events: room_1x_enter
    enable_events: boss_achievement_initialize
    sync_ms: 1000

achievement_groups:
  boss_achievements:
    achievements: boss_ridley, boss_draygon, boss_phantoon, boss_kraid
    enable_events: boss_achievement_initialize
    events_when_all_completed: metroid_win_all

event_player:
  mode_boss_started{current_player.ball == 1}: boss_achievement_initialize
