#config_version=5

mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 200


timers:
  multiplier_countdown:
    start_value: 1
    end_value: 10000
    tick_interval: 15.0s
    restart_on_complete: True
    control_events:
      - event: multiplier_timer_restart
        action: restart


shots:
  multiplier_increase_value_shot:
    switch: s_thin_orange


event_player:
  mode_multiplier_started: multiplier_timer_restart
  multiplier_increase_value_shot_hit: multiplier_timer_restart
  # timer_multiplier_countdown_tick{current_player.multiplier_charge >= 3 and current_player.multiplier_charge < 6}: multiplier_set_


variable_player:
  mode_multiplier_started:
    multiplier_charge:
      action: set
      int: 0
    multiplier:
      action: set
      int: 1
  multiplier_increase_value_shot_hit:
    multiplier_charge: 1
