#config_version=5

# https://commons.wikimedia.org/w/index.php?search=desert+cave&title=Special:Search&go=Go&ns0=1&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1#/media/File:Sonora_Desert_Museum_cave_-_Flickr_-_gailhampshire_(1).jpg
# https://commons.wikimedia.org/w/index.php?search=desert+cave&title=Special:Search&go=Go&ns0=1&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1#/media/File:GaraCaveInside4.jpg

mode:
  start_events: room_1z_continue, room_1z_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2a_enter, room_2d_enter, room_1z_exit
  priority: 300


timers:
  room_1z_skree_timer:
    start_value: 1
    end_value: 16
    tick_interval: 1s
    control_events:
      - event: room_1z_start_timer
        action: restart
      - event: mode_room_1z_underground_desert_started
        action: stop
      - event: mode_room_1z_underground_desert_ending
        action: stop

shot_profiles:
  room_1z_drop_skree:
    states:
      - name: lit
        show: two_color_blink
        loops: -1
        speed: 5
        show_tokens:
          color1: '10FF40'
          color2: 'FF7000'
  room_1z_strobe:
    states:
    - name: lit
      show: blink_3_lights
      loops: -1


shots:
  room_1z_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1z_exit_east_shot_hit, metroid_close_doors
    reset_events: room_1z_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_1z_exit_south_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1z_exit_south_shot_hit, metroid_close_doors
    reset_events: room_1z_exit_south_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1z_drop_skree_shot:
    switches: s_ramp_enter
    profile: room_1z_drop_skree
    enable_events: room_1z_enable_skree
    disable_events: mode_room_1z_underground_desert_started, room_1z_drop_skree_shot_hit
    reset_events: mode_room_1z_underground_desert_started, room_1z_drop_skree_shot_hit
    show_tokens:
      led: led_enter_ramp
  room_1z_upper_skree_shot:
    switch: s_purple_1, s_purple_2, s_purple_3
    profile: room_1z_strobe
    enable_events: room_1z_enable_upper_skree
    disable_events: mode_room_1z_underground_desert_started, room_1z_upper_skree_shot_hit, room_1z_enable_lower_skree
    reset_events: mode_room_1z_underground_desert_started, room_1z_upper_skree_shot_hit, room_1z_enable_lower_skree
    show_tokens:
      led_1: led_upgrade_bank_1
      led_2: led_upgrade_bank_2
      led_3: led_upgrade_bank_3
      color_1: '808010'
      color_2: stop
  room_1z_lower_skree_1_shot:
    switch: s_missile_bank_1, s_missile_bank_2, s_missile_bank_3
    profile: room_1z_strobe
    enable_events: room_1z_enable_lower_skree
    disable_events: mode_room_1z_underground_desert_started, room_1z_lower_skree_1_shot_hit, room_1z_lower_skree_2_shot_hit, room_1z_enable_skree
    reset_events: mode_room_1z_underground_desert_started, room_1z_lower_skree_1_shot_hit, room_1z_lower_skree_2_shot_hit, room_1z_enable_skree
    show_tokens:
      led_1: led_missile_bank_1
      led_2: led_missile_bank_2
      led_3: led_missile_bank_3
      color_1: '808010'
      color_2: stop
  room_1z_lower_skree_2_shot:
    switch: s_lower_right_bank_1, s_lower_right_bank_2, s_lower_right_bank_3
    profile: room_1z_strobe
    enable_events: room_1z_enable_lower_skree
    disable_events: mode_room_1z_underground_desert_started, room_1z_lower_skree_1_shot_hit, room_1z_lower_skree_2_shot_hit, room_1z_enable_skree
    reset_events: mode_room_1z_underground_desert_started, room_1z_lower_skree_1_shot_hit, room_1z_lower_skree_2_shot_hit, room_1z_enable_skree
    show_tokens:
      led_1: led_bomb_bank_1
      led_2: led_bomb_bank_2
      led_3: led_bomb_bank_3
      color_1: '808010'
      color_2: stop

slides:
  room_underground_desert_backglass_slide:
    widgets:
      - type: image
        image: room_underground_desert_backglass
    transition: fade
    transition_out: fade
  room_underground_desert_splash_slide:
    widgets:
      - type: image
        image: room_underground_desert_splash

slide_player:
  mode_room_1z_underground_desert_started:
    room_underground_desert_backglass_slide:
      target: backglass
    room_underground_desert_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1z_underground_desert_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: 'FFC000'
        color2: '8080FF'
  show_mode_status_report:
    room_1z_underground_desert_status_report:
      loops: 0
  flipper_cradle_release:
    room_1z_underground_desert_status_report:
      action: stop

event_player:
  mode_room_1z_underground_desert_started:
    cmd_backbox_show:
      show_type: pour
      count: 1
      min_length: 4
      max_length: 12
      color: "200C00"
    drop_targets_continue:
    cmd_map_position:
      room: '1z'
      visit: True
    cmd_play_map_music:
      music: music_maridia_intro
    metroid_open_doors:
    room_1z_enable_skree:
  room_1z_drop_skree_shot_hit: room_1z_start_timer, room_1z_enable_upper_skree
  timer_room_1z_skree_timer_tick{ticks == 8}: room_1z_enable_lower_skree
  timer_room_1z_skree_timer_complete: room_1z_enable_skree
  room_1z_exit_east_shot_hit.1: drop_targets_save
  room_1z_exit_east_shot_hit.2: room_2a_enter
  room_1z_exit_south_shot_hit.1: drop_targets_save
  room_1z_exit_south_shot_hit.2: room_2d_enter

variable_player:
  mode_room_1z_underground_desert_started:
    continue_room:
      string: 1z
      action: set
