#config_version=5

mode:
  code: attract.MyAttract

show_player:
  mode_attract_started:
    attract_display_loop:
      priority: 100
      manual_advance: false
  s_right_flipper_active:
    attract_display_loop:
      action: advance
      manual_advance: false
  s_left_flipper_active:
    attract_display_loop:
      action: step_back
      manual_advance: false
  flipper_cancel:
    attract_display_loop:
      priority: 100
      manual_advance: false
  flipper_code_squeak:
    flipper_code_squeak:
      priority: 200
      loops: 0
  twitch_new_chat_message{line_count <= 3}:
    chat_message_3:
      loops: 0
      priority: 200
  twitch_new_chat_message{line_count > 3 and line_count <= 1000}:
    chat_message_6:
      loops: 0
      priority: 200
  twitch_bit_donation:
    bits_small:
      loops: 0
      priority: 300

animations:
  high_score_scroll_up:
    - property: y
      value: 140
      relative: true
      duration: 8s
    - property: y
      value: -140
      relative: true
      duration: 0s
      repeat: true

event_player:
  twitch_new_chat_message:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "400080"
      speed: 2
      repeat: 3
      direction: right
  twitch_bit_donation:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "804040"
      speed: 2
      repeat: 9
      direction: left
  mode_attract_started:
    cmd_backbox_show:
      show_type: rainbow
  mode_attract_stopping:
    cmd_backbox_show:
      show_type: none
