#config_version=5

mode:
  code: attract.MyAttract

show_player:
  mode_attract_started:
    attract_display_loop:
      priority: 100
      manual_advance: false
  s_right_flipper_active:
    attract_display_loop:
      action: advance
      manual_advance: false
  s_left_flipper_active:
    attract_display_loop:
      action: step_back
      manual_advance: false
  flipper_code_squeak:
    flipper_code_squeak:
      priority: 200
      loops: 0
  twitch_new_chat_message:
    who_said_that:
      loops: 0
      priority: 200
  twitch_bit_donation:
    bits_100:
      loops: 0
      priority: 300

animations:
  high_score_scroll_up:
    property: y
    value: 140
    relative: true
    duration: 8s
