#config_version=5

mode:
  code: attract.MyAttract

show_player:
  mode_attract_started:
    attract_display_loop:
      priority: 100
  flipper_code_squeak:
    flipper_code_squeak:
      priority: 200
      loops: 0