#config_version=5

mode:
  code: attract.MyAttract

show_player:
  mode_attract_started:
    attract_display_loop:
      priority: 100
      manual_advance: false
  s_right_flipper_active:
    attract_display_loop:
      action: advance
      manual_advance: false
  s_left_flipper_active:
    attract_display_loop:
      action: step_back
      manual_advance: false
  flipper_cancel:
    attract_display_loop:
      priority: 100
      manual_advance: false
  flipper_code_squeak:
    flipper_code_squeak:
      priority: 200
      loops: 0
  flipper_code_no_music:
    flipper_code_no_music:
      priority: 200
      loops: 0
  twitch_new_chat_message{line_count <= 3}:
    chat_message_3:
      loops: 0
      priority: 200
  twitch_new_chat_message{line_count > 3 and line_count <= 1000}:
    chat_message_6:
      loops: 0
      priority: 200
  twitch_bit_donation:
    bits_small:
      loops: 0
      priority: 300
  slide_last_game_high_scores_active:
    attract_water:
      action: stop
    lights_rainbow_blurred:
      loops: -1
      speed: 10
  slide_press_start_active:
    lights_rainbow_blurred:
      action: stop
    gi_solid:
      key: attract_lights_press_start_gi
      loops: -1
      speed: 10
      show_tokens:
        color: '009000'
    theater_chase:
      key: attract_lights_press_start
      loops: -1
      speed: 10
      show_tokens:
        color: '009000'
  slide_fast_logo_active:
    attract_lights_press_start:
      action: stop
    attract_lights_press_start_gi:
      action: stop
    gi_solid:
      key: attract_lights_fast_logo_gi
      loops: -1
      speed: 10
      show_tokens:
        color: '900000'
    theater_chase:
      key: attract_lights_fast_logo
      loops: -1
      speed: 10
      show_tokens:
        color: '900000'
  slide_mission_pinball_active:
    attract_lights_fast_logo:
      action: stop
    attract_lights_fast_logo_gi:
      action: stop
    gi_solid:
      key: attract_lights_mission_pinball_gi
      loops: -1
      speed: 10
      show_tokens:
        color: '000090'
    theater_chase:
      key: attract_lights_mission_pinball
      loops: -1
      speed: 10
      show_tokens:
        color: '000090'
  slide_arrrrrcade_active:
    attract_lights_mission_pinball:
      action: stop
    attract_lights_mission_pinball_gi:
      action: stop
    drizzle:
      key: attract_lights_arrrrrcade
      loops: -1
      speed: 10
      show_tokens:
        color: '900000'
  slide_metroid_logo_active:
    attract_lights_arrrrrcade:
      action: stop
    lights_samus_logo:
      loops: -1
      speed: 10
  slide_claire_samus_active:
    lights_samus_logo:
      action: stop
    lights_fire:
      loops: -1
      speed: 15
  slide_stemage_slide_active:
    lights_fire:
      action: stop
    lights_asterix_spin:
      loops: -1
      speed: 14
  slide_joel_slide_active:
    lights_asterix_spin:
      action: stop
    gi_solid:
      key: attract_lights_joel_gi
      loops: -1
      show_tokens:
        color: 'c1a24d'
  slide_double_danger_slide_active:
    attract_lights_joel_gi:
      action: stop
    lights_fire:
      loops: -1
      speed: 15
  slide_rudy_slide_active:
    lights_fire:
      action: stop
    rudy_tas:
      loops: -1
      speed: 19
  slide_erin_slide_active:
    rudy_tas:
      action: stop
    attract_pinball_monkey:
      loops: -1
      speed: 15
  slide_rubber_ducks_slide_active:
    attract_pinball_monkey:
      action: stop
    lights_fire:
      loops: -1
      speed: 15
  slide_owl_slide_active:
    lights_fire:
      action: stop
    lights_purple_spotlight:
      loops: -1
      speed: 20
  slide_attract_special_thanks_slide_active:
    lights_purple_spotlight:
      action: stop
    attract_water:
      loops: -1
      speed: 8

animations:
  high_score_scroll_up:
    - property: y
      value: 140
      relative: true
      duration: 8s
    - property: y
      value: -140
      relative: true
      duration: 0s
      repeat: true
  special_thanks_scroll_up:
    - property: y
      value: 150
      relative: true
      duration: 8s
    - property: y
      value: -150
      relative: true
      duration: 0s
      repeat: true

event_player:
  twitch_new_chat_message:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "400080"
      speed: 2
      repeat: 3
      direction: right
  twitch_bit_donation:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "804040"
      speed: 2
      repeat: 9
      direction: left
  slide_last_game_high_scores_active:
    cmd_backbox_show:
      show_type: rainbow
  slide_fast_logo_active:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 5
      max_cutoff: 5
      color1: "400000"
      color2: "000040"
  slide_press_start_active:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 5
      max_cutoff: 5
      color1: "404040"
      color2: "004000"
  slide_arrrrrcade_active:
    cmd_backbox_show:
      show_type: pour
      count: 7
      min_length: 2
      max_length: 16
      color: "400000"
  slide_metroid_logo_active:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 2
      max_cutoff: 8
      color1: "404040"
      color2: "000040"
  slide_double_danger_slide_active:
    cmd_backbox_show:
      show_type: drop
      min_delay: 4
      max_delay: 6
      background_color: "040000"
      drop_color: "100C00"
  slide_pbu_slide_active:
    cmd_backbox_show:
      show_type: fire
  slide_erin_slide_active:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 8
      max_cutoff: 8
      color1: "000040"
      color2: "401800"
  slide_rubber_ducks_slide_active:
    cmd_backbox_show:
      show_type: fire
  slide_owl_slide_active:
    cmd_backbox_show:
      show_type: pour
      count: 4
      min_length: 2
      max_length: 16
      color: "401040"
  slide_attract_special_thanks_slide_active:
    cmd_backbox_show:
      show_type: pour
      count: 6
      min_length: 3
      max_length: 10
      color: "000040"


  mode_attract_stopping:
    cmd_backbox_show:
      show_type: none
