#config_version=5
mode:
    start_events: ball_starting
    priority: 100
    code: base.Base

shots:
  scoop_shot:
    switch: s_scoop
  ramp_shot:
    switch: s_ramp_enter
  side_ramp_shot:
    switch: s_side_ramp_made
  secret_passage_shot:
    switch: s_left_passage
  upper_right_sling_shot:
    switch: s_pop_sling
  upper_left_sling_shot:
    switch: s_upper_sling
  left_sling_shot:
    switch: s_left_sling
  right_sling_shot:
    switch: s_right_sling
  pop_1_shot:
    switch: s_pop_1
  pop_2_shot:
    switch: s_pop_2
  pop_3_shot:
    switch: s_pop_3
  left_outlane_shot:
    switch: s_left_outlane
  left_inlane_shot:
    switch: s_left_inlane
  right_outlane_shot:
    switch: s_right_outlane
  right_inlane_shot:
    switch: s_right_inlane
  spinner_shot:
    switch: s_spinner
  big_red_shot:
    switch: s_big_red
  rollover_shot:
    switch: s_rollover_button
  shatz_shot:
    switch: s_shatz
  purple_1_shot:
    switch: s_purple_1
  purple_2_shot:
    switch: s_purple_2
  purple_3_shot:
    switch: s_purple_3
  captive_shot:
    switch: s_captive_ball
  side_1_shot:
    switch: s_left_target_1
  side_2_shot:
    switch: s_left_target_2
  lower_right_bank_1_shot:
   switch: s_lower_right_bank_1
  lower_right_bank_2_shot:
   switch: s_lower_right_bank_2
  lower_right_bank_3_shot:
   switch: s_lower_right_bank_3

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: yes
    balls_to_save: 1
    debug: yes

show_player:
  full_shatz_hit:
    base_full_shatz:
      loops: 0
      priority: 10
  shatz_shot_hit:
    base_white_target:
      loops: 0
  capside_combo_hit:
    base_capside_combo:
      loops: 0
  twitch_new_chat_message:
    who_said_that:
      loops: 0
  base_bits_small:
    bits_small:
      loops: 0

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        style: dmd_big
        y: 18
      - type: text
        text: PLAYER (number)
        y: 0
        x: 10
        style: dmd_med
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 0
        x: right-10
        anchor_x: right
        anchor_y: bottom
        style: dmd_med

variable_player:
  left_orbit_hit:
    orbits: 1
    score:
      int: (current_player.orbits * 500) + (current_player.spinners * 10)
  right_orbit_hit:
    orbits: 1
    score:
      int: (current_player.orbits * 500) + (current_player.spinners * 10)
  ramp_shot_hit:
    ramps: 1
    score:
      int: current_player.ramps * 1250
  side_ramp_shot_hit:
    ramps: 1
    score:
      int: current_player.ramps * 2010
  secret_passage_shot_hit:
    score: 420
  upper_right_sling_shot_hit:
    slingshots: 1
    score:
      int: 100 + (10 * current_player.slingshots)
  upper_left_sling_shot_hit:
    slingshots: 1
    score:
      int: 100 + (10 * current_player.slingshots)
  left_sling_shot_hit:
    slingshots: 1
    score:
      int: 100 + (10 * current_player.slingshots)
  right_sling_shot_hit:
    slingshots: 1
    score:
      int: 100 + (10 * current_player.slingshots)
  left_outlane_shot_hit:
    lanes: 1
    score:
      int: 100 + (10 * current_player.lanes)
  left_inlane_shot_hit:
    lanes: 1
    score:
      int: 100 + (10 * current_player.lanes)
  right_outlane_shot_hit:
    lanes: 1
    score:
      int: 100 + (10 * current_player.lanes)
  right_inlane_shot_hit:
    lanes: 1
    score:
      int: 100 + (10 * current_player.lanes)
  big_red_shot_hit:
    score: 5000
  rollover_shot_hit:
    score: 1000
  shatz_shot_hit:
    score: 1500
  full_shatz_hit:
    score: 10000
  captive_shot_hit:
    captives: 1
    score:
      int: 500 + (500 * current_player.captives)
  side_1_shot_hit:
    score: 25000
  side_2_shot_hit:
    score: 25000
  capside_combo_hit:
    capsides: 1
    score:
      int: 10000 + (2000 * current_player.capsides)
  scoop_shot_hit:
    scoops: 1
    score:
      int: 1000 + (500 * current_player.scoops)
