#config_version=5
mode:
  start_events: ball_starting
  priority: 100

config:
  - music_player.yaml

shots:
  scoop_shot:
    switch: s_scoop
  ramp_shot:
    switch: s_ramp_enter
  side_ramp_shot:
    switch: s_side_ramp_made
  secret_passage_shot:
    switch: s_left_passage
  upper_right_sling_shot:
    switch: s_pop_sling
  upper_left_sling_shot:
    switch: s_upper_sling
  left_sling_shot:
    switch: s_left_sling
  right_sling_shot:
    switch: s_right_sling
  pop_1_shot:
    switch: s_pop_1
  pop_2_shot:
    switch: s_pop_2
  pop_3_shot:
    switch: s_pop_3
  spinner_shot:
    switch: s_spinner
  pop_subway_shot:
    switch: s_pop_subway
  rollover_shot:
    switch: s_rollover_button
  shatz_shot:
    switch: s_shatz
  captive_shot:
    switch: s_captive_ball
  side_1_shot:
    switch: s_left_target_1
  side_2_shot:
    switch: s_left_target_2
  side_3_shot:
    switch: s_left_target_3
  missile_bank_1_shot:
    switch: s_missile_bank_1
  missile_bank_2_shot:
    switch: s_missile_bank_2
  missile_bank_3_shot:
    switch: s_missile_bank_3
  the_pit_shot:
    switch: s_pit

shot_groups:
  whole_playfield_shot_group:
    shots:
      - scoop_shot
      - ramp_shot
      - side_ramp_shot
      - secret_passage_shot
      - upper_right_sling_shot
      - upper_left_sling_shot
      - left_sling_shot
      - right_sling_shot
      - pop_1_shot
      - pop_2_shot
      - pop_3_shot
      - left_outlane_shot
      - right_outlane_shot
      - left_inlane_shot
      - right_inlane_shot
      - spinner_shot
      - pop_subway_shot
      - rollover_shot
      - shatz_shot
      - purple_1_shot
      - purple_2_shot
      - purple_3_shot
      - captive_shot
      - side_1_shot
      - side_2_shot
      - side_3_shot
      - power_bomb_1_shot
      - power_bomb_2_shot
      - power_bomb_3_shot
      - missile_bank_1_shot
      - missile_bank_2_shot
      - missile_bank_3_shot
      - the_pit_shot

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: yes
    balls_to_save: 1
    debug: yes

show_player:
  full_shatz_hit:
    base_full_shatz:
      loops: 0
      priority: 10
  shatz_shot_hit:
    base_white_target:
      loops: 0
  capside_combo_hit:
    base_capside_combo:
      loops: 0
  twitch_new_chat_message{line_count <= 3}:
    chat_message_3:
      loops: 0
      priority: 200
  twitch_new_chat_message{line_count > 3 and line_count <= 1000}:
    chat_message_6:
      loops: 0
      priority: 200
  base_bits_small:
    bits_small:
      loops: 0
  ball_save_default_disabled:
    base_ball_save_default_blink:
      action: stop
  ball_save_default_enabled:
    blink_light:
      key: base_ball_save_default_blink
      loops: -1
      speed: 2
      show_tokens:
        led: led_ball_save
        color: ff0000
  left_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_left_sling_top
        led_2: gi_left_sling_bottom
        color_1: 'FFFFFF'
        color_2: '000000'
  right_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_right_sling_top
        led_2: gi_right_sling_bottom
        color_1: 'FFFFFF'
        color_2: '000000'
  upper_left_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_missile_bank
        led_2: gi_middle_sling
        color_1: 'FFFFFF'
        color_2: '000000'
  upper_right_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_under_side_ramp
        led_2: led_null
        color_1: 'FFFFFF'
        color_2: '000000'
  rollover_shot_hit:
    blink_light:
      key: rollover_blink
      loops: 4
      speed: 3
      show_tokens:
        led: led_rollover
        color: ff0000
  the_pit_shot_hit:
    base_the_pit:
      loops: 0
    blink_light:
      key: pit_blink
      loops: 10
      speed: 15
      show_tokens:
        led: led_pit
        color: ff0000


slide_player:
  mode_base_started: score_slide
  player_added:
    new_player_slide:
      priority: 1000

slides:
  score_slide:
    widgets:
    - type: text
      text: (score)
      number_grouping: true
      min_digits: 2
      style: dmd_big
      y: 18
    - type: text
      text: PLAYER (number)
      y: 0
      x: 10
      style: dmd_med
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: BALL (ball)
      y: 0
      x: right-10
      anchor_x: right
      anchor_y: bottom
      style: dmd_med
  new_player_slide:
    expire: 1s
    widgets:
      - type: text
        text: PLAYER (num) ADDED
        style: dmd_med

event_player:
  twitch_bit_donation{bits < 25}: base_bits_small
  twitch_bit_donation{bits >= 25 and bits < 500}: base_bits_medium
  twitch_bit_donation{bits >= 500}: base_bits_large
  twitch_new_chat_message:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "802000"
      speed: 1
      repeat: 3
      direction: left
  base_bits_small:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "A00000"
      speed: 1
      repeat: 4
      direction: left
  base_bits_medium:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "A00000"
      speed: 1
      repeat: 9
      direction: left
  base_bits_large:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "A00000"
      speed: 1
      repeat: 20
      direction: left

variable_player:
  left_orbit_hit:
    orbits: 1
    score:
      int: ((current_player.orbits * 500) + (current_player.spinners * 10) + (current_player.area_bonus_nw * 500)) * current_player.multiplier
  right_orbit_hit:
    orbits: 1
    score:
      int: ((current_player.orbits * 500) + (current_player.spinners * 10) + (current_player.area_bonus_ne * 500)) * current_player.multiplier
  ramp_shot_hit:
    ramps: 1
    score:
      int: ((current_player.ramps * 1250) + (current_player.area_bonus_nw * 1000)) * current_player.multiplier
  side_ramp_shot_hit:
    ramps: 1
    score:
      int: ((current_player.ramps * 2010) + (current_player.area_bonus_ne * 1000)) * current_player.multiplier
  secret_passage_shot_hit:
    score: 420 + (current_player.area_bonus_w * 1000)
  upper_right_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots)) * current_player.multiplier
  upper_left_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots + (current_player.area_bonus_w * 500))) * current_player.multiplier
  left_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots) + (current_player.area_bonus_sw * 500)) * current_player.multiplier
  right_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots) + (current_player.area_bonus_se * 500)) * current_player.multiplier
  pop_subway_shot_hit:
    score: 10000 * current_player.multiplier
  rollover_shot_hit:
    score: (2500 + (current_player.area_bonus_e * 2500)) * current_player.multiplier
  shatz_shot_hit:
    score: 1500 * current_player.multiplier
  full_shatz_hit:
    score: 30000 * current_player.multiplier
  captive_shot_hit:
    captives: 1
    score:
      int: (500 + (500 * current_player.captives) + (current_player.area_bonus_ne * 2000)) * current_player.multiplier
  side_1_shot_hit:
    score: 25000 * current_player.multiplier
  side_2_shot_hit:
    score: 25000 * current_player.multiplier
  side_3_shot_hit:
    score: 25000 * current_player.multiplier
  capside_combo_hit:
    capsides: 1
    score:
      int: (10000 + (2000 * current_player.capsides)) * current_player.multiplier
  scoop_shot_hit:
    scoops: 1
    score:
      int: (1000 + (500 * current_player.scoops)) * current_player.multiplier
  whole_playfield_shot_group_hit:
    switches: 1
  mode_base_started:
    emergency_landings:
      action: set
      int: 0
  the_pit_shot_hit:
    score: 16660 * current_player.multiplier

sounds:
  left_sling:
    file: left_sling.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  right_sling:
    file: right_sling.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  mid_sling:
    file: mid_sling.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  mini_loop:
    file: mini_loop.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_1:
    file: ramp_sound_1.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_2:
    file: ramp_sound_2.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_3:
    file: ramp_sound_3.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_4:
    file: ramp_sound_4.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

#sound_pools:
#  ramp_sound_pool:
#    type: random
#    sounds: ramp_sound_1, ramp_sound_2, ramp_sound_3, ramp_sound_4

sound_player:
  ball_started{ball > 1 and player == 1}: player_1
  ball_started{ball > 1 and player == 2}: player_2
  ball_started{ball > 1 and player == 3}: player_3
  ball_started{ball > 1 and player == 4}: player_4
  twitch_bit_donation{bits < 100}: jackpot
  twitch_bit_donation{bits >= 100 and bits < 500}: super_jackpot
  twitch_bit_donation{bits >= 500}: double_super_jackpot
  player_added{num == 2}: player_2
  player_added{num == 3}: player_3
  player_added{num == 4}: player_4
  left_sling_shot_hit: left_sling
  right_sling_shot_hit: right_sling
  upper_left_sling_shot_hit: mid_sling
  ramp_shot_hit: ramp_sound_1
  side_ramp_shot_hit: ramp_sound_4
  secret_passage_shot_hit: ramp_sound_2
  rollover_shot_hit: mini_loop
