#config_version=5
mode:
  code: base.Base
  start_events: ball_starting
  priority: 100

config:
  - music_player.yaml

shot_profiles:
  pop_bumper:
    states:
      - name: unlit
        show: led_color
        show_tokens:
          color: '808080'

shots:
  scoop_shot:
    switch: s_scoop
  side_ramp_shot:
    switch: s_side_ramp_made
  secret_passage_shot:
    switch: s_left_passage
  upper_right_sling_shot:
    switch: s_pop_sling
  upper_left_sling_shot:
    switch: s_upper_sling
  left_sling_shot:
    switch: s_left_sling
  right_sling_shot:
    switch: s_right_sling
  pop_1_shot:
    switch: s_pop_1
    profile: pop_bumper
    show_tokens:
      led: led_pop_2
  pop_2_shot:
    switch: s_pop_2
    profile: pop_bumper
    show_tokens:
      led: led_pop_3
  pop_3_shot:
    switch: s_pop_3
    profile: pop_bumper
    show_tokens:
      led: led_pop_1
  spinner_shot:
    switch: s_spinner
  pop_subway_shot:
    switch: s_pop_subway
  rollover_shot:
    switch: s_rollover_button
  shatz_shot:
    switch: s_shatz
  captive_shot:
    switch: s_captive_ball
  the_pit_shot:
    switch: s_pit
  thin_orange_shot:
    switch: s_thin_orange
  vuk_shot:
    switch: s_vuk

shot_groups:
  whole_playfield_shot_group:
    shots:
      - scoop_shot
      - ramp_shot
      - side_ramp_shot
      - secret_passage_shot
      - upper_right_sling_shot
      - upper_left_sling_shot
      - left_sling_shot
      - right_sling_shot
      - left_outlane_shot
      - right_outlane_shot
      - left_inlane_shot
      - right_inlane_shot
      - pop_subway_shot
      - rollover_shot
      - miniboss_level_1_1_shot
      - miniboss_level_1_2_shot
      - miniboss_level_1_3_shot
      - miniboss_level_2_1_shot
      - miniboss_level_2_2_shot
      - miniboss_level_2_3_shot
      - miniboss_level_3_1_shot
      - miniboss_level_3_2_shot
      - miniboss_level_3_3_shot
      - miniboss_level_4_1_shot
      - miniboss_level_4_2_shot
      - miniboss_level_4_3_shot
      - captive_shot
      - side_1_shot
      - side_2_shot
      - side_3_shot
      - power_bomb_1_shot
      - power_bomb_2_shot
      - power_bomb_3_shot
      - missile_bank_1_shot
      - missile_bank_2_shot
      - missile_bank_3_shot
      - the_pit_shot
      - thin_orange_shot

ball_saves:
  default:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    auto_launch: yes
    balls_to_save: 1
    debug: yes

timers:
  base_possible_dirty_pool:
    end_value: 4
    tick_interval: 1s
    control_events:
      - event: dirty_pool_possible
        action: restart
  base_twitch_left_flipper_timer:
    end_value: 2
    tick_interval: 1s
    control_events:
      - event: twitch_flip_left
        action: start
      - event: timer_base_twitch_left_flipper_timer_complete
        action: reset
      - event: timer_base_twitch_left_flipper_timer_complete
        action: stop
  base_twitch_right_flipper_timer:
    end_value: 2
    tick_interval: 1s
    control_events:
      - event: twitch_flip_right
        action: start
      - event: timer_base_twitch_right_flipper_timer_complete
        action: reset
      - event: timer_base_twitch_right_flipper_timer_complete
        action: stop


show_player:
  base_start_single_player:
    base_single_player:
      key: base_score_loop
      loops: -1
  base_start_multi_player_one:
    base_multi_player_one:
      key: base_score_loop
      loops: -1
  base_start_multi_player_two:
    base_multi_player_two:
      key: base_score_loop
      loops: -1
  base_start_multi_player_three:
    base_multi_player_three:
      key: base_score_loop
      loops: -1
  base_start_multi_player_four:
    base_multi_player_four:
      key: base_score_loop
      loops: -1
  full_shatz_hit:
    base_full_shatz:
      loops: 0
      priority: 10
    blink_light:
      key: full_shatz_shot_blink
      priority: 320
      loops: 8
      speed: 18
      show_tokens:
        led: led_zero_suit
        color: '00FF00'
  shatz_shot_hit:
    base_white_target:
      loops: 0
    blink_light:
      key: shatz_shot_blink
      priority: 310
      loops: 8
      speed: 18
      show_tokens:
        led: led_zero_suit
        color: '0000FF'
  capside_combo_hit:
    base_capside_combo:
      loops: 0
  reload_combo_hit:
    base_recharge_combo_lights:
      loops: 0
      priority: 9000
      speed: 60
  twitch_chat_message{line_count <= 3}:
    chat_message_3:
      loops: 0
      priority: 20000
  twitch_chat_message{line_count > 3 and line_count <= 1000}:
    chat_message_6:
      loops: 0
      priority: 20000
  base_bits_small:
    bits_small:
      loops: 0
  ball_save_default_grace_period:
    base_ball_save_default_blink:
      action: stop
  ball_save_default_disabled:
    base_ball_save_default_blink:
      action: stop
  ball_save_default_hurry_up:
    blink_light:
      key: base_ball_save_default_blink
      loops: -1
      speed: 4
      show_tokens:
        led: led_ball_save
        color: ff0000
  ball_save_default_enabled:
    blink_light:
      key: base_ball_save_default_blink
      loops: -1
      speed: 2
      show_tokens:
        led: led_ball_save
        color: ff0000
  ball_save_default_saving_ball:
    base_default_ball_save:
      loops: 0
      speed: 40
      priority: 10000
  left_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_left_sling_top
        led_2: gi_left_sling_bottom
        color_1: 'FFFFFF'
        color_2: '000000'
  right_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_right_sling_top
        led_2: gi_right_sling_bottom
        color_1: 'FFFFFF'
        color_2: '000000'
  upper_left_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_missile_bank
        led_2: gi_middle_sling
        color_1: 'FFFFFF'
        color_2: '000000'
  upper_right_sling_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_under_side_ramp
        led_2: led_null
        color_1: 'FFFFFF'
        color_2: '000000'
  vuk_shot_hit:
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 3
      show_tokens:
        led_1: gi_strip_8
        led_2: gi_strip_9
        color_1: 'FF0000'
        color_2: '0000FF'
  scoop_shot_hit:
    blink_light:
      key: scoop_blink
      loops: 4
      speed: 5
      show_tokens:
        led: led_enter_scoop
        color: ffff00
  rollover_shot_hit:
    blink_light:
      key: rollover_blink
      loops: 4
      speed: 3
      show_tokens:
        led: led_rollover
        color: ff0000
  the_pit_shot_hit:
    base_the_pit:
      priority: 666
      loops: 0
    blink_light:
      key: pit_blink
      priority: 500
      loops: 10
      speed: 15
      show_tokens:
        led: led_pit
        color: ff0000
  thin_orange_shot_hit:
    blink_light:
      key: thin_orange_blink
      priority: 500
      loops: 8
      speed: 18
      show_tokens:
        led: led_thin_orange
        color: ff9000
  dirty_pool_locked:
    base_dirty_pool:
      loops: 0
  secret_passage_shot_hit:
    blink_3_lights:
      loops: 0
      priority: 500
      speed: 3
      show_tokens:
        led_1: gi_behind_zero_suit
        led_2: gi_missile_bank
        led_3: gi_middle_sling
        color_1: 'FF0000'
        color_2: '000000'
  pop_subway_shot_hit:
    blink_3_lights:
      loops: 0
      priority: 500
      speed: 3
      show_tokens:
        led_1: led_pop_1
        led_2: led_pop_2
        led_3: led_pop_3
        color_1: 'FF0000'
        color_2: '000000'
  flipper_cradle:
    base_status_report:
      loops: 0
      priority: 1000
      events_when_completed: show_mode_status_report
  flipper_cradle_release:
    base_status_report:
      action: stop


slide_player:
  player_added:
    new_player_slide:
      priority: 1000

slides:
  score_slide:
    widgets:
    - type: text
      text: (score)
      number_grouping: true
      min_digits: 2
      style: dmd_big
      y: 18
    - type: text
      text: PLAYER (number)
      y: 0
      x: 10
      style: dmd_med
      anchor_x: left
      anchor_y: bottom
    - type: text
      text: BALL (ball)
      y: 0
      x: right-10
      anchor_x: right
      anchor_y: bottom
      style: dmd_med
  new_player_slide:
    expire: 1s
    widgets:
      - type: text
        text: PLAYER (num) ADDED
        style: dmd_med

event_player:
  twitch_bit_donation{bits < 25}: base_bits_small
  twitch_bit_donation{bits >= 25 and bits < 500}: base_bits_medium
  twitch_bit_donation{bits >= 500}: base_bits_large
  twitch_chat_message:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "802000"
      speed: 1
      repeat: 3
      direction: left
  base_bits_small:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "A00000"
      speed: 1
      repeat: 4
      direction: down
  base_bits_medium:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "A00000"
      speed: 1
      repeat: 9
      direction: down
  base_bits_large:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "A00000"
      speed: 1
      repeat: 20
      direction: down
  twitch_flip_left:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "432c6f"
      speed: 1
      repeat: 1
      direction: right
  twitch_flip_right:
    cmd_backbox_show_overlay:
      show_type: sweep_horizontal
      color: "432c6f"
      speed: 1
      repeat: 1
      direction: left
  timer_base_twitch_left_flipper_timer_complete: twitch_unflip_left
  timer_base_twitch_right_flipper_timer_complete: twitch_unflip_right
  player_added{num == 2}: base_sound_player_2
  player_added{num == 3}: base_sound_player_3
  player_added{num == 4}: base_sound_player_4
  player_added{current_player.number == 1}: base_start_multi_player_one
  player_added{current_player.number == 2}: base_start_multi_player_two
  player_added{current_player.number == 3}: base_start_multi_player_three
  mode_base_started{game.num_players == 1}: base_start_single_player
  mode_base_started{game.num_players > 1 and current_player.number == 1}: base_start_multi_player_one
  mode_base_started{game.num_players > 1 and current_player.number == 2}: base_start_multi_player_two
  mode_base_started{game.num_players > 1 and current_player.number == 3}: base_start_multi_player_three
  mode_base_started{game.num_players > 1 and current_player.number == 4}: base_start_multi_player_four
  mode_base_started{machine.next_game_bao == 0}: metroid_base_started, base_skillshot_should_start
  mode_base_started{machine.next_game_bao == 1}: bao_base_started
  mode_base_started{machine.next_game_goren == 1}: gorens_lament_should_start
  base_skillshot_should_start: skillshot_should_start
  ball_save_default_saving_ball:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "FF2000"
      speed: 1
      repeat: 0
      direction: up
  mode_bonus_will_start: stop_current_music, cmd_stop_all_music


variable_player:
  left_orbit_hit:
    orbits: 1
    score:
      int: ((current_player.orbits * 500) + (current_player.spinners * 10) + (current_player.area_bonus_nw * 500)) * current_player.multiplier
  right_orbit_hit:
    orbits: 1
    score:
      int: ((current_player.orbits * 500) + (current_player.spinners * 10) + (current_player.area_bonus_ne * 500)) * current_player.multiplier
  side_ramp_shot_hit:
    ramps: 1
    score:
      int: ((current_player.ramps * 2010) + (current_player.area_bonus_ne * 1000)) * current_player.multiplier
  secret_passage_shot_hit:
    score: 420 + (current_player.area_bonus_w * 1000)
  upper_right_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots)) * current_player.multiplier
  upper_left_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots + (current_player.area_bonus_w * 500))) * current_player.multiplier
  left_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots) + (current_player.area_bonus_sw * 500)) * current_player.multiplier
  right_sling_shot_hit:
    slingshots: 1
    score:
      int: (100 + (10 * current_player.slingshots) + (current_player.area_bonus_se * 500)) * current_player.multiplier
  pop_subway_shot_hit:
    score: 10000 * current_player.multiplier
  rollover_shot_hit:
    score: (2500 + (current_player.area_bonus_e * 2500)) * current_player.multiplier
  shatz_shot_hit:
    score: 1500 * current_player.multiplier
  full_shatz_hit:
    score: 30000 * current_player.multiplier
  captive_shot_hit:
    captives: 1
    score:
      int: (500 + (500 * current_player.captives) + (current_player.area_bonus_ne * 2000)) * current_player.multiplier
  capside_combo_hit:
    capsides: 1
    score:
      int: (10000 + (2000 * current_player.capsides)) * current_player.multiplier
  reload_combo_hit:
    score: 250000 * current_player.multiplier
  scoop_shot_hit:
    scoops: 1
    score:
      int: (1000 + (500 * current_player.scoops)) * current_player.multiplier
  whole_playfield_shot_group_hit:
    switches: 1
  mode_base_started:
    emergency_landings:
      action: set
      int: 0
  the_pit_shot_hit:
    score: 16660 * current_player.multiplier
  thin_orange_shot_hit:
    score: 800 * current_player.multiplier
  vuk_shot_hit:
    score: 10000 * current_player.multiplier
  dirty_pool_locked:
    score: 66600 * current_player.multiplier

sounds:
  energy_target:
    file: energy_target.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  left_orbit:
    file: left_orbit.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  right_orbit:
    file: right_orbit.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  left_sling:
    file: left_sling.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  right_sling:
    file: right_sling.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  mid_sling:
    file: mid_sling.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  mini_loop:
    file: mini_loop.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_2:
    file: ramp_sound_2.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_3:
    file: ramp_sound_3.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  ramp_sound_4:
    file: ramp_sound_4.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  scoop_eject:
    file: scoop_eject.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  zero_suit_target:
    file: zero_suit_target.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

sound_player:
  twitch_bit_donation{bits < 100}: jackpot
  twitch_bit_donation{bits >= 100 and bits < 500}: super_jackpot
  twitch_bit_donation{bits >= 500}: double_super_jackpot
  base_sound_player_2: player_2
  base_sound_player_3: player_3
  base_sound_player_4: player_4
  left_sling_shot_hit: left_sling
  right_sling_shot_hit: right_sling
  upper_left_sling_shot_hit: mid_sling
  side_ramp_shot_hit: ramp_sound_4
  secret_passage_shot_hit: ramp_sound_2
  rollover_shot_hit: mini_loop
  scoop_shot_hit: scoop_eject
  thin_orange_shot_hit: energy_target
  shatz_shot_hit: zero_suit_target
  left_orbit_hit: left_orbit
  right_orbit_hit: right_orbit
