#config_version=5
mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        style: dmd_big
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        style: dmd_med
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        style: dmd_med

