#config_version=5

sound_player:
  mode_room_1b_gunship_started: music_crateria
  mode_room_1b_gunship_victory_started: music_crateria
  mode_room_1l_entryway_started: music_wrecked_ship
  mode_room_1r_space_pirate_battle_started: music_brinstar
  mode_room_2a_shifting_sands_started: music_maridia
  mode_room_2a_sandy_cavern_started: music_maridia
  mode_room_2i_lava_jump_started: music_norfair
  mode_bonus_started:
    music_crateria:
      action: stop
      fade_out: 3s
    music_brinstar:
      action: stop
      fade_out: 3s
    music_norfair:
      action: stop
      fade_out: 3s
    music_maridia:
      action: stop
      fade_out: 3s
    music_wrecked_ship:
      action: stop
      fade_out: 3s
