#config_version=5

sound_player:
  music_player_play_music_boss: music_boss
  music_player_play_music_brinstar: music_brinstar
  music_player_play_music_brinstar_calm: music_brinstar_calm
  music_player_play_music_brinstar_side_entrance: music_brinstar_side_entrance
  music_player_play_music_crateria: music_crateria
  music_player_play_music_maridia: music_maridia
  music_player_play_music_maridia_intro: music_maridia_intro
  music_player_play_music_maridia_snow: music_maridia_snow
  music_player_play_music_metal_item_room: music_metal_item_room
  music_player_play_music_norfair: music_norfair
  music_player_play_music_norfair_calm: music_norfair_calm
  music_player_play_music_norfair_deep: music_norfair_deep
  music_player_play_music_norfair_deep_intro: music_norfair_deep_intro
  music_player_play_music_wrecked_ship: music_wrecked_ship
  music_player_play_music_wrecked_ship_generator: music_wrecked_ship_generator
  music_player_stop_music_boss:
    music_boss:
      action: stop
      fade_out: 1s
  music_player_stop_music_brinstar:
    music_brinstar:
      action: stop
      fade_out: 1s
  music_player_stop_music_brinstar_calm:
    music_brinstar_calm:
      action: stop
      fade_out: 1s
  music_player_stop_music_brinstar_side_entrance:
    music_brinstar_side_entrance:
      action: stop
      fade_out: 1s
  music_player_stop_music_crateria:
    music_crateria:
      action: stop
      fade_out: 1s
  music_player_stop_music_maridia:
    music_maridia:
      action: stop
      fade_out: 1s
  music_player_stop_music_maridia_intro:
    music_maridia_intro:
      action: stop
      fade_out: 1s
  music_player_stop_music_maridia_snow:
    music_maridia_snow:
      action: stop
      fade_out: 1s
  music_player_stop_music_metal_item_room:
    music_metal_item_room:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair:
    music_norfair:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair_calm:
    music_norfair_calm:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair_deep:
    music_norfair_deep:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair_deep_intro:
    music_norfair_deep_intro:
      action: stop
      fade_out: 1s
  music_player_stop_music_wrecked_ship:
    music_wrecked_ship:
      action: stop
      fade_out: 1s
  music_player_stop_music_wrecked_ship_generator:
    music_wrecked_ship_generator:
      action: stop
      fade_out: 1s

  bao_play_main:
    music_bao_main:
      action: play
      fade_in: 2s
    music_bao_multiball:
      action: stop
    music_bao_reactor:
      action: stop
    music_bao_critical:
      action: stop
  bao_play_reactor:
    music_bao_reactor:
      action: play
      fade_in: 2s
    music_bao_multiball:
      action: stop
    music_bao_main:
      action: stop
    music_bao_critical:
      action: stop
  bao_play_critical:
    music_bao_critical:
      action: play
    music_bao_main:
      action: stop
    music_bao_reactor:
      action: stop
    music_bao_multiball:
      action: stop
  bao_play_multiball:
    music_bao_multiball:
      action: play
    music_bao_main:
      action: stop
    music_bao_reactor:
      action: stop
    music_bao_critical:
      action: stop

  stop_all_music:
    music_crateria:
      action: stop
      fade_out: 3s
    music_boss:
      action: stop
      fade_out: 3s
    music_brinstar:
      action: stop
      fade_out: 3s
    music_brinstar_calm:
      action: stop
      fade_out: 3s
    music_brinstar_side_entrance:
      action: stop
      fade_out: 3s
    music_norfair:
      action: stop
      fade_out: 3s
    music_norfair_calm:
      action: stop
      fade_out: 3s
    music_norfair_deep_intro:
      action: stop
      fade_out: 3s
    music_norfair_deep:
      action: stop
      fade_out: 3s
    music_maridia:
      action: stop
      fade_out: 3s
    music_wrecked_ship:
      action: stop
      fade_out: 3s
    music_wrecked_ship_generator:
      action: stop
      fade_out: 3s
    music_maridia_intro:
      action: stop
      fade_out: 3s
    music_maridia_snow:
      action: stop
      fade_out: 3s
    music_metal_item_room:
      action: stop
      fade_out: 3s
    music_bao_main:
      action: stop
      fade_out: 3s
    music_bao_multiball:
      action: stop
      fade_out: 3s
    music_bao_reactor:
      action: stop
      fade_out: 3s
    music_bao_critical:
      action: stop
      fade_out: 3s

