#config_version=5

sound_player:
  # play music
  music_player_play_music_bao_critical: music_bao_critical
  music_player_play_music_bao_main:
    music_bao_main:
      action: play
      fade_in: 2s
  music_player_play_music_bao_multiball: music_bao_multiball
  music_player_play_music_bao_reactor:
    music_bao_reactor:
      action: play
      fade_in: 2s
  music_player_play_music_boss: music_boss
  music_player_play_music_brinstar: music_brinstar
  music_player_play_music_brinstar_calm: music_brinstar_calm
  music_player_play_music_brinstar_side_entrance: music_brinstar_side_entrance
  music_player_play_music_crateria: music_crateria
  music_player_play_music_crateria_central: music_crateria_central
  music_player_play_music_crateria_edge: music_crateria_edge
  music_player_play_music_crateria_quiet: music_crateria_quiet
  music_player_play_music_maridia: music_maridia
  music_player_play_music_maridia_intro: music_maridia_intro
  music_player_play_music_maridia_snow: music_maridia_snow
  music_player_play_music_metal_item_room: music_metal_item_room
  music_player_play_music_multiball: music_multiball
  music_player_play_music_norfair: music_norfair
  music_player_play_music_norfair_calm: music_norfair_calm
  music_player_play_music_norfair_deep: music_norfair_deep
  music_player_play_music_norfair_deep_intro: music_norfair_deep_intro
  music_player_play_music_wrecked_ship: music_wrecked_ship
  music_player_play_music_wrecked_ship_calm: music_wrecked_ship_calm
  music_player_play_music_wrecked_ship_generator: music_wrecked_ship_generator

  # stop music
  music_player_stop_music_bao_critical:
    music_bao_critical:
      action: stop
      fade_out: 1s
  music_player_stop_music_bao_main:
    music_bao_main:
      action: stop
      fade_out: 1s
  music_player_stop_music_bao_multiball:
    music_bao_multiball:
      action: stop
      fade_out: 1s
  music_player_stop_music_bao_reactor:
    music_bao_reactor:
      action: stop
      fade_out: 1s
  music_player_stop_music_boss:
    music_boss:
      action: stop
      fade_out: 1s
  music_player_stop_music_brinstar:
    music_brinstar:
      action: stop
      fade_out: 1s
  music_player_stop_music_brinstar_calm:
    music_brinstar_calm:
      action: stop
      fade_out: 1s
  music_player_stop_music_brinstar_side_entrance:
    music_brinstar_side_entrance:
      action: stop
      fade_out: 1s
  music_player_stop_music_crateria:
    music_crateria:
      action: stop
      fade_out: 1s
  music_player_stop_music_crateria_central:
    music_crateria_central:
      action: stop
      fade_out: 1s
  music_player_stop_music_crateria_edge:
    music_crateria_edge:
      action: stop
      fade_out: 1s
  music_player_stop_music_crateria_quiet:
    music_crateria_quiet:
      action: stop
      fade_out: 1s
  music_player_stop_music_maridia:
    music_maridia:
      action: stop
      fade_out: 1s
  music_player_stop_music_maridia_intro:
    music_maridia_intro:
      action: stop
      fade_out: 1s
  music_player_stop_music_maridia_snow:
    music_maridia_snow:
      action: stop
      fade_out: 1s
  music_player_stop_music_metal_item_room:
    music_metal_item_room:
      action: stop
      fade_out: 1s
  music_player_stop_music_multiball:
    music_multiball:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair:
    music_norfair:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair_calm:
    music_norfair_calm:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair_deep:
    music_norfair_deep:
      action: stop
      fade_out: 1s
  music_player_stop_music_norfair_deep_intro:
    music_norfair_deep_intro:
      action: stop
      fade_out: 1s
  music_player_stop_music_wrecked_ship:
    music_wrecked_ship:
      action: stop
      fade_out: 1s
  music_player_stop_music_wrecked_ship_calm:
    music_wrecked_ship_calm:
      action: stop
      fade_out: 1s
  music_player_stop_music_wrecked_ship_generator:
    music_wrecked_ship_generator:
      action: stop
      fade_out: 1s

  # stop all with long fade out
  stop_all_music:
    music_crateria:
      action: stop
      fade_out: 3s
    music_crateria_central:
      action: stop
      fade_out: 3s
    music_crateria_edge:
      action: stop
      fade_out: 3s
    music_crateria_quiet:
      action: stop
      fade_out: 3s
    music_boss:
      action: stop
      fade_out: 3s
    music_brinstar:
      action: stop
      fade_out: 3s
    music_brinstar_calm:
      action: stop
      fade_out: 3s
    music_brinstar_side_entrance:
      action: stop
      fade_out: 3s
    music_norfair:
      action: stop
      fade_out: 3s
    music_norfair_calm:
      action: stop
      fade_out: 3s
    music_norfair_deep_intro:
      action: stop
      fade_out: 3s
    music_norfair_deep:
      action: stop
      fade_out: 3s
    music_maridia:
      action: stop
      fade_out: 3s
    music_multiball:
      action: stop
      fade_out: 3s
    music_wrecked_ship:
      action: stop
      fade_out: 3s
    music_wrecked_ship_calm:
      action: stop
      fade_out: 3s
    music_wrecked_ship_generator:
      action: stop
      fade_out: 3s
    music_maridia_intro:
      action: stop
      fade_out: 3s
    music_maridia_snow:
      action: stop
      fade_out: 3s
    music_metal_item_room:
      action: stop
      fade_out: 3s
    music_bao_main:
      action: stop
      fade_out: 3s
    music_bao_multiball:
      action: stop
      fade_out: 3s
    music_bao_reactor:
      action: stop
      fade_out: 3s
    music_bao_critical:
      action: stop
      fade_out: 3s

