#config_version=5
mode:
    start_events: room_2a_sink_into_sand, room_2e_continue, room_2e_enter
    stop_events: game_ending, ball_ending, room_2d_enter, room_2f_enter
    priority: 300

shots:
  room_2e_exit_west_closed_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: room_2e_enable_west_missile_door
    disable_events: room_2e_disable_west_missile_door, room_2e_open_west_door
    reset_events: room_2e_disable_west_missile_door, room_2e_open_west_door
    show_tokens:
      led: led_enter_left_orbit
      color: door_red
  room_2e_exit_east_closed_shot:
    hit_events: rollover_shot_hit
    profile: exit_door
    enable_events: room_2e_enable_east_missile_door
    disable_events: room_2e_disable_east_missile_door, room_2e_open_east_door
    reset_events: room_2e_disable_east_missile_door, room_2e_open_east_door
    show_tokens:
      led: led_rollover
      color: door_red
  room_2e_exit_west_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: room_2e_enable_west_door
    disable_events: room_2e_disable_west_door
    reset_events: room_2e_disable_west_door
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_2e_exit_east_shot:
    hit_events: rollover_shot_hit
    profile: exit_door
    enable_events: room_2e_enable_east_door
    disable_events: room_2e_disable_east_door
    reset_events: room_2e_disable_east_door
    show_tokens:
      led: led_rollover
      color: door_blue

slides:
  room_2e_backglass_slide:
    widgets:
      - type: image
        image: room_2e_sandy_cavern_backglass
    transition:
      type: push
      duration: 1s
      direction: down
    transition_out: fade
#  room_2a_splash_slide:
#    widgets:
#      - type: image
#        image: room_2a_splash

slide_player:
  mode_room_2e_sandy_cavern_started:
    room_2e_backglass_slide:
      target: backglass
#    room_2a_splash_slide:
#      target: dmd
#      expire: 1s
#      priority: 500

show_player:
  mode_room_2e_sandy_cavern_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '806000'
        color2: 'a78600'

event_player:
  mode_room_2e_sandy_cavern_started:
    cmd_backbox_show:
      show_type: pour
      count: 3
      min_length: 4
      max_length: 12
      color: "200C00"
  mode_room_2e_sandy_cavern_started{current_player.door_2d_2e == 0}: room_2e_enable_west_missile_door, room_2e_disable_west_door
  mode_room_2e_sandy_cavern_started{current_player.door_2e_2f == 0}: room_2e_enable_east_missile_door, room_2e_disable_east_door
  mode_room_2e_sandy_cavern_started{current_player.door_2d_2e == 1}: room_2e_enable_west_door, room_2e_disable_west_missile_door
  mode_room_2e_sandy_cavern_started{current_player.door_2e_2f == 1}: room_2e_enable_east_door, room_2e_disable_east_missile_door
  room_2e_exit_west_closed_shot_hit{current_player.missiles > 0}: room_2e_open_west_door
  room_2e_exit_east_closed_shot_hit{current_player.missiles > 0}: room_2e_open_east_door
  room_2e_open_west_door: room_2e_exit_west_shot_hit
  room_2e_open_east_door: room_2e_exit_east_shot_hit
  room_2e_exit_west_shot_hit: room_2d_enter
  room_2e_exit_east_shot_hit: room_2f_enter
  room_2e_enter: drop_targets_continue

variable_player:
  mode_room_2e_sandy_cavern_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2e
      action: set
  room_2e_open_west_door:
    missiles: -1
    door_2d_2e:
      int: 1
      action: set
  room_2e_open_east_door:
    missiles: -1
    door_2e_2f:
      int: 1
      action: set


