#config_version=5
mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 420


sequences:
   upper_lanes_progress_sequence:
      events:
         - upper_lanes_stage_1_complete
         - upper_lanes_stage_2_complete
      events_when_complete: upper_lanes_start_multiball
      persist_state: True
      reset_on_complete: True
      disable_on_complete: False


shot_profiles:
  upper_lanes:
    states:
      - name: unlit
        show: off
      - name: stage_1
        show: blink_light
        sync_ms: 1000
      - name: stage_2
        show: blink_light
        speed: 2
        sync_ms: 500
      - name: lit
        show: led_color
  upper_lanes_select:
    advance_on_hit: False
    states:
      - name: unselected
        show: led_color
      - name: selected
        show: blink_light
        speed: 4


shots:
  upper_lane_left_shot:
    switch: s_top_lane_1
    profile: upper_lanes
    show_tokens:
      led: led_upper_playfield_1
      color: '9f2e3d'
  upper_lane_middle_shot:
    switch: s_top_lane_2
    profile: upper_lanes
    show_tokens:
      led: led_upper_playfield_2
      color: '979f2e'
  upper_lane_right_shot:
    switch: s_top_lane_3
    profile: upper_lanes
    show_tokens:
      led: led_upper_playfield_3
      color: '2e9f61'
  upper_lane_select_left_shot:
    switch: s_top_lane_1
    advance_events: upper_lanes_select_1
    reset_events: mode_upper_lanes_started, upper_lanes_select_2, upper_lanes_select_3
    profile: upper_lanes_select
    show_tokens:
      led: led_upper_playfield_1
      color: '9f2e3d'
  upper_lane_select_middle_shot:
    switch: s_top_lane_2
    advance_events: upper_lanes_select_2
    reset_events: mode_upper_lanes_started, upper_lanes_select_1, upper_lanes_select_3
    profile: upper_lanes_select
    show_tokens:
      led: led_upper_playfield_2
      color: '979f2e'
  upper_lane_select_right_shot:
    switch: s_top_lane_3
    advance_events: upper_lanes_select_3
    reset_events: mode_upper_lanes_started, upper_lanes_select_2, upper_lanes_select_1
    profile: upper_lanes_select
    show_tokens:
      led: led_upper_playfield_3
      color: '2e9f61'

shot_groups:
  upper_lanes_shot_group:
    shots: upper_lane_left_shot, upper_lane_middle_shot, upper_lane_right_shot
    enable_events: upper_lanes_stage_1
    disable_events: mode_upper_lanes_started, mode_upper_lanes_ending, upper_lanes_stage_1_complete
    reset_events: upper_lanes_stage_1_complete
  upper_lanes_collect_shot_group:
    shots: upper_lane_select_left_shot, upper_lane_select_middle_shot, upper_lane_select_right_shot
    enable_events: upper_lanes_stage_1_complete, upper_lanes_stage_2
    disable_events: mode_upper_lanes_started, mode_upper_lanes_ending, upper_lanes_stage_2_complete
    reset_events: upper_lanes_stage_2_complete

sounds:
  upper_lanes_spider_rail:
    file: upper_lanes_spider_rail.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  upper_lanes_bridge:
    file: upper_lanes_bridge.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

sound_player:
  upper_lane_left_shot_hit: upper_lanes_spider_rail
  upper_lanes_play_bridge_sound: upper_lanes_bridge

show_player:
  upper_lanes_stage_1_complete:
    upper_lanes_complete:
      loops: 0
      priority: 10
  upper_lane_left_shot_hit:
    upper_lanes_left_score:
      loops: 0
  upper_lane_middle_shot_hit:
    upper_lanes_middle_score:
      loops: 0
  upper_lane_right_shot_hit:
    upper_lanes_right_score:
      loops: 0


event_player:
  mode_upper_lanes_started{device.sequences.upper_lanes_progress_sequence.value == 0}: upper_lanes_stage_1
  mode_upper_lanes_started{device.sequences.upper_lanes_progress_sequence.value == 1}: upper_lanes_stage_2
  upper_lanes_shot_group_lit_complete: upper_lanes_stage_1_complete
  upper_lanes_stage_1_complete: upper_lanes_stage_2
  upper_lane_select_left_shot_hit: upper_lanes_select_1
  upper_lane_select_middle_shot_hit: upper_lanes_select_2
  upper_lane_select_right_shot_hit: upper_lanes_select_3
  upper_lane_middle_shot_hit{current_player.power_bombs < 1}: upper_lanes_play_bridge_sound

variable_player:
  upper_lane_left_shot_hit:
    lanes: 1
    score:
      int: (10000 + (1000 * current_player.lanes) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
    room_special_score:
      int: (10000 + (1000 * current_player.lanes) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
      action: set
  upper_lane_middle_shot_hit:
    lanes: 1
    score:
      int: (10000 + (1000 * current_player.lanes) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
    room_special_score:
      int: (10000 + (1000 * current_player.lanes) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
      action: set
  upper_lane_right_shot_hit:
    lanes: 1
    score:
      int: (10000 + (1000 * current_player.lanes) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
    room_special_score:
      int: (10000 + (1000 * current_player.lanes) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
      action: set
  upper_lanes_stage_1_complete:
    score:
      int: (100000 + (10000 * current_player.lanes) + (current_player.area_bonus_ne * 42690)) * current_player.multiplier
    room_special_score:
      int: (100000 + (10000 * current_player.lanes) + (current_player.area_bonus_ne * 42690)) * current_player.multiplier
      action: set
