#config_version=5

mode:
  start_events: room_2p_continue, room_2p_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2o_enter, room_2p_exit
  priority: 300

shots:
  room_2p_exit_west_shot:
    switch: s_ramp_enter
    profile: exit_door_optimum
    enable_events: mode_room_2p_east_hot_springs_started
    disable_events: room_2p_exit_west_shot_hit
    reset_events: room_2p_exit_west_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue

slides:
  room_2p_east_hot_springs_backglass_slide:
    widgets:
      - type: image
        image: room_2p_east_hot_springs_backglass
    transition: fade
    transition_out: fade
  room_2p_east_hot_springs_splash_slide:
    widgets:
      - type: image
        image: room_2p_east_hot_springs_splash

slide_player:
  mode_room_2p_east_hot_springs_started:
    room_2p_east_hot_springs_backglass_slide:
      target: backglass
    room_2p_east_hot_springs_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2p_east_hot_springs_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_2p_east_hot_springs_status_report:
      loops: 0
  flipper_cradle_release:
    room_2p_east_hot_springs_status_report:
      action: stop

event_player:
  mode_room_2p_east_hot_springs_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2p'
      visit: True
  room_2p_exit_west_shot_hit.1: drop_targets_save
  room_2p_exit_west_shot_hit.2: room_2o_enter

variable_player:
  mode_room_2p_east_hot_springs_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2p
      action: set
