#config_version=5

# https://commons.wikimedia.org/wiki/File:2019-07-16_Plasma_ball.jpg

mode:
  code: room_1h_teleporters.Room1hTeleporters
  start_events: room_1h_continue, room_1h_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1i_enter, room_1h_exit
  priority: 300


timers:
  room_1h_begin_teleport_countdown:
    start_value: 1
    end_value: 3
    tick_interval: 1.0s
    control_events:
      - event: room_1h_start_countdown
        action: restart
  room_1h_teleport:
    start_value: 1
    end_value: 2
    tick_interval: 1.0s
    control_events:
      - event: room_1h_ball_locked_for_final_shot
        action: restart


sequences:
  room_1h_teleporter_multi_sequence:
    events:
      - room_1h_light_teleporter_shot_hit
      - room_1h_light_teleporter_shot_hit
    events_when_complete: room_1h_teleporter_lock
    enable_events: room_1h_enable_teleporter_charge
    disable_events: mode_room_1h_teleporters_started, logicblock_room_1h_teleporter_multi_sequence_complete
    restart_events: mode_room_1h_teleporters_started, logicblock_room_1h_teleporter_multi_sequence_complete


shot_profiles:
  room_1h_target:
    states:
      - name: lit
        show: single_rainbow
        speed: 45

shots:
  room_1h_exit_east_shot:
    switches: s_ramp_enter
    profile: exit_door_optimum
    enable_events: mode_room_1h_teleporters_started
    disable_events: room_1h_exit_east_shot_hit
    reset_events: room_1h_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1h_light_teleporter_shot:
    switch: s_captive_ball
    profile: room_1h_target
    enable_events: mode_room_1h_teleporters_started
    disable_events: room_1h_start_teleporter_lock
    show_tokens:
      led: led_captive_ball
  room_1h_load_teleporter_shot:
    switch: s_drop_target_3
    profile: room_1h_target
    enable_events: room_1h_start_teleporter_lock
    disable_events: mode_room_1h_teleporters_started, room_1h_ball_locked_for_final_shot
    show_tokens:
      led: led_drop_3
  room_1h_lock_teleporter_shot:
    switch: s_behind_drop_2
    enable_events: room_1h_start_teleporter_lock
    disable_events: mode_room_1h_teleporters_started, room_1h_ball_locked_for_final_shot


slides:
  room_1h_teleporters_backglass_slide:
    widgets:
      - type: image
        image: room_1h_teleporters_backglass
    transition: fade
    transition_out: fade
  room_1h_teleporters_backglass_powered_slide:
    widgets:
      - type: image
        image: room_1h_teleporters_backglass_powered
    transition: fade
    transition_out: fade
  room_1h_teleporters_splash_slide:
    widgets:
      - type: image
        image: room_1h_teleporters_splash

slide_player:
  mode_room_1h_teleporters_started_no_charge:
    room_1h_teleporters_backglass_slide:
      target: backglass
  mode_room_1h_teleporters_started_charge:
    room_1h_teleporters_backglass_powered_slide:
      target: backglass
  mode_room_1h_teleporters_started:
    room_1h_teleporters_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1h_teleporters_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1h_teleporters_status_report:
      loops: 0
  flipper_cradle_release:
    room_1h_teleporters_status_report:
      action: stop
  room_1h_ball_locked_for_final_shot:
    room_1h_teleporters_teleport:
      speed: 40
      loops: 6

event_player:
  mode_room_1h_teleporters_started:
    drop_targets_continue:
    chozo_multiball_disable:
    cmd_map_position:
      room: '1h'
      visit: True
  mode_room_1h_teleporters_started_no_charge:
    cmd_backbox_show:
      show_type: plasma
      color1: "202000"
      color2: "181800"
      color3: "101000"
      color4: "080800"
      color5: "040400"
      color6: "001000"
      color7: "000800"
      color8: "001010"
      decay_r: 2.1
      decay_g: 2.1
      decay_b: 1.4
  mode_room_1h_teleporters_started_charge:
    cmd_backbox_show:
      show_type: plasma
      color1: "800000"
      color2: "282800"
      color3: "202000"
      color4: "181800"
      color5: "101000"
      color6: "080800"
      color7: "000800"
      color8: "001010"
      decay_r: 1.4
      decay_g: 1.8
      decay_b: 1.8
  mode_room_1h_teleporters_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1h_teleporters_started_no_charge, room_1h_enable_teleporter_charge
  mode_room_1h_teleporters_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1h_teleporters_started_charge
  room_1h_light_teleporter_shot_hit{current_player.wrecked_ship_powered_up == 1}: room_1h_start_teleporter_lock
  room_1h_teleporter_lock: room_1h_start_teleporter_lock
  room_1h_exit_east_shot_hit.1: drop_targets_save
  room_1h_exit_east_shot_hit.2: room_1i_enter
  # This is slow
  room_1h_load_teleporter_shot_hit: cmd_drop_three_up, cmd_drop_two_up
  room_1h_lock_teleporter_shot_hit: cmd_drop_two_up, room_1h_start_countdown
  # -- <O-
  timer_room_1h_begin_teleport_countdown_complete: cmd_drop_three_up, cmd_drop_two_down
  timer_room_1h_begin_teleport_countdown_complete{device.switches.s_behind_drop_2.state}: room_1h_ball_locked_for_final_shot
  timer_room_1h_begin_teleport_countdown_complete{not device.switches.s_behind_drop_2.state}: cmd_drop_three_up, cmd_drop_two_down
  timer_room_1h_teleport_complete: room_1h_should_teleport


variable_player:
  mode_room_1h_teleporters_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1h
      action: set
