#config_version=5

mode:
  start_events: room_1h_continue, room_1h_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1i_enter
  priority: 300

shots:
  room_1h_exit_east_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_1h_teleporters_started
    disable_events: room_1h_exit_east_shot_hit
    reset_events: room_1h_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue

slides:
  room_1h_teleporters_backglass_slide:
    widgets:
      - type: image
        image: room_1h_teleporters_backglass
    transition: fade
    transition_out: fade
  room_1h_teleporters_backglass_powered_slide:
    widgets:
      - type: image
        image: room_1h_teleporters_backglass_powered
    transition: fade
    transition_out: fade
  room_1h_teleporters_splash_slide:
    widgets:
      - type: image
        image: room_1h_teleporters_splash

slide_player:
  mode_room_1h_teleporters_started_no_charge:
    room_1h_teleporters_backglass_slide:
      target: backglass
  mode_room_1h_teleporters_started_charge:
    room_1h_teleporters_backglass_powered_slide:
      target: backglass
  mode_room_1h_teleporters_started:
    room_1h_teleporters_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1h_teleporters_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1h_teleporters_status_report:
      loops: 0
  flipper_cradle_release:
    room_1h_teleporters_status_report:
      action: stop

event_player:
  mode_room_1h_teleporters_started:
    drop_targets_continue:
    cmd_map_position:
      room: '1h'
      visit: True
  mode_room_1h_teleporters_started_no_charge:
    cmd_backbox_show:
      show_type: plasma
      color1: "202000"
      color2: "181800"
      color3: "101000"
      color4: "080800"
      color5: "040400"
      color6: "001000"
      color7: "000800"
      color8: "001010"
      decay_r: 2.1
      decay_g: 2.1
      decay_b: 1.4
  mode_room_1h_teleporters_started_charge:
    cmd_backbox_show:
      show_type: fire
  mode_room_1h_teleporters_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1h_teleporters_started_no_charge
  mode_room_1h_teleporters_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1h_teleporters_started_charge
  room_1h_exit_east_shot_hit.1: drop_targets_save
  room_1h_exit_east_shot_hit.2: room_1i_enter

variable_player:
  mode_room_1h_teleporters_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1h
      action: set
