#config_version=5

mode:
  start_events: mode_base_starting
  priority: 100

shots:
  ramp_shot:
    switch: s_ramp_enter

show_player:
  ramp_shot_hit:
    blink_3_lights:
      loops: 0
      priority: 500
      speed: 3
      show_tokens:
        led_1: gi_strip_1
        led_2: gi_strip_2
        led_3: gi_strip_3
        color_1: 'FF0000'
        color_2: '00FF00'
    blink_2_lights:
      loops: 0
      priority: 500
      speed: 2
      show_tokens:
        led_1: gi_back_left
        led_2: led_enter_ramp
        color_1: '00FF00'
        color_2: '0000FF'

sounds:
  ramp_sound_1:
    file: ramp_sound_1.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

sound_player:
  ramp_shot_hit: ramp_sound_1

variable_player:
  ramp_shot_hit:
    ramps: 1
    score:
      int: ((current_player.ramps * 1250) + (current_player.area_bonus_nw * 1000)) * current_player.multiplier

