#config_version=5

# https://commons.wikimedia.org/wiki/File:Orange_Spring_Mound_at_Mammoth_Hot_Springs.jpg

mode:
  start_events: room_2l_continue, room_2l_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2m_enter, room_2p_enter, room_2l_exit, hot_spring_room_exit
  priority: 300

shot_profiles:
  room_2l_scoop:
    states:
      - name: lit
        show: blink_light
        speed: 2
        loops: -1
        sync_ms: 1000
  room_2l_increase:
    states:
      - name: lit
        show: blink_light
        loops: -1
        sync_ms: 1000

shots:
  room_2l_exit_east_shot:
    switches: s_ramp_enter
    profile: exit_door_optimum
    enable_events: metroid_open_doors
    disable_events: room_2l_exit_east_shot_hit, metroid_close_doors
    reset_events: room_2l_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_2l_scoop_shot:
    switch: s_scoop
    profile: room_2l_scoop
    enable_events: room_2l_enable_scoop
    disable_events: mode_room_2l_west_hot_springs_started
    show_tokens:
      led: led_enter_scoop
      color: 'FFFF00'
  room_2l_increase_1_shot:
    switch: s_left_passage
    profile: room_2l_increase
    enable_events: room_2l_enable_shots
    disable_events: mode_room_2l_west_hot_springs_started
    show_tokens:
      led: led_enter_secret_passage
      color: 'A040FF'
  room_2l_increase_2_shot:
    hit_events: left_orbit_hit
    profile: room_2l_increase
    enable_events: room_2l_enable_shots
    disable_events: mode_room_2l_west_hot_springs_started
    show_tokens:
      led: led_enter_left_orbit
      color: 'C000FF'
  room_2l_increase_3_shot:
    switch: s_side_ramp_made
    profile: room_2l_increase
    enable_events: room_2l_enable_shots
    disable_events: mode_room_2l_west_hot_springs_started
    show_tokens:
      led: led_enter_side_ramp
      color: 'FF8ADD'
  room_2l_increase_4_shot:
    hit_events: right_orbit_hit
    profile: room_2l_increase
    enable_events: room_2l_enable_shots
    disable_events: mode_room_2l_west_hot_springs_started
    show_tokens:
      led: led_enter_right_orbit
      color: '6900FF'

slides:
  room_2l_west_hot_springs_backglass_slide:
    widgets:
      - type: image
        image: room_2l_west_hot_springs_backglass
    transition: fade
    transition_out: fade
  room_2l_west_hot_springs_splash_slide:
    widgets:
      - type: image
        image: room_2l_west_hot_springs_splash

slide_player:
  mode_room_2l_west_hot_springs_started:
    room_2l_west_hot_springs_backglass_slide:
      target: backglass
    room_2l_west_hot_springs_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2l_west_hot_springs_started:
    room_2l_gi:
      loops: -1
      speed: 60
    light_bar_solid:
      loops: -1
      show_tokens:
        color: light_bar_basic
  show_mode_status_report:
    room_2l_west_hot_springs_status_report:
      loops: 0
  flipper_cradle_release:
    room_2l_west_hot_springs_status_report:
      action: stop
  room_2l_increase_1_shot_hit:
    special_score_yellow:
      loops: 0
  room_2l_increase_2_shot_hit:
    special_score_yellow:
      loops: 0
  room_2l_increase_3_shot_hit:
    special_score_yellow:
      loops: 0
  room_2l_increase_4_shot_hit:
    special_score_yellow:
      loops: 0

event_player:
  mode_room_2l_west_hot_springs_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2l'
      visit: True
    cmd_play_map_music:
      music: music_norfair_deep
    metroid_open_doors:
    room_2l_enable_shots:
  room_2l_increase_1_shot_hit: room_2l_enable_scoop
  room_2l_increase_2_shot_hit: room_2l_enable_scoop
  room_2l_increase_3_shot_hit: room_2l_enable_scoop
  room_2l_increase_4_shot_hit: room_2l_enable_scoop
  room_2l_scoop_shot_hit:
    room_2p_enter:
    cmd_map_complete:
      room: '2l'
  room_2l_exit_east_shot_hit.1: drop_targets_save
  room_2l_exit_east_shot_hit.2: room_2m_enter

variable_player:
  mode_room_2l_west_hot_springs_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2l
      action: set
  room_2l_increase_1_shot_hit:
    score: (100000 + (current_player.area_bonus_w * 50000)) * current_player.multiplier
    room_special_score:
      int: (100000 + (current_player.area_bonus_w * 50000)) * current_player.multiplier
      action: set
    hot_springs_jackpot_value: 25000
  room_2l_increase_2_shot_hit:
    score: (100000 + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
    room_special_score:
      int: (100000 + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
      action: set
    hot_springs_jackpot_value: 25000
  room_2l_increase_3_shot_hit:
    score: (100000 + (current_player.area_bonus_ne * 50000)) * current_player.multiplier
    room_special_score:
      int: (100000 + (current_player.area_bonus_ne * 50000)) * current_player.multiplier
      action: set
    hot_springs_jackpot_value: 25000
  room_2l_increase_4_shot_hit:
    score: (100000 + (current_player.area_bonus_ne * 50000)) * current_player.multiplier
    room_special_score:
      int: (100000 + (current_player.area_bonus_ne * 50000)) * current_player.multiplier
      action: set
    hot_springs_jackpot_value: 25000
