#config_version=5

# https://commons.wikimedia.org/wiki/File:Orange_Spring_Mound_at_Mammoth_Hot_Springs.jpg

mode:
  start_events: room_2l_continue, room_2l_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2m_enter
  priority: 300

shots:
  room_2l_exit_east_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_2l_west_hot_springs_started
    disable_events: room_2l_exit_east_shot_hit
    reset_events: room_2l_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue

slides:
  room_2l_west_hot_springs_backglass_slide:
    widgets:
      - type: image
        image: room_2l_west_hot_springs_backglass
    transition: fade
    transition_out: fade
  room_2l_west_hot_springs_splash_slide:
    widgets:
      - type: image
        image: room_2l_west_hot_springs_splash

slide_player:
  mode_room_2l_west_hot_springs_started:
    room_2l_west_hot_springs_backglass_slide:
      target: backglass
    room_2l_west_hot_springs_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2l_west_hot_springs_started:
    room_2l_gi:
      loops: -1
  show_mode_status_report:
    room_2l_west_hot_springs_status_report:
      loops: 0
  flipper_cradle_release:
    room_2l_west_hot_springs_status_report:
      action: stop

event_player:
  mode_room_2l_west_hot_springs_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2l'
      visit: True
  room_2l_exit_east_shot_hit.1: drop_targets_save
  room_2l_exit_east_shot_hit.2: room_2m_enter

variable_player:
  mode_room_2l_west_hot_springs_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2l
      action: set
