#config_version=5
mode:
  code: select_landing_site.SelectLandingSite
  start_events: metroid_base_started
  stop_events: ball_ended, metroid_base_ended, select_landing_site_item_selected
  priority: 500
  game_mode: false

mode_settings:
  selectable_items: crateria, brinstar, wrecked_ship, maridia, norfair
  select_item_events: s_shooter_lane_inactive
  next_item_events: s_left_flipper_active
  previous_item_events: s_right_flipper_active

queue_relay_player:
  player_turn_starting:
    post: landing_site_selection_started
    wait_for: select_landing_site_item_selected

slide_player:
  select_landing_site_continue_highlighted:
    select_landing_site_continue_slide:
      target: dmd
    select_landing_site_continue_backglass_slide:
      target: backglass
  select_landing_site_crateria_highlighted:
    select_landing_site_crateria_slide:
      target: dmd
    select_landing_site_crateria_backglass_slide:
      target: backglass
  select_landing_site_brinstar_highlighted:
    select_landing_site_brinstar_slide:
      target: dmd
    select_landing_site_brinstar_backglass_slide:
      target: backglass
  select_landing_site_wrecked_ship_highlighted:
    select_landing_site_wrecked_ship_slide:
      target: dmd
    select_landing_site_wrecked_ship_backglass_slide:
      target: backglass
  select_landing_site_maridia_highlighted:
    select_landing_site_maridia_slide:
      target: dmd
    select_landing_site_maridia_backglass_slide:
      target: backglass
  select_landing_site_norfair_highlighted:
    select_landing_site_norfair_slide:
      target: dmd
    select_landing_site_norfair_backglass_slide:
      target: backglass

slides:
  select_landing_site_continue_slide:
    widgets:
    - type: image
      image: landing_site_arrow_left
      anchor_x: left
      x: 0
    - type: image
      image: landing_site_arrow_right
      anchor_x: right
      x: 128
    - type: text
      text: Player (player|number)
      color: "FF6030"
      y: 3
      style: dmd_small
    - type: image
      image: landing_site_continue
      y: 18
  select_landing_site_continue_backglass_slide:
    widgets:
    - type: image
      image: landing_site_continue_backglass
  select_landing_site_crateria_slide:
    widgets:
    - type: image
      image: landing_site_arrow_left
      anchor_x: left
      x: 0
    - type: image
      image: landing_site_arrow_right
      anchor_x: right
      x: 128
    - type: image
      image: landing_site_crateria
  select_landing_site_crateria_backglass_slide:
    widgets:
    - type: image
      image: landing_site_crateria_backglass
  select_landing_site_brinstar_slide:
    widgets:
    - type: image
      image: landing_site_arrow_left
      anchor_x: left
      x: 0
    - type: image
      image: landing_site_arrow_right
      anchor_x: right
      x: 128
    - type: image
      image: landing_site_brinstar
  select_landing_site_brinstar_backglass_slide:
    widgets:
    - type: image
      image: landing_site_brinstar_backglass
  select_landing_site_wrecked_ship_slide:
    widgets:
    - type: image
      image: landing_site_arrow_left
      anchor_x: left
      x: 0
    - type: image
      image: landing_site_arrow_right
      anchor_x: right
      x: 128
    - type: image
      image: landing_site_wrecked_ship
  select_landing_site_wrecked_ship_backglass_slide:
    widgets:
    - type: image
      image: landing_site_wrecked_ship_backglass
  select_landing_site_maridia_slide:
    widgets:
    - type: image
      image: landing_site_arrow_left
      anchor_x: left
      x: 0
    - type: image
      image: landing_site_arrow_right
      anchor_x: right
      x: 128
    - type: image
      image: landing_site_maridia
  select_landing_site_maridia_backglass_slide:
    widgets:
    - type: image
      image: landing_site_maridia_backglass
  select_landing_site_norfair_slide:
    widgets:
    - type: image
      image: landing_site_arrow_left
      anchor_x: left
      x: 0
    - type: image
      image: landing_site_arrow_right
      anchor_x: right
      x: 128
    - type: image
      image: landing_site_norfair
  select_landing_site_norfair_backglass_slide:
    widgets:
    - type: image
      image: landing_site_norfair_backglass

event_player:
  mode_select_landing_site_started:
    cmd_backbox_show:
      show_type: none
  select_landing_site_first_ball:
    cmd_map_position:
      room: '1b'
  select_landing_site_continue_highlighted:
    cmd_backbox_show:
      show_type: none
  select_landing_site_crateria_highlighted{current_player.room_1b_step_2 == 0}:
    cmd_backbox_show:
      show_type: drop
      min_delay: 1
      max_delay: 2
      background_color: "000004"
      drop_color: "101020"
  select_landing_site_crateria_highlighted{current_player.room_1b_step_2 != 0}:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 6
      max_cutoff: 8
      color1: "040404"
      color2: "04100C"
  select_landing_site_crateria_highlighted:
    cmd_map_position:
      room: '1b'
  select_landing_site_brinstar_highlighted:
    cmd_backbox_show:
      show_type: solid
      color: "200010"
    cmd_map_position:
      room: '1r'
  select_landing_site_wrecked_ship_highlighted:
    cmd_backbox_show:
      show_type: none
    cmd_map_position:
      room: '1l'
  select_landing_site_maridia_highlighted:
    cmd_backbox_show:
      show_type: pour
      count: 3
      min_length: 4
      max_length: 12
      color: "200C00"
    cmd_map_position:
      room: '2a'
  select_landing_site_norfair_highlighted:
    cmd_backbox_show:
      show_type: fire
    cmd_map_position:
      room: '2i'

show_player:
  mode_select_landing_site_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: "808040"
        color2: "C0C0C0"

sound_player:
# crateria, brinstar, wrecked_ship, maridia, norfair
# continue, crateria, brinstar, wrecked_ship, maridia, norfair
  select_landing_site_continue_highlighted:
    norfair:
      action: stop
    crateria:
      action: stop
    continue:
      action: play
  select_landing_site_crateria_highlighted:
    continue:
      action: stop
    brinstar:
      action: stop
    norfair:
      action: stop
    crateria:
      action: play
  select_landing_site_brinstar_highlighted:
    crateria:
      action: stop
    wrecked_ship:
      action: stop
    brinstar:
      action: play
  select_landing_site_norfair_highlighted:
    continue:
      action: stop
    maridia:
      action: stop
    crateria:
      action: stop
    norfair:
      action: play
  select_landing_site_maridia_highlighted:
    norfair:
      action: stop
    wrecked_ship:
      action: stop
    maridia:
      action: play
  select_landing_site_wrecked_ship_highlighted:
    maridia:
      action: stop
    brinstar:
      action: stop
    wrecked_ship:
      action: play
  mode_select_landing_site_started{machine.next_game_acapella == 0}:
    music_item_room:
      volume: 0.15
  mode_select_landing_site_started{current_player.ball == 1}: choose_landing_site
  select_landing_site_item_selected:
    music_item_room:
      action: stop
