#config_version=5
mode:
  code: select_landing_site.SelectLandingSite
  start_events: ball_starting
  stop_events: ball_ended, select_landing_site_item_selected
  priority: 500
  game_mode: false

mode_settings:
  selectable_items: crateria, brinstar, wrecked_ship, maridia, norfair
  select_item_events: s_shooter_lane_inactive
  next_item_events: s_left_flipper_active
  previous_item_events: s_right_flipper_active

queue_relay_player:
  player_turn_starting:
    post: landing_site_selection_started
    wait_for: select_landing_site_item_selected

slide_player:
  select_landing_site_continue_highlighted:
    select_landing_site_continue_slide:
      target: dmd
    select_landing_site_continue_backglass_slide:
      target: backglass
  select_landing_site_crateria_highlighted:
    select_landing_site_crateria_slide:
      target: dmd
    select_landing_site_crateria_backglass_slide:
      target: backglass
  select_landing_site_brinstar_highlighted:
    select_landing_site_brinstar_slide:
      target: dmd
    select_landing_site_brinstar_backglass_slide:
      target: backglass
  select_landing_site_wrecked_ship_highlighted:
    select_landing_site_wrecked_ship_slide:
      target: dmd
    select_landing_site_wrecked_ship_backglass_slide:
      target: backglass
  select_landing_site_maridia_highlighted:
    select_landing_site_maridia_slide:
      target: dmd
    select_landing_site_maridia_backglass_slide:
      target: backglass
  select_landing_site_norfair_highlighted:
    select_landing_site_norfair_slide:
      target: dmd
    select_landing_site_norfair_backglass_slide:
      target: backglass

slides:
  select_landing_site_continue_slide:
    widgets:
    - type: image
      image: landing_site_continue
      y: 12
    - type: text
      text: Player (player|number)
      color: "FF6030"
      y: 28
      style: dmd_med
  select_landing_site_continue_backglass_slide:
    widgets:
    - type: image
      image: landing_site_continue_backglass
  select_landing_site_crateria_slide:
    widgets:
    - type: image
      image: landing_site_crateria
  select_landing_site_crateria_backglass_slide:
    widgets:
    - type: image
      image: landing_site_crateria_backglass
  select_landing_site_brinstar_slide:
    widgets:
    - type: image
      image: landing_site_brinstar
  select_landing_site_brinstar_backglass_slide:
    widgets:
    - type: image
      image: landing_site_brinstar_backglass
  select_landing_site_wrecked_ship_slide:
    widgets:
    - type: image
      image: landing_site_wrecked_ship
  select_landing_site_wrecked_ship_backglass_slide:
    widgets:
    - type: image
      image: landing_site_wrecked_ship_backglass
  select_landing_site_maridia_slide:
    widgets:
    - type: image
      image: landing_site_maridia
  select_landing_site_maridia_backglass_slide:
    widgets:
    - type: image
      image: landing_site_maridia_backglass
  select_landing_site_norfair_slide:
    widgets:
    - type: image
      image: landing_site_norfair
  select_landing_site_norfair_backglass_slide:
    widgets:
    - type: image
      image: landing_site_norfair_backglass

#display_light_player:
#  mode_select_landing_site_started:
#    backglass:
#      lights: reflective
#      action: play
#  mode_select_landing_site_stopping:
#    backglass:
#      lights: reflective
#      action: stop

event_player:
  mode_select_landing_site_started:
    cmd_backbox_show:
      show_type: none
  select_landing_site_continue_highlighted:
    cmd_backbox_show:
      show_type: none
  select_landing_site_crateria_highlighted{current_player.room_1b_step_2 == 0}:
    cmd_backbox_show:
      show_type: drop
      min_delay: 1
      max_delay: 2
      background_color: "000004"
      drop_color: "101020"
  select_landing_site_crateria_highlighted{current_player.room_1b_step_2 != 0}:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 6
      max_cutoff: 8
      color1: "040404"
      color2: "04100C"
  select_landing_site_brinstar_highlighted:
    cmd_backbox_show:
      show_type: solid
      color: "200010"
  select_landing_site_wrecked_ship_highlighted:
    cmd_backbox_show:
      show_type: none
  select_landing_site_maridia_highlighted:
    cmd_backbox_show:
      show_type: pour
      count: 3
      min_length: 4
      max_length: 12
      color: "200C00"
  select_landing_site_norfair_highlighted:
    cmd_backbox_show:
      show_type: fire

sound_player:
  select_landing_site_continue_highlighted: continue
  select_landing_site_crateria_highlighted: crateria
  select_landing_site_brinstar_highlighted: brinstar
  select_landing_site_norfair_highlighted: norfair
  select_landing_site_maridia_highlighted: maridia
  select_landing_site_wrecked_ship_highlighted: wrecked_ship

