#config_version=5
mode:
    start_events: select_landing_site_crateria_selected, room_1b_continue, room_1b_enter
    stop_events: game_ending, ball_ending, metroid_base_ended, room_1b_success, room_1b_already_complete, room_1b_exit
    priority: 300

shots:
  room_1b_increase_value_shot:
    switch: s_shatz
    profile: room_1b_increase
    show_tokens:
      led: led_zero_suit
      color: '00ffff'

shot_profiles:
  room_1b_increase:
    states:
      - name: lit
        show: blink_light
        speed: 4

accruals:
  room_1b_complete_left_orbit:
    events: left_orbit_hit
    events_when_complete: room_1b_ship_left
    persist_state: true
    reset_on_complete: false
  room_1b_complete_right_orbit:
    events: right_orbit_hit
    events_when_complete: room_1b_ship_right
    persist_state: true
    reset_on_complete: false
  room_1b_complete_orbits:
    events:
      - room_1b_ship_left
      - room_1b_ship_right
    events_when_complete: room_1b_ship_navigated
    persist_state: true
    reset_on_complete: false

show_player:
  room_1b_ship_left:
    room_1b_go_left:
      loops: 0
    room_1b_left_orbit_blink:
      action: stop
  room_1b_ship_right:
    room_1b_go_right:
      loops: 0
    room_1b_right_orbit_blink:
      action: stop
  room_1b_ship_navigated:
    blink_light:
      key: room_1b_scoop_blink
      loops: -1
      show_tokens:
        led: led_enter_scoop
        color: ffff00
  room_1b_achieved:
    room_1b_scoop_blink:
      action: stop
  mode_room_1b_gunship_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '404080'
        color2: "808080"
  mode_room_1b_gunship_started{current_player.room_1b_step_1a == 0}:
    blink_light:
      key: room_1b_left_orbit_blink
      loops: -1
      show_tokens:
        led: led_enter_left_orbit
        color: 00ffff
  mode_room_1b_gunship_started{current_player.room_1b_step_1b == 0}:
    blink_light:
      key: room_1b_right_orbit_blink
      loops: -1
      show_tokens:
        led: led_enter_right_orbit
        color: 00ffff
  mode_room_1b_gunship_started{current_player.room_1b_step_1a == 1 and current_player.room_1b_step_1b == 1 and current_player.room_1b_step_2 == 0}:
    blink_light:
      key: room_1b_scoop_blink
      loops: -1
      show_tokens:
        led: led_enter_scoop
        color: ffff00
  show_mode_status_report:
    room_1b_status_report:
      loops: 0
  flipper_cradle_release:
    room_1b_status_report:
      action: stop
  room_1b_increase_value_shot_hit:
    single_fire:
      speed: 30
      loops: 0
      priority: 300
      show_tokens:
        led: led_zero_suit


animations:
  room_1b_backglass_scroll_up_slow:
    - property: y
      value: 1280
      relative: true
      duration: 1s
    - property: y
      value: -1280
      relative: true
      duration: 0s
      repeat: true
  room_1b_backglass_scroll_up_fast:
    - property: y
      value: 1280
      relative: true
      duration: 0.5s
    - property: y
      value: -1280
      relative: true
      duration: 0s
      repeat: true

slides:
  room_1b_backglass_slide:
    widgets:
      - type: image
        image: room_1b_backglass_rain
        opacity: 0.5
        y: -1
        anchor_y: top
        animations:
          show_slide: room_1b_backglass_scroll_up_fast
      - type: image
        image: room_1b_backglass_rain
        opacity: 0.5
        y: 1279
        anchor_y: top
        animations:
          show_slide: room_1b_backglass_scroll_up_fast
      - type: image
        image: gunship_flying
        y: 700
      - type: image
        image: room_1b_backglass_rain
        y: -1
        anchor_y: top
        animations:
          show_slide: room_1b_backglass_scroll_up_slow
      - type: image
        image: room_1b_backglass_rain
        y: 1279
        anchor_y: top
        animations:
          show_slide: room_1b_backglass_scroll_up_slow
    transition: fade
    transition_out: fade
  room_1b_splash_slide:
    widgets:
      - type: image
        image: room_1b_splash

slide_player:
  room_1b_show_backglass:
    room_1b_backglass_slide:
      target: backglass
    room_1b_splash_slide:
      target: dmd
      expire: 1.5s

sounds:
  room_1b_sound_ship_left:
    file: room_1b_sound_ship_left.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  room_1b_sound_ship_right:
    file: room_1b_sound_ship_right.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None


sound_player:
  room_1b_ship_navigated: shoot_the_scoop
  room_1b_ship_left: room_1b_sound_ship_left
  room_1b_ship_right: room_1b_sound_ship_right
  room_1b_play_shoot_the_orbit: shoot_the_orbit
  room_1b_play_shoot_the_right_orbit: shoot_the_right_orbit
  room_1b_play_shoot_the_left_orbit: shoot_the_left_orbit


event_player:
  scoop_award_land_the_gunship: room_1b_achieved
  mode_room_1b_gunship_started:
    cmd_map_position:
      room: '1b'
      visit: True
    cmd_play_map_music:
      music: music_crateria
  mode_room_1b_gunship_started{current_player.room_1b_step_2 == 0}:
    - room_1b_show_backglass
  mode_room_1b_gunship_started{current_player.room_1b_step_2 != 0}:
    - room_1b_already_complete
  mode_room_1b_gunship_started{current_player.crateria_landed > 0}: room_1b_already_complete
  mode_room_1b_gunship_started{current_player.room_1b_step_1a == 0 and current_player.room_1b_step_1b == 0}: room_1b_play_shoot_the_orbit
  mode_room_1b_gunship_started{current_player.room_1b_step_1a == 1 and current_player.room_1b_step_1b == 0}: room_1b_play_shoot_the_right_orbit
  mode_room_1b_gunship_started{current_player.room_1b_step_1a == 0 and current_player.room_1b_step_1b == 1}: room_1b_play_shoot_the_left_orbit
  room_1b_ship_left{current_player.room_1b_step_1b == 0}: room_1b_play_shoot_the_right_orbit
  room_1b_ship_right{current_player.room_1b_step_1a == 0}: room_1b_play_shoot_the_left_orbit
  room_1b_achieved:
    cmd_map_complete:
      room: '1b'
    room_1b_success:
  room_1b_show_backglass:
    cmd_backbox_show:
      show_type: drop
      min_delay: 1
      max_delay: 2
      background_color: "000004"
      drop_color: "101020"
  room_1b_ship_navigated:
    cmd_scoop_collect:
      index: 0


variable_player:
  mode_room_1b_gunship_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1b
      action: set
  room_1b_ship_left:
    score: (200000 + current_player.crateria_shot_bonus + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
    room_special_score:
      int: (200000 + current_player.crateria_shot_bonus + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
      action: set
    room_1b_step_1a:
      int: 1
      action: set
  room_1b_ship_right:
    score: (150000 + current_player.crateria_shot_bonus + (current_player.area_bonus_ne * 50000)) * current_player.multiplier
    room_special_score:
      int: (150000 + current_player.crateria_shot_bonus + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
      action: set
    room_1b_step_1b:
      int: 1
      action: set
  room_1b_achieved:
    score: (150000 + current_player.crateria_shot_bonus + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
    room_special_score:
      int: (150000 + current_player.crateria_shot_bonus + (current_player.area_bonus_nw * 50000)) * current_player.multiplier
      action: set
    room_1b_step_2:
      int: 1
      action: set
  room_1b_increase_value_shot_hit:
    crateria_shot_bonus: 25000
