#config_version=5
mode:
  code: drop_targets.DropTargets
  start_events: drop_target_mode_should_start
  priority: 100

event_player:
  mode_drop_targets_started:
    - drop_targets_enable_scoring:3.5s
    - drop_targets_continue:3s

shot_profiles:
  drop_target_hit_me:
    states:
      - name: lit
        show: fade_one_light

shots:
  drop_1_shot:
    hit_events: drop_target_drop_one_down
    profile: drop_target_hit_me
    disable_events: mode_drop_targets_started, drop_target_drop_one_down
    enable_events: drop_targets_enable_scoring
    show_tokens:
      led: led_drop_1
      color: drop_target_can_hit
  drop_2_shot:
    hit_events: drop_target_drop_two_down
    profile: drop_target_hit_me
    disable_events: mode_drop_targets_started, drop_target_drop_two_down
    enable_events: drop_targets_enable_scoring
    show_tokens:
      led: led_drop_2
      color: drop_target_can_hit
  drop_3_shot:
    hit_events: drop_target_drop_three_down
    profile: drop_target_hit_me
    disable_events: mode_drop_targets_started, drop_target_drop_three_down
    enable_events: drop_targets_enable_scoring
    show_tokens:
      led: led_drop_3
      color: drop_target_can_hit

variable_player:
  drop_1_shot_hit:
    score: 1000
  drop_2_shot_hit:
    score: 10000
  drop_3_shot_hit:
    score: 25000
