#config_version=5
mode:
    start_events: ball_starting
    stop_events: game_ending, mode_1b_success
    stop_on_ball_end: false
    priority: 300

accruals:
  mode_1b_complete_left_orbit:
    events: left_orbit_hit
    events_when_complete: mode_1b_ship_left
    persist_state: true
    reset_on_complete: false
  mode_1b_complete_right_orbit:
    events: right_orbit_hit
    events_when_complete: mode_1b_ship_right
    persist_state: true
    reset_on_complete: false
  mode_1b_complete_orbits:
    events:
      - mode_1b_ship_left
      - mode_1b_ship_right
    events_when_complete: mode_1b_ship_navigated
    persist_state: true
    reset_on_complete: false
  mode_1b_land_ship:
    enable_events: mode_1b_ship_navigated
    events: scoop_shot_hit
    events_when_complete: mode_1b_achieved
    persist_state: true
    reset_on_complete: false

show_player:
  mode_1b_ship_left:
    mode_1b_go_left:
      loops: 0
  mode_1b_ship_right:
    mode_1b_go_right:
      loops: 0
  mode_1b_achieved:
    mode_1b_land_ship:
      events_when_completed: mode_1b_gunship_landing_animated
      loops: 0
  mode_mode_1b_started{not devices.accruals.mode_1b_complete_left_orbit.completed}:
    blink_light:
      key: left_orbit_blink
      show_tokens:
        led: led_enter_left_orbit
        color: 00ffff
  mode_1b_ship_left:
    left_orbit_blink:
      action: stop
  mode_mode_1b_started{not devices.accruals.mode_1b_complete_left_orbit.completed}:
    blink_light:
      key: left_orbit_blink
      show_tokens:
        led: led_enter_left_orbit
        color: 00ffff
  mode_1b_ship_left:
    left_orbit_blink:
      action: stop
  mode_mode_1b_started{not devices.accruals.mode_1b_complete_right_orbit.completed}:
    blink_light:
      key: right_orbit_blink
      show_tokens:
        led: led_enter_right_orbit
        color: 00ffff
  mode_1b_ship_right:
    right_orbit_blink:
      action: stop

event_player:
  mode_1b_gunship_landing_animated:
    - mode_1b_success

variable_player:
  mode_1b_ship_left:
    score: 50000
  mode_1b_ship_right:
    score: 50000
  mode_1b_achieved:
    score: 75000
