#config_version=5
mode:
  start_events: skillshot_should_start
  stop_events: skillshot_stage_one_end, skillshot_bombs_success, skillshot_bombs_failure
  priority: 500

timers:
  skillshot_bombs_move:
    end_value: 4
    tick_interval: 1s
    restart_on_complete: true
    control_events:
      - event: mode_skillshot_bombs_started
        action: restart

light_player:
  skillshot_bombs_left_lit:
    led_bomb_bank_1:
      color: "A00050"
    led_bomb_bank_2:
      color: stop
  skillshot_bombs_center_lit:
    led_bomb_bank_1:
      color: stop
    led_bomb_bank_2:
      color: "A00050"
    led_bomb_bank_3:
      color: stop
  skillshot_bombs_right_lit:
    led_bomb_bank_2:
      color: stop
    led_bomb_bank_3:
      color: "A00050"

event_player:
  timer_skillshot_bombs_move_tick{ticks == 0}: skillshot_bombs_left_lit
  timer_skillshot_bombs_move_tick{ticks == 1}: skillshot_bombs_center_lit
  timer_skillshot_bombs_move_tick{ticks == 2}: skillshot_bombs_right_lit
  timer_skillshot_bombs_move_tick{ticks == 3}: skillshot_bombs_center_lit
  power_bomb_1_shot_hit{current_player.skillshot_bombs_lit == 0}: skillshot_bombs_success, power_bomb_collected
  power_bomb_1_shot_hit{current_player.skillshot_bombs_lit != 0}: skillshot_bombs_failure
  power_bomb_2_shot_hit{current_player.skillshot_bombs_lit == 1}: skillshot_bombs_success, power_bomb_collected
  power_bomb_2_shot_hit{current_player.skillshot_bombs_lit != 1}: skillshot_bombs_failure
  power_bomb_3_shot_hit{current_player.skillshot_bombs_lit == 2}: skillshot_bombs_success, power_bomb_collected
  power_bomb_3_shot_hit{current_player.skillshot_bombs_lit != 2}: skillshot_bombs_failure


variable_player:
  skillshot_bombs_left_lit:
    skillshot_bombs_lit:
      action: set
      int: 0
  skillshot_bombs_center_lit:
    skillshot_bombs_lit:
      action: set
      int: 1
  skillshot_bombs_right_lit:
    skillshot_bombs_lit:
      action: set
      int: 2
  skillshot_bombs_success:
    score: 10000 * current_player.multiplier
    power_bombs: 1

sound_player:
  skillshot_bombs_success: skillshot
