#config_version=5

# https://commons.wikimedia.org/wiki/File:Cargo_bay_A300-600ST_Beluga.jpg

mode:
  start_events: room_1p_continue, room_1p_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1n_enter, room_1o_enter, room_1q_enter, room_1p_exit
  priority: 300

shots:
  room_1p_exit_north_shot:
    hit_events: left_orbit_hit
    profile: exit_door_optimum
    enable_events: metroid_open_doors
    disable_events: room_1p_exit_north_shot_hit, metroid_close_doors
    reset_events: room_1p_exit_north_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_1p_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1p_exit_east_shot_hit, metroid_close_doors
    reset_events: room_1p_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_1p_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1p_exit_west_shot_hit, metroid_close_doors
    reset_events: room_1p_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue

slides:
  room_1p_cargo_bay_backglass_slide:
    widgets:
      - type: image
        image: room_1p_cargo_bay_backglass
    transition: fade
    transition_out: fade
  room_1p_cargo_bay_backglass_unpowered_slide:
    widgets:
      - type: image
        image: room_1p_cargo_bay_backglass_unpowered
    transition: fade
    transition_out: fade
  room_1p_cargo_bay_splash_slide:
    widgets:
      - type: image
        image: room_1p_cargo_bay_splash

slide_player:
  mode_room_1p_cargo_bay_started_no_charge:
    room_1p_cargo_bay_backglass_unpowered_slide:
      target: backglass
  mode_room_1p_cargo_bay_started_charge:
    room_1p_cargo_bay_backglass_slide:
      target: backglass
  mode_room_1p_cargo_bay_started:
    room_1p_cargo_bay_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1p_cargo_bay_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  mode_room_1p_cargo_bay_started_charge:
    light_bar_solid:
      loops: -1
      show_tokens:
        color: light_bar_basic
  mode_room_1p_cargo_bay_started_no_charge:
    light_bar_solid:
      loops: -1
      show_tokens:
        color: light_bar_dim
  show_mode_status_report:
    room_1p_cargo_bay_status_report:
      loops: 0
  flipper_cradle_release:
    room_1p_cargo_bay_status_report:
      action: stop

event_player:
  mode_room_1p_cargo_bay_started:
    drop_targets_continue:
    cmd_map_position:
      room: '1p'
      visit: True
    metroid_open_doors:
  mode_room_1p_cargo_bay_started_charge:
    cmd_backbox_show:
      show_type: gradient
      color_start: '808000'
      color_end: '808080'
    cmd_play_map_music:
      music: music_wrecked_ship_generator
  mode_room_1p_cargo_bay_started_no_charge:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 7
      max_cutoff: 12
      color1: '000004'
      color2: '200800'
    cmd_play_map_music:
      music: music_wrecked_ship
  mode_room_1p_cargo_bay_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1p_cargo_bay_started_no_charge
  mode_room_1p_cargo_bay_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1p_cargo_bay_started_charge
  room_1p_exit_north_shot_hit.1: drop_targets_save
  room_1p_exit_north_shot_hit.2: room_1n_enter
  room_1p_exit_east_shot_hit.1: drop_targets_save
  room_1p_exit_east_shot_hit.2: room_1q_enter
  room_1p_exit_west_shot_hit.1: drop_targets_save
  room_1p_exit_west_shot_hit.2: room_1o_enter

variable_player:
  mode_room_1p_cargo_bay_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1p
      action: set
