#config_version=5
mode:
  start_events: room_2d_continue, room_2d_enter
  stop_events: game_ending, ball_ending, room_1z_enter, room_2e_enter
  priority: 300

shots:
  room_2d_exit_east_closed_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: room_2d_enable_east_missile_door
    disable_events: room_2d_disable_east_missile_door, room_2d_open_east_door
    reset_events: room_2d_disable_east_missile_door, room_2d_open_east_door
    show_tokens:
      led: led_enter_right_orbit
      color: door_red
  room_2d_exit_north_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: mode_room_2d_abyss_started
    disable_events: room_2d_exit_north_shot_hit
    reset_events: room_2d_exit_north_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_2d_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: room_2d_enable_east_door
    disable_events: room_2d_disable_east_door
    reset_events: room_2d_disable_east_door
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue

slides:
  room_2d_abyss_backglass_slide:
    widgets:
      - type: image
        image: room_2d_abyss_backglass
    transition: fade
    transition_out: fade
  room_2d_abyss_splash_slide:
    widgets:
      - type: image
        image: room_2d_abyss_splash

slide_player:
  mode_room_2d_abyss_started:
    room_2d_abyss_backglass_slide:
      target: backglass
    room_2d_abyss_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2d_abyss_started:
    room_2d_underwater:
      loops: -1
      speed: 10

event_player:
  mode_room_2d_abyss_started:
    cmd_backbox_show:
      show_type: fire
  mode_room_2d_abyss_started{current_player.door_2d_2e == 0}: room_2d_enable_east_missile_door, room_2d_disable_east_door
  mode_room_2d_abyss_started{current_player.door_2d_2e == 1}: room_2d_enable_east_door, room_2d_disable_east_missile_door
  room_2d_exit_east_closed_shot_hit{current_player.missiles > 0}: room_2d_open_east_door
  room_2d_open_east_door: room_2d_exit_east_shot_hit
  room_2d_exit_north_shot_hit: room_1z_enter
  room_2d_exit_east_shot_hit: room_2e_enter

variable_player:
  mode_room_2d_abyss_started:
    continue_room:
      string: 2d
      action: set
  room_2d_open_east_door:
    missiles: -1
    door_2d_2e:
      int: 1
      action: set
