#config_version=5
mode:
  start_events: mode_base_starting
  priority: 100

shots:
  bridge_rail_shot:
    switch: s_top_lane_2

timers:
  bridge_enable_coil_timer:
    start_value: 1
    end_value: 2
    tick_interval: .5s
    control_events:
      - event: bridge_rail_shot_hit
        action: restart
  bridge_disable_coil_timer:
    start_value: 1
    end_value: 3
    tick_interval: 1s
    control_events:
      - event: timer_bridge_enable_coil_timer_complete
        action: restart

coil_player:
  timer_bridge_enable_coil_timer_complete:
    c_bridge:
      action: enable
  mode_bridge_ending:
    c_bridge:
      action: disable
  timer_bridge_disable_coil_timer_complete:
    c_bridge:
      action: disable

show_player:
  timer_bridge_enable_coil_timer_complete:
    bridge_explode:
      priority: 1000
      speed: 1.5
      loops: 1
      show_tokens:
        led_1: gi_bomb_bank
        led_2: gi_upper_flipper_bottom
        color_1: 'FF0000'
        color_2: 'FF8000'
        color_3: 'FFFF00'
        color_4: 'FFFFFF'
        color_off: '000000'
    playfield_explode:
      priority: 1000
      speed: 50
      loops: 1
