#config_version=5

# https://commons.wikimedia.org/wiki/File:Quartz_var._citrine_and_amethyst.jpg
# https://commons.wikimedia.org/wiki/File:Rhodonite_et_quartz_(P%C3%A9rou).JPG
# https://commons.wikimedia.org/wiki/File:SCUBA_Silfra.jpg

mode:
  start_events: room_2h_continue, room_2h_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2d_enter, room_2g_enter, room_2i_enter, room_2h_exit
  priority: 300


shot_profiles:
  room_2h_gem_shot:
    states:
      - name: normal
        show: fade_one_light
        speed: 2
        show_tokens:
          color: '800080'
      - name: extra
        show: fade_one_light
        speed: 4
        show_tokens:
          color: 'E75A56'



shots:
  room_2h_exit_north_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_2h_exit_north_shot_hit, metroid_close_doors
    reset_events: room_2h_exit_north_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_2h_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_2h_exit_west_shot_hit, metroid_close_doors
    reset_events: room_2h_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_2h_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_2h_exit_south_shot_hit, metroid_close_doors
    reset_events: room_2h_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_2h_add_crystal_shot:
    switches:
      - s_thin_orange
      - s_lower_right_bank_1
      - s_lower_right_bank_2
      - s_lower_right_bank_3
      - s_missile_bank_1
      - s_missile_bank_2
      - s_missile_bank_3
      - s_shatz
      - s_purple_1
      - s_purple_2
      - s_purple_3
      - s_left_target_1
      - s_left_target_2
      - s_left_target_3
    enable_events: mode_room_2h_crystalline_seabed_started
    disable_events: mode_room_2h_crystalline_seabed_ending
  room_2h_gem_shot_1:
    hit_events: left_orbit_hit
    profile: room_2h_gem_shot
    enable_events: room_2h_gem_shot_enable
    disable_events: mode_room_2h_crystalline_seabed_started
    advance_events: room_2h_gem_shot_enable
    show_tokens:
      led: led_enter_left_orbit
  room_2h_gem_shot_2:
    switch: s_ramp_enter
    profile: room_2h_gem_shot
    enable_events: room_2h_gem_shot_enable
    disable_events: mode_room_2h_crystalline_seabed_started
    show_tokens:
      led: led_enter_ramp
  room_2h_gem_shot_3:
    switch: s_side_ramp_made
    profile: room_2h_gem_shot
    enable_events: room_2h_gem_shot_enable
    disable_events: mode_room_2h_crystalline_seabed_started
    show_tokens:
      led: led_enter_side_ramp


shot_groups:
  room_2h_gem_shots:
    shots: room_2h_gem_shot_1, room_2h_gem_shot_3, room_2h_gem_shot_2
    enable_events: room_2h_gem_shot_enable
    disable_events: mode_room_2h_crystalline_seabed_started
    reset_events: mode_room_2h_crystalline_seabed_started
    rotate_events: room_2h_add_crystal_shot_hit


slides:
  room_2h_crystalline_seabed_backglass_slide:
    widgets:
      - type: image
        image: room_2h_crystalline_seabed_backglass
    transition: fade
    transition_out: fade
  room_2h_crystalline_seabed_splash_slide:
    widgets:
      - type: image
        image: room_2h_crystalline_seabed_splash

slide_player:
  mode_room_2h_crystalline_seabed_started:
    room_2h_crystalline_seabed_backglass_slide:
      target: backglass
    room_2h_crystalline_seabed_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2h_crystalline_seabed_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_2h_crystalline_seabed_status_report:
      loops: 0
  flipper_cradle_release:
    room_2h_crystalline_seabed_status_report:
      action: stop
  room_2h_add_crystal_shot_hit:
    room_2h_crystal_add:
      loops: 0

sounds:
  room_2h_crystal:
    file: room_2h_crystal.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None


sound_player:
  room_2h_add_crystal_shot_hit: room_2h_crystal


event_player:
  mode_room_2h_crystalline_seabed_started:
    cmd_backbox_show:
      show_type: gradient
      color_start: "000020"
      color_end: "002000"
    drop_targets_continue:
    cmd_map_position:
      room: '2h'
      visit: True
    cmd_play_map_music:
      music: music_maridia
    metroid_open_doors:
  mode_room_2h_crystalline_seabed_started{current_player.room_2h_crystals > 0}: room_2h_gem_shot_enable
  player_room_2h_crystals{value == 1}: room_2h_gem_shot_enable
  room_2h_exit_north_shot_hit.1: drop_targets_save
  room_2h_exit_north_shot_hit.2: room_2d_enter
  room_2h_exit_west_shot_hit.1: drop_targets_save
  room_2h_exit_west_shot_hit.2: room_2g_enter
  room_2h_exit_south_shot_hit.1: drop_targets_save
  room_2h_exit_south_shot_hit.2: room_2i_enter

variable_player:
  mode_room_2h_crystalline_seabed_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2h
      action: set
  room_2h_add_crystal_shot_hit:
    room_2h_crystals: 1
