#config_version=5

# https://commons.wikimedia.org/wiki/File:Quartz_var._citrine_and_amethyst.jpg
# https://commons.wikimedia.org/wiki/File:Rhodonite_et_quartz_(P%C3%A9rou).JPG
# https://commons.wikimedia.org/wiki/File:SCUBA_Silfra.jpg

mode:
  start_events: room_2h_continue, room_2h_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2d_enter, room_2g_enter, room_2i_enter
  priority: 300

shots:
  room_2h_exit_north_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: mode_room_2h_crystalline_seabed_started
    disable_events: room_2h_exit_north_shot_hit
    reset_events: room_2h_exit_north_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_2h_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: mode_room_2h_crystalline_seabed_started
    disable_events: room_2h_exit_west_shot_hit
    reset_events: room_2h_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_2h_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: mode_room_2h_crystalline_seabed_started
    disable_events: room_2h_exit_south_shot_hit
    reset_events: room_2h_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue

slides:
  room_2h_crystalline_seabed_backglass_slide:
    widgets:
      - type: image
        image: room_2h_crystalline_seabed_backglass
    transition: fade
    transition_out: fade
  room_2h_crystalline_seabed_splash_slide:
    widgets:
      - type: image
        image: room_2h_crystalline_seabed_splash

slide_player:
  mode_room_2h_crystalline_seabed_started:
    room_2h_crystalline_seabed_backglass_slide:
      target: backglass
    room_2h_crystalline_seabed_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2h_crystalline_seabed_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_2h_crystalline_seabed_status_report:
      loops: 0
  flipper_cradle_release:
    room_2h_crystalline_seabed_status_report:
      action: stop

event_player:
  mode_room_2h_crystalline_seabed_started:
    cmd_backbox_show:
      show_type: gradient
      color_start: "000020"
      color_end: "002000"
    drop_targets_continue:
    cmd_map_position:
      room: '2h'
      visit: True
  room_2h_exit_north_shot_hit.1: drop_targets_save
  room_2h_exit_north_shot_hit.2: room_2d_enter
  room_2h_exit_west_shot_hit.1: drop_targets_save
  room_2h_exit_west_shot_hit.2: room_2g_enter
  room_2h_exit_south_shot_hit.1: drop_targets_save
  room_2h_exit_south_shot_hit.2: room_2i_enter

variable_player:
  mode_room_2h_crystalline_seabed_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2h
      action: set
