#config_version=5

# replace xx with room code
# replace room_template with mode name

mode:
  start_events: room_xx_continue, room_xx_enter
  stop_events: game_ending, ball_ending, metroid_base_ended
  priority: 300

slides:
  room_template_backglass_slide:
    widgets:
      - type: image
        image: room_template_backglass
    transition: fade
    transition_out: fade
  room_template_splash_slide:
    widgets:
      - type: image
        image: room_template_splash

slide_player:
  mode_room_template_started:
    room_template_backglass_slide:
      target: backglass
    room_template_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_template_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_template_status_report:
      loops: 0
  flipper_cradle_release:
    room_template_status_report:
      action: stop

event_player:
  mode_room_template_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: 'xx'
      visit: True

variable_player:
  mode_room_template_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: xx
      action: set
