#config_version=5
mode:
    start_events: mode_base_starting
    priority: 100

show_player:
  spinner_shot_hit:
    spin_jump_spins:
      loops: 0

sounds:
  spin_jump:
    file: spin_jump.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None

sound_player:
  spinner_shot_hit: spin_jump

variable_player:
  spinner_shot_hit:
    spinners: 1
    score:
      int: (50 + (10 * current_player.spinners)) * current_player.multiplier
