#config_version=5
mode:
  start_events: room_1a_continue, room_1a_enter
  stop_events: game_ending, ball_ending, room_1b_enter
  priority: 300

shots:
  room_1a_exit_east_shot:
    switch: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_1a_lush_cavern_started
    disable_events: room_1a_exit_east_shot_hit
    reset_events: room_1a_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue

slides:
  room_1a_lush_cavern_backglass_slide:
    widgets:
      - type: image
        image: room_1a_lush_cavern_backglass
    transition: fade
    transition_out: fade
  room_1a_lush_cavern_splash_slide:
    widgets:
      - type: image
        image: room_1a_lush_cavern_splash

slide_player:
  mode_room_1a_lush_cavern_started:
    room_1a_lush_cavern_backglass_slide:
      target: backglass
    room_1a_lush_cavern_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1a_lush_cavern_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1a_lush_cavern_status_report:
      loops: 0
  flipper_cradle_release:
    room_1a_lush_cavern_status_report:
      action: stop

event_player:
  mode_room_1a_lush_cavern_started:
    cmd_backbox_show:
      show_type: twinkle
      background_color: "100040"
      twinkle_color: "104000"
      twinkle_count: 15
    drop_targets_continue:
  mode_room_1a_lush_cavern_ending: drop_targets_save
  room_1a_exit_east_shot_hit: room_1b_enter


variable_player:
  mode_room_1a_lush_cavern_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1a
      action: set
