#config_version=5
mode:
  start_events: room_1a_continue, room_1a_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1b_enter, room_1f_enter, room_1a_exit
  priority: 300

shot_profiles:
  room_1a_lanes:
    states:
      - name: lit
        speed: 30
        show: blink_light
        show_tokens:
          color: 'BFFF00'
      - name: unlit
        show: led_color
        show_tokens:
          color: stop

shots:
  room_1a_exit_east_shot:
    switch: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_1a_lush_cavern_started
    disable_events: room_1a_exit_east_shot_hit
    reset_events: room_1a_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1a_exit_south_closed_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: room_1a_enable_south_missile_door
    disable_events: room_1a_disable_south_missile_door, room_1a_open_south_door
    reset_events: room_1a_disable_south_missile_door, room_1a_open_south_door
    show_tokens:
      led: led_enter_scoop
      color: door_red
  room_1a_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: room_1a_enable_south_door
    disable_events: room_1a_disable_south_door
    reset_events: room_1a_disable_south_door
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1a_left_outlane_shot:
    switch: s_left_outlane
    profile: room_1a_lanes
    show_tokens:
      led: led_left_outlane
  room_1a_left_inlane_shot:
    switch: s_left_inlane
    profile: room_1a_lanes
    show_tokens:
      led: led_left_inlane
  room_1a_right_outlane_shot:
    switch: s_right_outlane
    profile: room_1a_lanes
    show_tokens:
      led: led_right_outlane
  room_1a_right_inlane_shot:
    switch: s_right_inlane
    profile: room_1a_lanes
    show_tokens:
      led: led_right_inlane

slides:
  room_1a_lush_cavern_backglass_slide:
    widgets:
      - type: image
        image: room_1a_lush_cavern_backglass
    transition: fade
    transition_out: fade
  room_1a_lush_cavern_splash_slide:
    widgets:
      - type: image
        image: room_1a_lush_cavern_splash

slide_player:
  mode_room_1a_lush_cavern_started:
    room_1a_lush_cavern_backglass_slide:
      target: backglass
    room_1a_lush_cavern_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1a_lush_cavern_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1a_lush_cavern_status_report:
      loops: 0
  flipper_cradle_release:
    room_1a_lush_cavern_status_report:
      action: stop

event_player:
  mode_room_1a_lush_cavern_started:
    cmd_backbox_show:
      show_type: twinkle
      background_color: "000800"
      twinkle_color: "604000"
      twinkle_count: 20
      steps: 50
    drop_targets_continue:
    cmd_map_position:
      room: '1a'
      visit: True
  mode_room_1a_lush_cavern_ending: drop_targets_save
  mode_room_1a_lush_cavern_started{current_player.door_1a_1f == 0}: room_1a_enable_south_missile_door, room_1a_disable_south_door
  mode_room_1a_lush_cavern_started{current_player.door_1a_1f == 1}: room_1a_enable_south_door, room_1a_disable_south_missile_door
  room_1a_exit_south_closed_shot_hit{current_player.missiles > 0}: room_1a_open_south_door
  room_1a_open_south_door: room_1a_exit_south_shot_hit
  room_1a_exit_south_shot_hit.1: drop_targets_save
  room_1a_exit_south_shot_hit.2: room_1f_enter
  room_1a_exit_east_shot_hit.1: drop_targets_save
  room_1a_exit_east_shot_hit.2: room_1b_enter


variable_player:
  mode_room_1a_lush_cavern_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1a
      action: set
  room_1a_open_south_door:
    missiles: -1
    door_1a_1f:
      int: 1
      action: set
