#config_version=5
mode:
  start_events: room_1a_continue, room_1a_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1b_enter, room_1f_enter, room_1a_exit
  priority: 300

shot_profiles:
  room_1a_lanes:
    states:
      - name: lit
        speed: 30
        show: blink_light
        show_tokens:
          color: 'BFFF00'
      - name: unlit
        show: led_color
        show_tokens:
          color: stop
  room_1a_collect:
    states:
      - name: lit
        speed: 30
        show: blink_light
        show_tokens:
          color: '00FF00'
      - name: unlit
        show: led_color
        show_tokens:
          color: stop

shots:
  room_1a_exit_east_shot:
    switch: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_1a_lush_cavern_started
    disable_events: room_1a_exit_east_shot_hit
    reset_events: room_1a_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1a_exit_south_closed_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: room_1a_enable_south_missile_door
    disable_events: room_1a_disable_south_missile_door, room_1a_open_south_door
    reset_events: room_1a_disable_south_missile_door, room_1a_open_south_door
    show_tokens:
      led: led_enter_scoop
      color: door_red
  room_1a_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: room_1a_enable_south_door
    disable_events: room_1a_disable_south_door
    reset_events: room_1a_disable_south_door
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1a_left_outlane_shot:
    switch: s_left_outlane
    profile: room_1a_lanes
    show_tokens:
      led: led_left_outlane
  room_1a_left_inlane_shot:
    switch: s_left_inlane
    profile: room_1a_lanes
    show_tokens:
      led: led_left_inlane
  room_1a_right_outlane_shot:
    switch: s_right_outlane
    profile: room_1a_lanes
    show_tokens:
      led: led_right_outlane
  room_1a_right_inlane_shot:
    switch: s_right_inlane
    profile: room_1a_lanes
    show_tokens:
      led: led_right_inlane
  room_1a_collect_1_shot:
    switch: s_left_passage
    profile: room_1a_collect
    show_tokens:
      led: led_enter_secret_passage
  room_1a_collect_2_shot:
    hit_events: left_orbit_hit
    profile: room_1a_collect
    show_tokens:
      led: led_enter_left_orbit
  room_1a_collect_3_shot:
    switch: s_side_ramp_made
    profile: room_1a_collect
    show_tokens:
      led: led_enter_side_ramp
  room_1a_collect_4_shot:
    hit_events: right_orbit_hit
    profile: room_1a_collect
    show_tokens:
      led: led_enter_right_orbit

shot_groups:
  room_1a_lanes_shot_group:
    shots: room_1a_left_outlane_shot, room_1a_left_inlane_shot, room_1a_right_inlane_shot, room_1a_right_outlane_shot
    reset_events: room_1a_collect_shot_group_lit_complete
  room_1a_collect_shot_group:
    shots: room_1a_collect_1_shot, room_1a_collect_2_shot, room_1a_collect_3_shot, room_1a_collect_4_shot
    reset_events: room_1a_collect_shot_group_lit_complete


slides:
  room_1a_lush_cavern_backglass_slide:
    widgets:
      - type: image
        image: room_1a_lush_cavern_backglass
    transition: fade
    transition_out: fade
  room_1a_lush_cavern_splash_slide:
    widgets:
      - type: image
        image: room_1a_lush_cavern_splash

slide_player:
  mode_room_1a_lush_cavern_started:
    room_1a_lush_cavern_backglass_slide:
      target: backglass
    room_1a_lush_cavern_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1a_lush_cavern_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1a_lush_cavern_status_report:
      loops: 0
  flipper_cradle_release:
    room_1a_lush_cavern_status_report:
      action: stop
  room_1a_collect_1_shot_lit_hit:
    special_score_green:
      loops: 0
  room_1a_collect_2_shot_lit_hit:
    special_score_green:
      loops: 0
  room_1a_collect_3_shot_lit_hit:
    special_score_green:
      loops: 0
  room_1a_collect_4_shot_lit_hit:
    special_score_green:
      loops: 0

event_player:
  mode_room_1a_lush_cavern_started:
    cmd_backbox_show:
      show_type: twinkle
      background_color: "000800"
      twinkle_color: "604000"
      twinkle_count: 20
      steps: 50
    drop_targets_continue:
    cmd_map_position:
      room: '1a'
      visit: True
  mode_room_1a_lush_cavern_ending: drop_targets_save
  mode_room_1a_lush_cavern_started{current_player.door_1a_1f == 0}: room_1a_enable_south_missile_door, room_1a_disable_south_door
  mode_room_1a_lush_cavern_started{current_player.door_1a_1f == 1}: room_1a_enable_south_door, room_1a_disable_south_missile_door
  room_1a_exit_south_closed_shot_hit{current_player.missiles > 0}: room_1a_open_south_door
  room_1a_open_south_door: room_1a_exit_south_shot_hit
  room_1a_exit_south_shot_hit.1: drop_targets_save
  room_1a_exit_south_shot_hit.2: room_1f_enter
  room_1a_exit_east_shot_hit.1: drop_targets_save
  room_1a_exit_east_shot_hit.2: room_1b_enter
  room_1a_collect_shot_group_lit_complete:
    cmd_map_complete:
      room: '1a'

variable_player:
  mode_room_1a_lush_cavern_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1a
      action: set
  room_1a_open_south_door:
    missiles: -1
    door_1a_1f:
      int: 1
      action: set
  room_1a_lanes_shot_group_lit_hit:
    room_1a_multiplier: 1
  room_1a_collect_shot_group_lit_complete:
    room_1a_multiplier:
      action: set
      int: 1
  room_1a_collect_1_shot_lit_hit:
    score: (50000 + current_player.crateria_shot_bonus + (25000 * current_player.area_bonus_sw)) * current_player.room_1a_multiplier * current_player.multiplier
    room_special_score:
      int: (50000 + current_player.crateria_shot_bonus + (25000 * current_player.area_bonus_sw)) * current_player.room_1a_multiplier * current_player.multiplier
      action: set
  room_1a_collect_2_shot_lit_hit:
    score: (120000 + current_player.crateria_shot_bonus + (50000 * current_player.area_bonus_nw)) * current_player.room_1a_multiplier * current_player.multiplier
    room_special_score:
      int: (120000 + current_player.crateria_shot_bonus + (50000 * current_player.area_bonus_nw)) * current_player.room_1a_multiplier * current_player.multiplier
      action: set
  room_1a_collect_3_shot_lit_hit:
    score: (90000 + current_player.crateria_shot_bonus + (40000 * current_player.area_bonus_ne)) * current_player.room_1a_multiplier * current_player.multiplier
    room_special_score:
      int: (90000 + current_player.crateria_shot_bonus + (40000 * current_player.area_bonus_ne)) * current_player.room_1a_multiplier * current_player.multiplier
      action: set
  room_1a_collect_4_shot_lit_hit:
    score: (90000 + current_player.crateria_shot_bonus + (35000 * current_player.area_bonus_ne)) * current_player.room_1a_multiplier * current_player.multiplier
    room_special_score:
      int: (90000 + current_player.crateria_shot_bonus + (35000 * current_player.area_bonus_ne)) * current_player.room_1a_multiplier * current_player.multiplier
      action: set
