#config_version=5

# https://commons.wikimedia.org/wiki/File:Laser_module.jpg
# https://commons.wikimedia.org/wiki/File:Duluth_Armory_6.jpg

mode:
  start_events: room_1u_continue, room_1u_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1r_enter, room_1w_enter, room_1u_exit
  priority: 300


shot_profiles:
  room_1u_orbit:
    states:
      - name: lit
        show: blink_light
        speed: 2
        sync_ms: 1000
        show_tokens:
          color: 'CF8E40'
  room_1u_light:
    states:
      - name: lit
        show: blink_light
        speed: 2
        sync_ms: 1000
        show_tokens:
          color: '3900C4'

shots:
  room_1u_exit_north_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1u_exit_north_shot_hit, metroid_close_doors
    reset_events: room_1u_exit_north_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1u_exit_south_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1u_exit_south_shot_hit, metroid_close_doors
    reset_events: room_1u_exit_south_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1u_speed_shot:
    switch: s_spinner
  room_1u_left_orbit_shot:
    hit_events: left_orbit_hit
    profile: room_1u_orbit
    enable_events: mode_room_1u_the_armory_started
    disable_events: mode_room_1u_the_armory_ending
    show_tokens:
      led: led_enter_left_orbit
  room_1u_right_orbit_shot:
    hit_events: right_orbit_hit
    profile: room_1u_orbit
    enable_events: mode_room_1u_the_armory_started
    disable_events: mode_room_1u_the_armory_ending
    show_tokens:
      led: led_enter_right_orbit
  room_1u_light_jackpot_shot:
    switch: s_side_ramp_made
    profile: room_1u_light
    enable_events: mode_room_1u_the_armory_started
    disable_events: mode_room_1u_the_armory_ending
    show_tokens:
      led: led_enter_side_ramp


slides:
  room_1u_the_armory_backglass_slide:
    widgets:
      - type: image
        image: room_1u_the_armory_backglass
    transition: fade
    transition_out: fade
  room_1u_the_armory_splash_slide:
    widgets:
      - type: image
        image: room_1u_the_armory_splash


slide_player:
  mode_room_1u_the_armory_started:
    room_1u_the_armory_backglass_slide:
      target: backglass
    room_1u_the_armory_splash_slide:
      target: dmd
      expire: 1.5s


show_player:
  mode_room_1u_the_armory_started:
    room_1u_the_armory_base_gi:
      loops: -1
      speed: 30
  show_mode_status_report:
    room_1u_the_armory_status_report:
      loops: 0
  flipper_cradle_release:
    room_1u_the_armory_status_report:
      action: stop
  room_1u_laser_speed_1:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 20
      priority: 100
  room_1u_laser_speed_2:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 30
      priority: 100
  room_1u_laser_speed_3:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 40
      priority: 100
  room_1u_laser_speed_4:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 50
      priority: 100
  room_1u_laser_speed_5:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 60
      priority: 100
  room_1u_laser_speed_6:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 70
      priority: 100
  room_1u_laser_speed_7:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 80
      priority: 100


event_player:
  mode_room_1u_the_armory_started:
    cmd_backbox_show:
      show_type: spectrum
      color1: '000000'
      color2: '200000'
      color3: '000000'
    drop_targets_continue:
    cmd_map_position:
      room: '1u'
      visit: True
    metroid_open_doors:
    room_1u_play_music:
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed < 3}: room_1u_laser_speed_1
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 3 and current_player.room_1u_laser_speed < 6}: room_1u_laser_speed_2
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 6 and current_player.room_1u_laser_speed < 9}: room_1u_laser_speed_3
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 9 and current_player.room_1u_laser_speed < 12}: room_1u_laser_speed_4
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 12 and current_player.room_1u_laser_speed < 15}: room_1u_laser_speed_5
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 15 and current_player.room_1u_laser_speed < 18}: room_1u_laser_speed_6
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 18}: room_1u_laser_speed_7
  room_1u_play_music:
    cmd_play_map_music:
      music: music_brinstar_side_entrance
  player_room_1u_laser_speed{value == 3}: room_1u_laser_speed_2
  player_room_1u_laser_speed{value == 6}: room_1u_laser_speed_3
  player_room_1u_laser_speed{value == 9}: room_1u_laser_speed_4
  player_room_1u_laser_speed{value == 12}: room_1u_laser_speed_5
  player_room_1u_laser_speed{value == 15}: room_1u_laser_speed_6
  player_room_1u_laser_speed{value == 18}: room_1u_laser_speed_7
  room_1u_exit_north_shot_hit.1: drop_targets_save
  room_1u_exit_north_shot_hit.2: room_1r_enter
  room_1u_exit_south_shot_hit.1: drop_targets_save
  room_1u_exit_south_shot_hit.2: room_1w_enter


variable_player:
  mode_room_1u_the_armory_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1u
      action: set
  room_1u_speed_shot_hit:
    room_1u_laser_speed: 1

