#config_version=5

# https://commons.wikimedia.org/wiki/File:Laser_module.jpg
# https://commons.wikimedia.org/wiki/File:Duluth_Armory_6.jpg

mode:
  start_events: room_1u_continue, room_1u_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1r_enter, room_1w_enter, room_1u_exit
  priority: 300


shots:
  room_1u_exit_north_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1u_exit_north_shot_hit, metroid_close_doors
    reset_events: room_1u_exit_north_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1u_exit_south_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1u_exit_south_shot_hit, metroid_close_doors
    reset_events: room_1u_exit_south_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1u_speed_shot:
    switch: s_spinner


slides:
  room_1u_the_armory_backglass_slide:
    widgets:
      - type: image
        image: room_1u_the_armory_backglass
    transition: fade
    transition_out: fade
  room_1u_the_armory_splash_slide:
    widgets:
      - type: image
        image: room_1u_the_armory_splash


slide_player:
  mode_room_1u_the_armory_started:
    room_1u_the_armory_backglass_slide:
      target: backglass
    room_1u_the_armory_splash_slide:
      target: dmd
      expire: 1.5s


show_player:
  # mode_room_1u_the_armory_started:
  show_mode_status_report:
    room_1u_the_armory_status_report:
      loops: 0
  flipper_cradle_release:
    room_1u_the_armory_status_report:
      action: stop
  room_1u_laser_speed_1:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 20
      priority: 100
  room_1u_laser_speed_2:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 30
      priority: 100
  room_1u_laser_speed_3:
    mode_1u_the_armory_gi:
      loops: -1
      speed: 40
      priority: 100



event_player:
  mode_room_1u_the_armory_started:
    cmd_backbox_show:
      show_type: spectrum
      color1: '000000'
      color2: '200000'
      color3: '000000'
    drop_targets_continue:
    cmd_map_position:
      room: '1u'
      visit: True
    metroid_open_doors:
    room_1u_play_music:
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed < 5}: room_1u_laser_speed_1
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 5 and current_player.room_1u_laser_speed < 10}: room_1u_laser_speed_2
  mode_room_1u_the_armory_started{current_player.room_1u_laser_speed >= 10}: room_1u_laser_speed_3
  room_1u_play_music:
    cmd_play_map_music:
      music: music_brinstar_side_entrance
  player_room_1u_laser_speed{value == 5}: room_1u_laser_speed_2
  player_room_1u_laser_speed{value == 10}: room_1u_laser_speed_3
  room_1u_exit_north_shot_hit.1: drop_targets_save
  room_1u_exit_north_shot_hit.2: room_1r_enter
  room_1u_exit_south_shot_hit.1: drop_targets_save
  room_1u_exit_south_shot_hit.2: room_1w_enter


variable_player:
  mode_room_1u_the_armory_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1u
      action: set
  room_1u_speed_shot_hit:
    room_1u_laser_speed: 1

