#config_version=5

autofire_coils:
  pop_1:
    coil: c_pop_1
    switch: s_pop_1
  pop_2:
    coil: c_pop_2
    switch: s_pop_2
  pop_3:
    coil: c_pop_3
    switch: s_pop_3
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_sling
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_sling
  upper_slingshot:
    coil: c_upper_slingshot
    switch: s_upper_sling
    disable_events: ball_ending, service_mode_entered, upper_slingshot_should_disable
    enable_events: ball_started, upper_slingshot_should_enable
  scoop:
    coil: c_scoop
    switch: s_scoop
    disable_events: ball_ending, service_mode_entered, scoop_autofire_should_disable
    # enable_events: ball_started, scoop_autofire_should_enable
    enable_events: scoop_autofire_should_enable
    switch_overwrite:
      debounce: 300ms
  vuk:
    coil: c_vuk
    switch: s_vuk
  pop_sling:
    coil: c_pop_sling
    switch: s_pop_sling

