#config_version=5

ball_devices:
    bd_trough:
        ball_switches: s_trough_4, s_trough_3, s_trough_2, s_trough_1, s_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        eject_targets: bd_plunger
        eject_timeouts: 3s
    bd_plunger:
        ball_switches: s_shooter_lane
        eject_coil: c_ball_launch
        mechanical_eject: true
        eject_timeouts: 3s
        eject_all_events: tilt
    bd_scoop:
        ball_switches: s_scoop
        eject_coil: c_scoop
        eject_all_events: tilt
    bd_drop_lock_1:
        ball_switches: s_behind_drop_1
        eject_coil: c_drop_1_down
        eject_all_events: tilt
        auto_fire_on_unexpected_ball: False
    bd_drop_lock_2:
        ball_switches: s_behind_drop_2
        eject_coil: c_drop_2_down
        eject_all_events: tilt
        auto_fire_on_unexpected_ball: False
