#config_version=5

coils:
  c_pop_1:
    number: 0-0
    allow_enable: true
  c_pop_2:
    number: 0-1
    allow_enable: true
  c_pop_3:
    number: 0-2
    allow_enable: true
  c_drop_1_reset:
    number: 0-3
    default_hold_power: 0.125
    default_pulse_power: 1
    default_pulse_ms: 20
    allow_enable: true
  c_flipper_upper_right_main:
    number: 0-4
    allow_enable: true
    default_hold_power: 0.125
    default_pulse_ms: 25
  c_scoop:
    number: 0-5
    allow_enable: true
    default_pulse_ms: 19
    default_pulse_power: 0.95
  c_drop_1_down:
    number: 0-8
    default_hold_power: 0.8
    default_pulse_power: 1
    default_pulse_ms: 20
    allow_enable: true
  c_drop_2_down:
    number: 0-9
    default_hold_power: 0.125
    default_pulse_power: 0.8
    default_pulse_ms: 20
    allow_enable: true
  c_drop_2_reset:
    number: 0-10
    default_hold_power: 0.125
    default_pulse_power: 1
    default_pulse_ms: 30
    allow_enable: true
  c_drop_3_reset:
    number: 0-11
    default_hold_power: 0.125
    default_pulse_power: 1
    default_pulse_ms: 25
    allow_enable: true
  c_drop_3_down:
    number: 0-12
    default_hold_power: 0.125
    default_pulse_power: 0.8
    default_pulse_ms: 20
    allow_enable: true
  c_flipper_right_main:
    number: 0-13
    allow_enable: true
    default_hold_power: 0.125
    default_pulse_ms: 22
  c_flipper_left_main:
    number: 0-14
    allow_enable: true
    default_hold_power: 0.125
    default_pulse_ms: 22
  c_upper_slingshot:
    number: 0-15
    allow_enable: true
  c_ball_launch:
    number: 1-3
    allow_enable: true
    default_pulse_ms: 17
    default_pulse_power: 0.8
  c_left_slingshot:
    number: 1-4
    allow_enable: true
  c_right_slingshot:
    number: 1-5
    allow_enable: true
  c_trough_eject:
    number: 1-7
    default_pulse_ms: 40
    allow_enable: true
  c_vuk:
    number: 2-0
    default_pulse_ms: 20
    allow_enable: true
  c_pop_sling:
    number: 2-1
    allow_enable: true
  c_bridge:
    number: 2-2
    allow_enable: true
    default_pulse_power: 1.0
    default_pulse_ms: 20
    default_hold_power: 0.2
