#config_version=4

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: /dev/ttyUSB1, /dev/ttyUSB2

config:
  - machine.yaml
  - graphics.yaml
  - scriptlets.yaml
  - modes.yaml
  - leds.yaml
  - switches.yaml
  - coils.yaml
  - autofire_coils.yaml
  - flippers.yaml
  - ball_devices.yaml

