#config_version=4

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: /dev/ttyUSB1, /dev/ttyUSB2

switches:
  s_right_flipper:
    number: 00
  s_left_flipper:
    number: 01
  s_start:
    number: 02
  s_pop_1:
    number: 03
  s_pop_2:
    number: 04
  s_pop_3:
    number: 05
  s_drop_down:
    number: 06
  s_thin_green:
    number: 07
  s_upper_right_flipper_eos:
    number: 08
  s_captive_ball:
    number: 09
  s_spinner:
    number: 0A
  s_left_target_1:
    number: 0B
  s_left_target_2:
    number: 0C
  s_lower_right_bank_1:
    number: 10
  s_lower_right_bank_2:
    number: 11
  s_lower_right_bank_3:
    number: 12
  s_shooter_lane:
    number: 13
  s_right_outlane:
    number: 14
  s_right_inlane:
    number: 15
  s_rollover_button:
    number: 16
  s_upper_flipper_rubber:
    number: 17
  s_right_flipper_eos:
    number: 18
  s_left_flipper_eos:
    number: 19
  s_left_sling:
    number: 1A
  s_right_sling:
    number: 1B
  s_left_inlane:
    number: 1C
  s_left_outlane:
    number: 1D
  s_skill_bank_1:
    number: 20
  s_skill_bank_2:
    number: 21
  s_skill_bank_3:
    number: 22
  s_skill_fire:
    number: 23
  s_shatz:
    number: 24
  s_trough_chamber:
    number: 28
  s_trough_6:
    number: 29
  s_trough_5:
    number: 2A
  s_trough_4:
    number: 2B
  s_trough_3:
    number: 2C
  s_trough_2:
    number: 2D
  s_trough_1:
    number: 2E
  s_huh_1:
    number: 2F

coils:
  c_pop_1:
    number: 00
    allow_enable: true
  c_pop_2:
    number: 01
    allow_enable: true
  c_pop_3:
    number: 02
    allow_enable: true
  c_drop_reset:
    number: 03
    hold_power: 1
    pulse_ms: 17
    allow_enable: true
  c_flipper_upper_right_main:
    number: 04
    allow_enable: true
    hold_power: 1
    pulse_ms: 20
  c_flipper_right_main:
    number: 10
    allow_enable: true
    hold_power: 1
    pulse_ms: 20
  c_flipper_left_main:
    number: 12
    allow_enable: true
    hold_power: 1
    pulse_ms: 20
  c_trough_load:
    number: 13
    allow_enable: true
  c_left_slingshot:
    number: 14
    allow_enable: true
  c_right_slingshot:
    number: 15
    allow_enable: true
  c_raptor_pit:
    number: 16
    pulse_ms: 20
    allow_enable: true
  c_trough_eject:
    number: 17
    allow_enable: true

autofire_coils:
  pop_1:
    coil: c_pop_1
    switch: s_pop_1
    enable_events: machine_reset_phase_3
  pop_2:
    coil: c_pop_2
    switch: s_pop_2
    enable_events: machine_reset_phase_3
  pop_3:
    coil: c_pop_3
    switch: s_pop_3
    enable_events: machine_reset_phase_3
  drop_reset:
    coil: c_drop_reset
    switch: s_thin_green
    enable_events: machine_reset_phase_3
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_sling
    enable_events: machine_reset_phase_3
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_sling
    enable_events: machine_reset_phase_3
  skill_shot_launch:
    coil: c_raptor_pit
    switch: s_skill_fire
    enable_events: machine_reset_phase_3
  load_ball:
    coil: c_trough_load
    switch: s_start
    enable_events: machine_reset_phase_3
  trough_eject:
    coil: c_trough_eject
    switch: s_trough_chamber
    enable_events: machine_reset_phase_3

flippers:
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
    eos_switch: s_right_flipper_eos
    debug: true
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
    eos_switch: s_left_flipper_eos
    debug: true
  upper_right_flipper:
    main_coil: c_flipper_upper_right_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
    eos_switch: s_upper_right_flipper_eos
    debug: true

displays:
  window:
    width: 1280
    height: 720
  dmd:
    width: 120
    height: 32

images:
  backglass_main:
    file: backglass_main_720.png

slides:
  attract_slide:
    widgets:
      - type: color_dmd
        x: 0
        y: 1088
        anchor_x: left
        anchor_y: top
        width: 720
        height: 192
      - type: image
        image:  backglass_main
        x: 0
        y: 0
        anchor_x: left
        anchor_y: top

slide_player:
  init_done: attract_slide

kivy_config:
  graphics:
    fbo: force-hardware
    fullscreen: auto
    rotation: 270


