#config_version=5

hardware:
  platform: fast
  driverboards: fast
  lights: fadecandy

fast:
  ports: /dev/ttyUSB1, /dev/ttyUSB2
  watchdog: 1500
  # net_buffer: 200
  firmware_updates:
    - type: net
      version: "1.05"
      file: "firmware/20180823_FP_Ver1_05.txt"

fadecandy:
  dithering: True

open_pixel_control:
  debug: False

config:
  - logging.yaml
  - machine.yaml
  - keyboard.yaml
  - bcp.yaml
  - assets.yaml
  - graphics.yaml
  - scriptlets.yaml
  - playfields.yaml
  - player_vars.yaml
  - machine_vars.yaml
  - named_colors.yaml
  - shot_profiles.yaml
  - modes.yaml
  - lights.yaml
  - switches.yaml
  - coils.yaml
  - autofire_coils.yaml
  - flippers.yaml
  - drop_targets.yaml
  - ball_devices.yaml
  - sequence_shots.yaml
  - sound_system.yaml
  - sounds.yaml
  - music.yaml

