#config_version=5

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: /dev/ttyUSB1, /dev/ttyUSB2

config:
  - machine.yaml
  - graphics.yaml
  - scriptlets.yaml
  - playfields.yaml
  - modes.yaml
  - lights.yaml
  - switches.yaml
  - coils.yaml
  - autofire_coils.yaml
  - flippers.yaml
  - ball_devices.yaml
  - shots.yaml
  - sequence_shots.yaml

