#config_version=5

drop_targets:
  drop_one:
    switch: s_drop_target_1
    reset_coil: c_drop_1_reset
    knockdown_coil: c_drop_1_down
    reset_events:
      - machine_reset_phase_3
      - cmd_reset_all_drops
      - cmd_drop_one_up
      - skillshot_drops_two_hit
    knockdown_events:
      - cmd_drop_all_drops
      - cmd_drop_one_down
  drop_two:
    switch: s_drop_target_2
    reset_coil: c_drop_2_reset
    knockdown_coil: c_drop_2_down
    reset_events:
      - machine_reset_phase_3
      - cmd_reset_all_drops
      - cmd_drop_two_up
      - skillshot_drops_three_hit
    knockdown_events:
      - cmd_drop_all_drops
      - cmd_drop_two_down
  drop_three:
    switch: s_drop_target_3
    reset_coil: c_drop_3_reset
    knockdown_coil: c_drop_3_down
    reset_events:
      - machine_reset_phase_3
      - cmd_reset_all_drops
      - cmd_drop_three_up
    knockdown_events:
      - cmd_drop_all_drops
      - cmd_drop_three_down
