#config_version=5

flippers:
  right_flipper:
    main_coil: c_flipper_right_main
    activation_switch: s_right_flipper
    #eos_switch: s_right_flipper_eos
    sw_flip_events: twitch_flip_right
    sw_release_events: twitch_unflip_right
  left_flipper:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    #eos_switch: s_left_flipper_eos
    sw_flip_events: twitch_flip_left
    sw_release_events: twitch_unflip_left
  upper_right_flipper:
    main_coil: c_flipper_upper_right_main
    activation_switch: s_upper_right_flipper
    #eos_switch: s_upper_right_flipper_eos
  left_sling_flipper:
    main_coil: c_upper_slingshot
    activation_switch: s_left_flipper
    disable_events: ball_will_end, service_mode_entered, left_sling_flipper_should_disable
    enable_events: left_sling_flipper_should_enable
    coil_overwrites:
      pulse_ms: 20