#config_version=5

displays:
  window:
    width: 720
    height: 1280
  backglass:
    width: 720
    height: 1280
  dmd:
    width: 128
    height: 32
    round_anchor_x: left
    round_anchor_y: bottom
    default: yes

window:
  source_display: window
  borderless: true
  exit_on_escape: true
  fullscreen: true
  no_window: false
  resizable: false
  show_cursor: false
  
slides:
  window_slide:
    - type: display
      source_display: dmd
      width: 640
      height: 160
      y: 120
      x: 370
      effects:
        - type: color_dmd
          dots_x: 128
          dots_y: 32
          dot_size: .75
          background_color: 000000ff
    - type: rectangle
      width: 648
      height: 168
      color: black
      y: 120
      x: 370
    - type: image
      image: backglass_main_logo
      y: 1088
    - type: display
      source_display: backglass
      width: 720
      height: 1280


  backglass_slide:
    widgets:
      - type: image
        image: backglass_main_symbol
        y: 780
      - type: image
        image: backglass_main_nebula

  dmd_slide:
    - type: text
      text: Booting...
      color: FF5000
    - type: line
      points: 0, 0, 127, 0, 127 31, 0, 31, 0, 0
      color: red
      thickness: 1
      cap: square
    - type: rectangle
      width: 128
      height: 32
      color: black

slide_player:
  init_done:
    window_slide:
      target: window
    backglass_slide:
      target: backglass
    dmd_slide:
      expire: 2s
      target: dmd

kivy_config:
  kivy:
    desktop: 0
    exit_on_escape: 1
    pause_on_minimize: 0
  graphics:
    borderless: 0
    window_state: visible  # visible, hidden, maximized, minimized
    fbo: hardware  # hardware, software, force-hardware
    fullscreen: 1
    width: 720
    maxfps: 30
    multisamples: 2
    position: auto  # auto, custom
    show_cursor: 0
    resizable: 0
    rotation: 0
    height: 1280
