#config_version=4

leds:
#left backbox
  led80:
    number: 80
  led81:
    number: 81
  led82:
    number: 82
  led83:
    number: 83
  led84:
    number: 84
  led85:
    number: 85
  led86:
    number: 86
  led87:
    number: 87
  led88:
    number: 88
  led89:
    number: 89
  led8A:
    number: 8A
  led8B:
    number: 8B
  led8C:
    number: 8C
  led8D:
    number: 8D
  led8E:
    number: 8E
  led8F:
    number: 8F
  led90:
    number: 90
  led91:
    number: 91
  led92:
    number: 92
  led93:
    number: 93
  led94:
    number: 94
  led95:
    number: 95
  led96:
    number: 96
  led97:
    number: 97
  led98:
    number: 98
  led99:
    number: 99
  led9A:
    number: 9A
  led9B:
    number: 9B
  led9C:
    number: 9C
  led9D:
    number: 9D
  led9E:
    number: 9E
  led9F:
    number: 9F
  ledA0:
    number: A0
  ledA1:
    number: A1
  ledA2:
    number: A2
  ledA3:
    number: A3
  ledA4:
    number: A4
  ledA5:
    number: A5
  ledA6:
    number: A6
  ledA7:
    number: A7
  ledA8:
    number: A8
  ledA9:
    number: A9
  ledAA:
    number: AA
  ledAB:
    number: AB
  ledAC:
    number: AC
  ledAD:
    number: AD
  ledAE:
    number: AE
  ledAF:
    number: AF
  ledB0:
    number: B0
  ledB1:
    number: B1

#right backbox
  ledC0:
    number: C0
  ledC1:
    number: C1
  ledC2:
    number: C2
  ledC3:
    number: C3
  ledC4:
    number: C4
  ledC5:
    number: C5
  ledC6:
    number: C6
  ledC7:
    number: C7
  ledC8:
    number: C8
  ledC9:
    number: C9
  ledCA:
    number: CA
  ledCB:
    number: CB
  ledCC:
    number: CC
  ledCD:
    number: CD
  ledCE:
    number: CE
  ledCF:
    number: CF
  ledD0:
    number: D0
  ledD1:
    number: D1
  ledD2:
    number: D2
  ledD3:
    number: D3
  ledD4:
    number: D4
  ledD5:
    number: D5
  ledD6:
    number: D6
  ledD7:
    number: D7
  ledD8:
    number: D8
  ledD9:
    number: D9
  ledDA:
    number: DA
  ledDB:
    number: DB
  ledDC:
    number: DC
  ledDD:
    number: DD
  ledDE:
    number: DE
  ledDF:
    number: DF
  ledE0:
    number: E0
  ledE1:
    number: E1
  ledE2:
    number: E2
  ledE3:
    number: E3
  ledE4:
    number: E4
  ledE5:
    number: E5
  ledE6:
    number: E6
  ledE7:
    number: E7
  ledE8:
    number: E8
  ledE9:
    number: E9
  ledEA:
    number: EA
  ledEB:
    number: EB
  ledEC:
    number: EC
  ledED:
    number: ED
  ledEE:
    number: EE
  ledEF:
    number: EF
  ledF0:
    number: F0
  ledF1:
    number: F1
    