#config_version=5

lights:
#gi-left
  gi_left_sling_top:
    number: 0
    type: grb
    platform: fadecandy
  gi_left_sling_bottom:
    number: 1
    type: grb
    platform: fadecandy
  gi_left_ball_guide:
    number: 2
    type: grb
    platform: fadecandy
  gi_behind_zero_suit:
    number: 3
    type: grb
    platform: fadecandy
  gi_missile_bank:
    number: 4
    type: grb
    platform: fadecandy
  gi_middle_sling:
    number: 5
    type: grb
    platform: fadecandy
  gi_side_bank:
    number: 6
    type: grb
    platform: fadecandy
  gi_back_left:
    number: 7
    type: grb
    platform: fadecandy
  gi_strip_1:
    number: 8
    type: grb
    platform: fadecandy
  gi_strip_2:
    number: 9
    type: grb
    platform: fadecandy
  gi_strip_3:
    number: 10
    type: grb
    platform: fadecandy
  gi_strip_4:
    number: 11
    type: grb
    platform: fadecandy
  gi_strip_5:
    number: 12
    type: grb
    platform: fadecandy
  gi_strip_6:
    number: 13
    type: grb
    platform: fadecandy
  gi_strip_7:
    number: 14
    type: grb
    platform: fadecandy
  gi_strip_8:
    number: 15
    type: grb
    platform: fadecandy
  gi_strip_9:
    number: 16
    type: grb
    platform: fadecandy
  gi_strip_10:
    number: 17
    type: grb
    platform: fadecandy

#gi-right
  gi_right_sling_top:
    number: 64
    type: grb
    platform: fadecandy
  gi_right_sling_bottom:
    number: 65
    type: grb
    platform: fadecandy
  gi_right_ball_guide:
    number: 66
    type: grb
    platform: fadecandy
  gi_bomb_bank:
    number: 67
    type: grb
    platform: fadecandy
  gi_upper_flipper_bottom:
    number: 68
    type: grb
    platform: fadecandy
  gi_upper_flipper_top:
    number: 69
    type: grb
    platform: fadecandy
  gi_upgrade_bank:
    number: 70
    type: grb
    platform: fadecandy
  gi_under_side_ramp:
    number: 71
    type: grb
    platform: fadecandy
  gi_back_center:
    number: 72
    type: grb
    platform: fadecandy
  gi_back_right:
    number: 73
    type: grb
    platform: fadecandy

#playfield-lower
  led_right_outlane:
    number: 128
    platform: fadecandy
    tags: reflective
  led_right_kickback:
    number: 129
    platform: fadecandy
    tags: reflective
  led_right_inlane:
    number: 130
    platform: fadecandy
    tags: reflective
  led_boss_phantoon:
    number: 131
    platform: fadecandy
    tags: reflective
  led_goal_4:
    number: 132
    platform: fadecandy
    tags: reflective
  led_goal_3:
    number: 133
    platform: fadecandy
    tags: reflective
  led_boss_kraid:
    number: 134
    platform: fadecandy
    tags: reflective
  led_motherbrain_3:
    number: 135
    platform: fadecandy
    tags: reflective
  led_motherbrain_2:
    number: 136
    platform: fadecandy
    tags: reflective
  led_motherbrain_1:
    number: 137
    platform: fadecandy
    tags: reflective
  led_boss_ridley:
    number: 138
    platform: fadecandy
    tags: reflective
  led_goal_2:
    number: 139
    platform: fadecandy
    tags: reflective
  led_ball_save:
    number: 140
    platform: fadecandy
    tags: reflective
  led_goal_1:
    number: 141
    platform: fadecandy
    tags: reflective
  led_boss_draygon:
    number: 142
    platform: fadecandy
    tags: reflective
  led_left_inlane:
    number: 143
    platform: fadecandy
    tags: reflective
  led_left_outlane:
    number: 144
    platform: fadecandy
    tags: reflective
  led_left_kickback:
    number: 145
    platform: fadecandy
    tags: reflective

#playfield-middle
  led_bomb_bank_3:
    number: 320
    platform: fadecandy
    tags: reflective
  led_bomb_bank_2:
    number: 321
    platform: fadecandy
    tags: reflective
  led_bomb_bank_1:
    number: 322
    platform: fadecandy
    tags: reflective
  led_rollover:
    number: 323
    platform: fadecandy
    tags: reflective
  led_3x:
    number: 324
    platform: fadecandy
    tags: reflective
  led_2x:
    number: 325
    platform: fadecandy
    tags: reflective
  led_scanner_center:
    number: 326
    platform: fadecandy
    tags: reflective
  led_scanner_nw:
    number: 327
    platform: fadecandy
    tags: reflective
  led_scanner_ne:
    number: 328
    platform: fadecandy
    tags: reflective
  led_scanner_e:
    number: 329
    platform: fadecandy
    tags: reflective
  led_scanner_se:
    number: 330
    platform: fadecandy
    tags: reflective
  led_scanner_sw:
    number: 331
    platform: fadecandy
    tags: reflective
  led_scanner_w:
    number: 332
    platform: fadecandy
    tags: reflective
  led_upgrade_bank_3:
    number: 333
    platform: fadecandy
    tags: reflective
  led_upgrade_bank_2:
    number: 334
    platform: fadecandy
    tags: reflective
  led_upgrade_bank_1:
    number: 335
    platform: fadecandy
    tags: reflective
  led_wall_jump:
    number: 336
    platform: fadecandy
    tags: reflective
  led_missile_bank_3:
    number: 337
    platform: fadecandy
    tags: reflective
  led_missile_bank_2:
    number: 338
    platform: fadecandy
    tags: reflective
  led_missile_bank_1:
    number: 339
    platform: fadecandy
    tags: reflective
  led_enter_secret_passage:
    number: 340
    platform: fadecandy
    tags: reflective
  led_zero_suit:
    number: 341
    platform: fadecandy
    tags: reflective

#playfield-upper
  led_upper_playfield_1:
    number: 384
    platform: fadecandy
    tags: reflective
  led_upper_playfield_2:
    number: 385
    platform: fadecandy
    tags: reflective
  led_upper_playfield_3:
    number: 386
    platform: fadecandy
    tags: reflective
  led_enter_side_ramp:
    number: 387
    platform: fadecandy
    tags: reflective
  led_drop_1:
    number: 388
    platform: fadecandy
    tags: reflective
  led_drop_2:
    number: 389
    platform: fadecandy
    tags: reflective
  led_drop_3:
    number: 390
    platform: fadecandy
    tags: reflective
  led_enter_right_orbit:
    number: 391
    platform: fadecandy
    tags: reflective
  led_thin_orange:
    number: 392
    platform: fadecandy
    tags: reflective
  led_captive_ball:
    number: 393
    platform: fadecandy
    tags: reflective
  led_pop_1:
    number: 394
    platform: fadecandy
    tags: reflective
  led_pop_2:
    number: 395
    platform: fadecandy
    tags: reflective
  led_pop_3:
    number: 396
    platform: fadecandy
    tags: reflective
  led_pit:
    number: 397
    platform: fadecandy
    tags: reflective
  led_enter_ramp:
    number: 398
    platform: fadecandy
    tags: reflective
  led_enter_scoop:
    number: 399
    platform: fadecandy
    tags: reflective
  led_enter_left_orbit:
    number: 400
    platform: fadecandy
    tags: reflective
  led_side_3:
    number: 401
    platform: fadecandy
    tags: reflective
  led_side_2:
    number: 402
    platform: fadecandy
    tags: reflective
  led_side_1:
    number: 403
    platform: fadecandy
    tags: reflective

#left backbox
  led80:
    number: 2-0
    type: grb
  led81:
    number: 2-1
    type: grb
  led82:
    number: 2-2
    type: grb
  led83:
    number: 2-3
    type: grb
  led84:
    number: 2-4
    type: grb
  led85:
    number: 2-5
    type: grb
  led86:
    number: 2-6
    type: grb
  led87:
    number: 2-7
    type: grb
  led88:
    number: 2-8
    type: grb
  led89:
    number: 2-9
    type: grb
  led8A:
    number: 2-10
    type: grb
  led8B:
    number: 2-11
    type: grb
  led8C:
    number: 2-12
    type: grb
  led8D:
    number: 2-13
    type: grb
  led8E:
    number: 2-14
    type: grb
  led8F:
    number: 2-15
    type: grb
  led90:
    number: 2-16
    type: grb
  led91:
    number: 2-17
    type: grb
  led92:
    number: 2-18
    type: grb
  led93:
    number: 2-19
    type: grb
  led94:
    number: 2-20
    type: grb
  led95:
    number: 2-21
    type: grb
  led96:
    number: 2-22
    type: grb
  led97:
    number: 2-23
    type: grb
  led98:
    number: 2-24
    type: grb
  led99:
    number: 2-25
    type: grb
  led9A:
    number: 2-26
    type: grb
  led9B:
    number: 2-27
    type: grb
  led9C:
    number: 2-28
    type: grb
  led9D:
    number: 2-29
    type: grb
  led9E:
    number: 2-30
    type: grb
  led9F:
    number: 2-31
    type: grb
  ledA0:
    number: 2-32
    type: grb
  ledA1:
    number: 2-33
    type: grb
  ledA2:
    number: 2-34
    type: grb
  ledA3:
    number: 2-35
    type: grb
  ledA4:
    number: 2-36
    type: grb
  ledA5:
    number: 2-37
    type: grb
  ledA6:
    number: 2-38
    type: grb
  ledA7:
    number: 2-39
    type: grb
  ledA8:
    number: 2-40
    type: grb
  ledA9:
    number: 2-41
    type: grb
  ledAA:
    number: 2-42
    type: grb
  ledAB:
    number: 2-43
    type: grb
  ledAC:
    number: 2-44
    type: grb
  ledAD:
    number: 2-45
    type: grb
  ledAE:
    number: 2-46
    type: grb
  ledAF:
    number: 2-47
    type: grb
  ledB0:
    number: 2-48
    type: grb
  ledB1:
    number: 2-49
    type: grb

#right backbox
  ledC0:
    number: 3-0
    type: grb
  ledC1:
    number: 3-1
    type: grb
  ledC2:
    number: 3-2
    type: grb
  ledC3:
    number: 3-3
    type: grb
  ledC4:
    number: 3-4
    type: grb
  ledC5:
    number: 3-5
    type: grb
  ledC6:
    number: 3-6
    type: grb
  ledC7:
    number: 3-7
    type: grb
  ledC8:
    number: 3-8
    type: grb
  ledC9:
    number: 3-9
    type: grb
  ledCA:
    number: 3-10
    type: grb
  ledCB:
    number: 3-11
    type: grb
  ledCC:
    number: 3-12
    type: grb
  ledCD:
    number: 3-13
    type: grb
  ledCE:
    number: 3-14
    type: grb
  ledCF:
    number: 3-15
    type: grb
  ledD0:
    number: 3-16
    type: grb
  ledD1:
    number: 3-17
    type: grb
  ledD2:
    number: 3-18
    type: grb
  ledD3:
    number: 3-19
    type: grb
  ledD4:
    number: 3-20
    type: grb
  ledD5:
    number: 3-21
    type: grb
  ledD6:
    number: 3-22
    type: grb
  ledD7:
    number: 3-23
    type: grb
  ledD8:
    number: 3-24
    type: grb
  ledD9:
    number: 3-25
    type: grb
  ledDA:
    number: 3-26
    type: grb
  ledDB:
    number: 3-27
    type: grb
  ledDC:
    number: 3-28
    type: grb
  ledDD:
    number: 3-29
    type: grb
  ledDE:
    number: 3-30
    type: grb
  ledDF:
    number: 3-31
    type: grb
  ledE0:
    number: 3-32
    type: grb
  ledE1:
    number: 3-33
    type: grb
  ledE2:
    number: 3-34
    type: grb
  ledE3:
    number: 3-35
    type: grb
  ledE4:
    number: 3-36
    type: grb
  ledE5:
    number: 3-37
    type: grb
  ledE6:
    number: 3-38
    type: grb
  ledE7:
    number: 3-39
    type: grb
  ledE8:
    number: 3-40
    type: grb
  ledE9:
    number: 3-41
    type: grb
  ledEA:
    number: 3-42
    type: grb
  ledEB:
    number: 3-43
    type: grb
  ledEC:
    number: 3-44
    type: grb
  ledED:
    number: 3-45
    type: grb
  ledEE:
    number: 3-46
    type: grb
  ledEF:
    number: 3-47
    type: grb
  ledF0:
    number: 3-48
    type: grb
  ledF1:
    number: 3-49
    type: grb
