#config_version=5

machine_vars:
  bao_balls_locked:
    initial_value: 0
    value_type: int
    persist: False
  metroid_game_booted:
    initial_value: 0
    value_type: int
  next_game_acapella:
    initial_value: 0
    value_type: int
    persist: False
  next_game_bao:
    initial_value: 0
    value_type: int
    persist: False
  next_game_goren:
    initial_value: 0
    value_type: int
    persist: False
  next_game_macho:
    initial_value: 0
    value_type: int
    persist: False
  twitch_last_bits_user:
    initial_value: Goren1818
    value_type: str
  twitch_last_bits_amount:
    initial_value: 237
  twitch_last_chat_message:
    initial_value: Yarrrrrr!
    value_type: str
  twitch_last_chat_message_line_1:
    initial_value: Yarrrrrr!
    value_type: str
  twitch_last_chat_message_line_2:
    initial_value: []
    value_type: str
  twitch_last_chat_message_line_3:
    initial_value: []
    value_type: str
  twitch_last_chat_message_line_4:
    initial_value: []
    value_type: str
  twitch_last_chat_message_line_5:
    initial_value: []
    value_type: str
  twitch_last_chat_message_line_6:
    initial_value: []
    value_type: str
  twitch_last_chat_message_line_count:
    initial_value: 0
  twitch_last_chat_user:
    initial_value: TheArrrrrcade
    value_type: str

