#config_version=5

modes:
  - base
  - bonus
  - chozo_multiball
  - drop_targets
  - emergency_landing
  - high_score
  - lanes
  - left_targets
  - match
  - missiles
  - pop_bumpers
  - power_bombs
  - room_1b_gunship
  - room_1b_gunship_victory
  - room_1l_entryway
  - room_1r_space_pirate_battle
  - room_2a_shifting_sands
  - room_2e_sandy_cavern
  - room_2i_lava_jump
  - select_landing_site
  - side_targets
  - skillshot
  - skillshot_bombs
  - skillshot_drops
  - skillshot_drops_release
  - skillshot_missiles
  - skillshot_purple
  - skillshot_unskilled
  - spin_jumps
  - twitch_bits_multiball
  - upper_lanes

