#config_version=5

modes:
  - base
  - bonus
  - chozo_multiball
  - high_score
  - lanes
  - match
  - missiles
  - pop_bumpers
  - power_bombs
  - room_1b_gunship
  - room_1b_gunship_victory
  - spin_jumps
  - twitch_bits_multiball

