#config_version=5

modes:
  - back_ramp
  - bao_base
  - bao_lanes
  - base
  - bonus
  - boss
  - bridge
  - chozo_multiball
  - drop_targets
  - emergency_landing
  - gorens_lament
#  - high_jump
  - high_score
  - lanes
  - map
  - match
  - miniboss
  - missiles
  - pop_bumpers
  - power_bombs
  - room_1a_lush_cavern
  - room_1b_gunship
  - room_1b_gunship_victory
  - room_1c_plains
  - room_1d_the_lake
  - room_1e_statue_room
  - room_1f_mushroom_chamber
  - room_1g_the_pit
  - room_1h_teleporters
  - room_1i_computing
  - room_1j_phantoon
  - room_1k_crew_quarters
  - room_1l_entryway
  - room_1m_generator
  - room_1n_the_hull
  - room_1o_artillery
  - room_1p_cargo_bay
  - room_1q_impact_zone
  - room_1r_space_pirate_battle
  - room_1s_blighted_canopy
  - room_1t_spiny_corridor
  - room_1u_the_armory
  - room_1v_fireflea
  - room_1w_biosphere
  - room_1x_kraid
  - room_1y_subterranean_isle
  - room_1z_underground_desert
  - room_2a_shifting_sands
  - room_2b_crevasse
  - room_2c_central_pumping
  - room_2d_abyss
  - room_2e_sandy_cavern
  - room_2f_frozen_lake
  - room_2g_draygon
  - room_2h_crystalline_seabed
  - room_2i_lava_jump
  - room_2j_lake_of_fire
  - room_2k_larvae_nest
  - room_2l_west_hot_springs
  - room_2m_geothermal_plant
  - room_2n_magma_chamber
  - room_2o_strange_ruins
  - room_2p_east_hot_springs
  - room_2q_ridley
  - select_landing_site
  - side_targets
  - skillshot
  - skillshot_big_points
  - skillshot_bombs
  - skillshot_drops
  - skillshot_drops_release
  - skillshot_missiles
  - skillshot_purple
  - skillshot_side_targets
  - skillshot_unskilled
  - spin_jumps
  - tilt
  - twitch_bits_multiball
  - upper_lanes
  - wall_jump
  - zero_suit_multiball
