#config_version=5

sounds:
  music_crateria:
    file: music_crateria.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_crateria_central:
    file: music_crateria_central.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_crateria_edge:
    file: music_crateria_edge.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_crateria_quiet:
    file: music_crateria_quiet.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_brinstar_side_entrance:
    file: music_brinstar_side_entrance.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_boss:
    file: music_boss.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_brinstar:
    file: music_brinstar.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_brinstar_calm:
    file: music_brinstar_calm.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_high_score:
    file: music_high_score.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_multiball:
    file: music_multiball.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_norfair:
    file: music_norfair.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_norfair_calm:
    file: music_norfair_calm.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_norfair_deep:
    file: music_norfair_deep.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_norfair_deep_intro:
    file: music_norfair_deep_intro.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_maridia:
    file: music_maridia.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_maridia_intro:
    file: music_maridia_intro.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    volume: 0.4
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_maridia_snow:
    file: music_maridia_snow.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    volume: 0.4
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_wrecked_ship:
    file: music_wrecked_ship.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_wrecked_ship_calm:
    file: music_wrecked_ship_calm.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_wrecked_ship_generator:
    file: music_wrecked_ship_generator.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_item_room:
    file: music_item_room.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_metal_item_room:
    file: music_metal_item_room.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_bao_main:
    file: music_bao_main.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_bao_multiball:
    file: music_bao_multiball.wav
    #streaming: True
    volume: 0.7
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_bao_reactor:
    file: music_bao_reactor.wav
    #streaming: True
    volume: 0.7
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_bao_critical:
    file: music_bao_critical.wav
    #streaming: True
    volume: 0.7
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
