#config_version=5

sounds:
  music_crateria:
    file: music_crateria.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_brinstar:
    file: music_brinstar.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_norfair:
    file: music_norfair.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_maridia:
    file: music_maridia.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
  music_wrecked_ship:
    file: music_wrecked_ship.wav
    #streaming: True
    track: music
    priority: 50
    #max_queue_time: 1s
    loops: -1
    simultaneous_limit: 1
    stealing_method: skip
