#config_version=5

named_colors:
  door_blue: '6969ff'
  door_green: '69ff69'
  door_red: 'ff6969'
  door_yellow: 'ffff69'
  door_closed: '808080'
  dmd_orange: 'E67300'
  dmd_blue: '009cff'
  drop_target_can_hit: '96ff00'
  drop_target_cannot_hit: '00FFFF'

