#config_version=5

player_vars:
  ramps:
    initial_value: 0
  orbits:
    initial_value: 0
  pops:
    initial_value: 0
  slingshots:
    initial_value: 0
  lanes:
    initial_value: 0
  spinners:
    initial_value: 0
  missiles:
    initial_value: 0
