#config_version=5

player_vars:
  capsides:
    initial_value: 0
  captive_ball_counter_value:
    initial_value: 6
  captives:
    initial_value: 0
  chozo_multiballs:
    initial_value: 0
  continue_room:
    value_type: str
    initial_value: 1b
  has_chosen_landing_site:
    initial_value: 0
  lanes:
    initial_value: 0
  missiles:
    initial_value: 0
  room_1b_step_1a:
    initial_value: 0
  room_1b_step_1b:
    initial_value: 0
  room_1b_step_2:
    initial_value: 0
  room_1b_victory_scan_percent:
    initial_value: 0
  room_1b_victory_step_1:
    initial_value: 0
  switches:
    initial_value: 0
  orbits:
    initial_value: 0
  pops:
    initial_value: 0
  ramps:
    initial_value: 0
  scoops:
    initial_value: 0
  slingshots:
    initial_value: 0
  spinners:
    initial_value: 0
