#config_version=5

player_vars:
  area_bonus_nw:
    initial_value: 0
  area_bonus_ne:
    initial_value: 0
  area_bonus_e:
    initial_value: 0
  area_bonus_se:
    initial_value: 0
  area_bonus_sw:
    initial_value: 0
  area_bonus_w:
    initial_value: 0
  bao_reactors:
    initial_value: 0
  boss_kraid_hp:
    initial_value: 240
  boss_kraid_multiball_played:
    initial_value: 0
  boss_ridley_hp:
    initial_value: 200
  boss_ridley_multiball_played:
    initial_value: 0
  bridge_bonus:
    initial_value: 0
  bridges:
    initial_value: 0
  capsides:
    initial_value: 0
  captive_ball_counter_value:
    initial_value: 6
  captives:
    initial_value: 0
  chozo_multiballs:
    initial_value: 0
  chozo_multiball_last_jackpot_score:
    initial_value: 0
  continue_room:
    value_type: str
    initial_value: 1b
  crateria_shot_bonus:
    initial_value: 0
  crateria_landed:
    initial_value: 0
  door_1a_1f:
    initial_value: 0
  door_2d_2e:
    initial_value: 0
  door_2e_2f:
    initial_value: 0
  drops:
    initial_value: 0
  drops_1d:
    value_type: str
    initial_value: 'DDD'
  drops_1g:
    value_type: str
    initial_value: 'DDD'
  drops_1m:
    value_type: str
    initial_value: 'DDD'
  drops_1t:
    value_type: str
    initial_value: 'DDD'
  drops_1v:
    value_type: str
    initial_value: 'DDU'
  drops_1z:
    value_type: str
    initial_value: 'UDU'
  drops_2a:
    value_type: str
    initial_value: 'UDD'
  drops_2b:
    value_type: str
    initial_value: 'DDD'
  drops_2d:
    value_type: str
    initial_value: 'DUD'
  drops_2i:
    value_type: str
    initial_value: 'DDU'
  drops_2m:
    value_type: str
    initial_value: 'DDD'
  emergency_landings:
    initial_value: 0
  has_chosen_landing_site:
    initial_value: 0
  high_jump_bonus:
    initial_value: 0
  kickbacks:
    initial_value: 0
  kickback_active:
    initial_value: 0
  lanes:
    initial_value: 0
  lanes_last_shot:
    initial_value: 0
  last_continue_room:
    value_type: str
    initial_value: ''
  map_location:
    value_type: str
    initial_value: '1b'
  map_visited_b:
    value_type: str
    initial_value: 'NNNNNNNNNN'
  map_visited_c:
    value_type: str
    initial_value: 'NNNNNNNNNN'
  map_visited_m:
    value_type: str
    initial_value: 'NNNNNNNNNN'
  map_visited_n:
    value_type: str
    initial_value: 'NNNNNNNNNN'
  map_visited_t:
    value_type: str
    initial_value: 'NNNNNNNNNN'
  map_visited_w:
    value_type: str
    initial_value: 'NNNNNNNNNN'
  miniboss_special_score:
    initial_value: 0
  missiles:
    initial_value: 0
  multiplier:
    initial_value: 1
  orbits:
    initial_value: 0
  pops:
    initial_value: 0
  power_bombs:
    initial_value: 0
  ramps:
    initial_value: 0
  room_1a_multiplier:
    initial_value: 1
  room_1b_step_1a:
    initial_value: 0
  room_1b_step_1b:
    initial_value: 0
  room_1b_step_2:
    initial_value: 0
  room_1b_victory_scan_percent:
    initial_value: 0
  room_1b_victory_step_1:
    initial_value: 0
  room_1d_shots_hit:
    initial_value: 0
  room_1m_captured:
    initial_value: 0
  room_1s_jackpot:
    initial_value: 0
  room_special_score:
    initial_value: 0
  wrecked_ship_charge:
    initial_value: 0
  room_1r_finished:
    initial_value: 0
  room_2a_alive_score:
    initial_value: 0
  room_2a_seconds_survived:
    initial_value: 0
  room_2f_target_order:
    value_type: str
    initial_value: 'ABCDEFGHIJKLMN'
  room_2k_insects:
    initial_value: 0
  room_2m_jackpot_value:
    initial_value: 88000
  rooms_visited:
    initial_value: 0
  rooms_completed:
    initial_value: 0
  scoops:
    initial_value: 0
  skillshot_bombs_lit:
    initial_value: 0
  skillshot_missiles_lit:
    initial_value: 0
  skillshot_purple_lit:
    initial_value: 0
  slingshots:
    initial_value: 0
  spinners:
    initial_value: 0
  super_missiles:
    initial_value: 0
  switches:
    initial_value: 0
  wrecked_ship_powered_up:
    initial_value: 0
