#config_version=5

player_vars:
  area_bonus_nw:
    initial_value: 0
  area_bonus_ne:
    initial_value: 0
  area_bonus_e:
    initial_value: 0
  area_bonus_se:
    initial_value: 0
  area_bonus_sw:
    initial_value: 0
  area_bonus_w:
    initial_value: 0
  bao_reactors:
    initial_value: 0
  bridge_bonus:
    initial_value: 0
  bridges:
    initial_value: 0
  capsides:
    initial_value: 0
  captive_ball_counter_value:
    initial_value: 6
  captives:
    initial_value: 0
  chozo_multiballs:
    initial_value: 0
  continue_room:
    value_type: str
    initial_value: 1b
  crateria_shot_bonus:
    initial_value: 0
  door_2d_2e:
    initial_value: 0
  door_2e_2f:
    initial_value: 0
  drops:
    initial_value: 0
  drops_1z:
    value_type: str
    initial_value: 'UDU'
  drops_2a:
    value_type: str
    initial_value: 'UDD'
  drops_2b:
    value_type: str
    initial_value: 'DDD'
  drops_2d:
    value_type: str
    initial_value: 'DUD'
  drops_2i:
    value_type: str
    initial_value: 'DDU'
  drops_2m:
    value_type: str
    initial_value: 'DDD'
  emergency_landings:
    initial_value: 0
  has_chosen_landing_site:
    initial_value: 0
  high_jump_bonus:
    initial_value: 0
  kickbacks:
    initial_value: 0
  kickback_active:
    initial_value: 0
  lanes:
    initial_value: 0
  lanes_last_shot:
    initial_value: 0
  missiles:
    initial_value: 0
  multiplier:
    initial_value: 1
  orbits:
    initial_value: 0
  pops:
    initial_value: 0
  power_bombs:
    initial_value: 0
  ramps:
    initial_value: 0
  door_1a_1f:
    initial_value: 0
  room_1b_step_1a:
    initial_value: 0
  room_1b_step_1b:
    initial_value: 0
  room_1b_step_2:
    initial_value: 0
  room_1b_victory_scan_percent:
    initial_value: 0
  room_1b_victory_step_1:
    initial_value: 0
  room_2a_alive_score:
    initial_value: 0
  room_2f_target_order:
    value_type: str
    initial_value: 'ABCDEFGHIJKLMN'
  scoops:
    initial_value: 0
  skillshot_bombs_lit:
    initial_value: 0
  skillshot_missiles_lit:
    initial_value: 0
  skillshot_purple_lit:
    initial_value: 0
  slingshots:
    initial_value: 0
  spinners:
    initial_value: 0
  super_missiles:
    initial_value: 0
  switches:
    initial_value: 0
