#config_version=5

shot_profiles:
  exit_door:
    states:
    - name: lit
      show: led_color
      loops: -1
  exit_door_optimum:
    states:
    - name: lit
      show: door_optimum
      loops: -1
