#config_version=5

sound_system:
  buffer: 1024
  channels: 2
  enabled: True
  frequency: 44100
  master_volume: 0.75
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: 0.25
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.4
