#config_version=5

sounds:
  ball_1_locked:
    file: ball_one_locked.flac
    streaming: False
    track: voice
    volume: -4.5 db
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: -18db
      release_point: 2.0 sec
      release: 1.0 sec
  crateria:
    file: crateria.flac
    streaming: False
    track: voice
    volume: -4.5 db
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: -18db
      release_point: 2.0 sec
      release: 1.0 sec
  norfair:
    file: norfair.flac
    streaming: False
    track: voice
    volume: -4.5 db
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: -18db
      release_point: 2.0 sec
      release: 1.0 sec
  torvus_bog:
    file: crateria.flac
    streaming: False
    track: voice
    volume: -4.5 db
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: -18db
      release_point: 2.0 sec
      release: 1.0 sec
