#config_version=5

sounds:
  ball_1_locked:
    file: ball_one_locked.ogg
    streaming: False
    track: voice
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 2.0 sec
      release: 1.0 sec
  crateria:
    file: crateria.ogg
    streaming: False
    track: voice
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 2.0 sec
      release: 1.0 sec
  jackpot_mother_fuckers:
    file: jackpot_mother_fuckers.ogg
    streaming: False
    track: voice
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 2.0 sec
      release: 1.0 sec
  harmony_metroid:
    file: harmony_metroid.ogg
    streaming: False
    track: voice
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 2.0 sec
      release: 1.0 sec
  norfair:
    file: norfair.ogg
    streaming: False
    track: voice
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 2.0 sec
      release: 1.0 sec
  torvus_bog:
    file: crateria.ogg
    streaming: False
    track: voice
    priority: 50
    max_queue_time: None
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 2.0 sec
      release: 1.0 sec
