#config_version=5

switches:
  s_right_flipper:
    number: 0
  s_left_flipper:
    number: 1
  s_start:
    number: 2
    tags: start
  s_pop_1:
    number: 3
    tags: playfield_active
  s_pop_2:
    number: 4
    tags: playfield_active
  s_pop_3:
    number: 5
    tags: playfield_active
  s_drop_target_1:
    number: 6
  s_thin_green:
    number: 7
    tags: playfield_active
  s_upper_right_flipper_eos:
    number: 8
  s_captive_ball:
    number: 9
    tags: playfield_active
  s_spinner:
    number: A
    tags: playfield_active
  s_left_target_1:
    number: B
    tags: playfield_active
  s_left_target_2:
    number: C
    tags: playfield_active
  s_scoop:
    number: D
    tags: playfield_active
    type: NC
  s_drop_target_2:
    number: E
  s_drop_target_3:
    number: F
  s_lower_right_bank_1:
    number: 10
    tags: playfield_active
  s_lower_right_bank_2:
    number: 11
    tags: playfield_active
  s_lower_right_bank_3:
    number: 12
    tags: playfield_active
  s_shooter_lane:
    number: 13
  s_right_outlane:
    number: 14
    tags: playfield_active
  s_right_inlane:
    number: 15
    tags: playfield_active
  s_rollover_button:
    number: 16
    tags: playfield_active
  s_removed_upper_flipper_rubber:
    number: 17
  s_right_flipper_eos:
    number: 18
  s_left_flipper_eos:
    number: 19
  s_left_sling:
    number: 1A
    tags: playfield_active
  s_right_sling:
    number: 1B
    tags: playfield_active
  s_left_inlane:
    number: 1C
    tags: playfield_active
  s_left_outlane:
    number: 1D
    tags: playfield_active
  s_trough_jam:
    number: 1E
    type: NC
  s_unknown_1f:
    number: 1F
  s_skill_bank_1:
    number: 20
    tags: playfield_active
  s_skill_bank_2:
    number: 21
    tags: playfield_active
  s_skill_bank_3:
    number: 22
    tags: playfield_active
  s_upper_sling:
    number: 23
    tags: playfield_active
  s_shatz:
    number: 24
    tags: playfield_active
  s_unknown_25:
    number: 25
  s_unknown_26:
    number: 26
  s_unknown_27:
    number: 27
  s_trough_2:
    number: 28
  s_trough_8:
    number: 29
  s_trough_7:
    number: 2A
  s_trough_6:
    number: 2B
  s_trough_5:
    number: 2C
  s_trough_4:
    number: 2D
  s_trough_3:
    number: 2E
  s_trough_1:
    number: 2F
    type: NC
  s_vuk:
    number: 30
  s_pop_sling:
    number: 31
  s_big_red:
    number: 32
  s_purple_1:
    number: 33
  s_purple_2:
    number: 34
  s_purple_3:
    number: 35
  s_orbit_r:
    number: 36
  s_orbit_l:
    number: 37
  s_ramp_enter:
    number: 38
  s_left_passage:
    number: 39
  s_behind_drop_1:
    number: 3A
    type: NC
  s_behind_drop_2:
    number: 3B
    type: NC
  s_behind_drop_3:
    number: 3C
    type: NC
  s_side_ramp_made:
    number: 3D
    type: NC

