#config_version=5

switches:
  s_right_flipper:
    number: 0-0
  s_left_flipper:
    number: 0-1
  s_start:
    number: 0-2
    tags: start
  s_pop_1:
    number: 0-3
    tags: playfield_active
  s_pop_2:
    number: 0-4
    tags: playfield_active
  s_pop_3:
    number: 0-5
    tags: playfield_active
  s_drop_target_1:
    number: 0-6
  s_thin_green:
    number: 0-7
    tags: playfield_active
  s_upper_right_flipper_eos:
    number: 0-8
  s_captive_ball:
    number: 0-9
    tags: playfield_active
  s_spinner:
    number: 0-10
    platform_settings:
      debounce_close: 20
      debounce_open: 20
    tags: playfield_active
  s_left_target_1:
    number: 0-11
    tags: playfield_active
  s_left_target_2:
    number: 0-12
    tags: playfield_active
  s_scoop:
    number: 0-13
    tags: playfield_active
    type: NC
  s_drop_target_2:
    number: 0-14
  s_drop_target_3:
    number: 0-15
  s_lower_right_bank_1:
    number: 1-0
    tags: playfield_active
  s_lower_right_bank_2:
    number: 1-1
    tags: playfield_active
  s_lower_right_bank_3:
    number: 1-2
    tags: playfield_active
  s_shooter_lane:
    number: 1-3
  s_right_outlane:
    number: 1-4
    tags: playfield_active
  s_right_inlane:
    number: 1-5
    tags: playfield_active
  s_rollover_button:
    number: 1-6
    tags: playfield_active
  s_removed_upper_flipper_rubber:
    number: 1-7
  s_right_flipper_eos:
    number: 1-8
  s_left_flipper_eos:
    number: 1-9
  s_left_sling:
    number: 1-10
    tags: playfield_active
  s_right_sling:
    number: 1-11
    tags: playfield_active
  s_left_inlane:
    number: 1-12
    tags: playfield_active
  s_left_outlane:
    number: 1-13
    tags: playfield_active
  s_trough_jam:
    number: 1-14
    type: NC
  s_unknown_1f:
    number: 1-15
  s_skill_bank_1:
    number: 1-16
    tags: playfield_active
  s_skill_bank_2:
    number: 1-17
    tags: playfield_active
  s_skill_bank_3:
    number: 1-18
    tags: playfield_active
  s_upper_sling:
    number: 1-19
    tags: playfield_active
  s_shatz:
    number: 1-20
    tags: playfield_active
  s_unknown_25:
    number: 1-21
  s_unknown_26:
    number: 1-22
  s_unknown_27:
    number: 1-23
  s_trough_2:
    number: 1-24
  s_trough_8:
    number: 1-25
  s_trough_7:
    number: 1-26
  s_trough_6:
    number: 1-27
  s_trough_5:
    number: 1-28
  s_trough_4:
    number: 1-29
  s_trough_3:
    number: 1-30
  s_trough_1:
    number: 1-31
    type: NC
  s_vuk:
    number: 2-0
  s_pop_sling:
    number: 2-1
  s_big_red:
    number: 2-2
  s_purple_1:
    number: 2-3
  s_purple_2:
    number: 2-4
  s_purple_3:
    number: 2-5
  s_orbit_r:
    number: 2-6
  s_orbit_l:
    number: 2-7
  s_ramp_enter:
    number: 2-8
  s_left_passage:
    number: 2-9
  s_behind_drop_1:
    number: 2-10
    type: NC
  s_behind_drop_2:
    number: 2-11
    type: NC
  s_behind_drop_3:
    number: 2-12
    type: NC
  s_side_ramp_made:
    number: 2-13
    type: NC

