#config_version=5
mode:
    start_events: select_landing_site_norfair_selected, room_2i_continue
    stop_events: game_ending, ball_ending
    # restart_on_next_ball: true
    priority: 300

animations:
  room_2i_backglass_scroll_up:
    - property: y
      value: 1280
      relative: true
      duration: 5s
    - property: y
      value: -1280
      relative: true
      duration: 0s
      repeat: true
  room_2i_backglass_scroll_down:
    - property: y
      value: -1280
      relative: true
      duration: 5s
    - property: y
      value: 1280
      relative: true
      duration: 0s
      repeat: true

slides:
  room_2i_backglass_slide:
    widgets:
      - type: image
        image: room_2i_lava_jump_backglass
        opacity: 0.75
        y: -1
        anchor_y: top
        animations:
          show_slide: room_2i_backglass_scroll_up
      - type: image
        image: room_2i_lava_jump_backglass
        opacity: 0.75
        y: 1279
        anchor_y: top
        animations:
          show_slide: room_2i_backglass_scroll_up
      - type: image
        image: room_2i_lava_jump_backglass
        y: 1280
        anchor_y: bottom
        animations:
          show_slide: room_2i_backglass_scroll_down
      - type: image
        image: room_2i_lava_jump_backglass
        y: 0
        anchor_y: bottom
        animations:
          show_slide: room_2i_backglass_scroll_down
    transition: fade
    transition_out: fade
  room_2i_splash_slide:
    widgets:
      - type: image
        image: room_2i_splash_title
      - type: image
        image: room_2i_splash_background
        fps: 17

slide_player:
  mode_room_2i_lava_jump_started:
    room_2i_backglass_slide:
      target: backglass
    room_2i_splash_slide:
      target: dmd
      expire: 1.5s

variable_player:
  mode_room_2i_lava_jump_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2i
      action: set

