#config_version=5
mode:
  start_events: select_landing_site_norfair_selected, room_2i_continue
  stop_events: game_ending, ball_ending
  priority: 300

timers:
  lava_jump_shot_timer:
    start_value: 1
    end_value: 4
    restart_on_complete: true
    tick_interval: 10s
    control_events:
      - event: mode_room_2i_lava_jump_started
        action: start

shots:
  lava_jump_first_shot:
    switch: s_left_passage
    enable_events:
      - timer_lava_jump_shot_timer_tick{ticks==1}
    disable_events:
      - timer_lava_jump_shot_timer_tick{ticks==2}
  lava_jump_second_shot:
    switch: s_orbit_l
    enable_events:
      - timer_lava_jump_shot_timer_tick{ticks==2}
    disable_events:
      - timer_lava_jump_shot_timer_tick{ticks==3}
  lava_jump_third_shot:
    switch: s_ramp_enter
    enable_events:
      - timer_lava_jump_shot_timer_tick{ticks==3}
    disable_events:
      - timer_lava_jump_shot_timer_tick{ticks==4}
  lava_jump_fourth_shot:
    switch: s_orbit_r
    enable_events:
      - timer_lava_jump_shot_timer_tick{ticks==4}
    disable_events:
      - timer_lava_jump_shot_timer_tick{ticks==1}

animations:
  room_2i_backglass_scroll_up:
    - property: y
      value: 1280
      relative: true
      duration: 5s
    - property: y
      value: -1280
      relative: true
      duration: 0s
      repeat: true
  room_2i_backglass_scroll_down:
    - property: y
      value: -1280
      relative: true
      duration: 5s
    - property: y
      value: 1280
      relative: true
      duration: 0s
      repeat: true

slides:
  room_2i_backglass_slide:
    widgets:
      - type: image
        image: room_2i_lava_jump_backglass
        opacity: 0.5
        y: -1
        anchor_y: top
        animations:
          show_slide: room_2i_backglass_scroll_up
      - type: image
        image: room_2i_lava_jump_backglass
        opacity: 0.5
        y: 1279
        anchor_y: top
        animations:
          show_slide: room_2i_backglass_scroll_up
      - type: image
        image: room_2i_lava_jump_backglass
        y: 1280
        anchor_y: bottom
        animations:
          show_slide: room_2i_backglass_scroll_down
      - type: image
        image: room_2i_lava_jump_backglass
        y: 0
        anchor_y: bottom
        animations:
          show_slide: room_2i_backglass_scroll_down
    transition: fade
    transition_out: fade
  room_2i_splash_slide:
    widgets:
      - type: image
        image: room_2i_splash_title
      - type: image
        image: room_2i_splash_background
        fps: 17

slide_player:
  mode_room_2i_lava_jump_started:
    room_2i_backglass_slide:
      target: backglass
    room_2i_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  timer_lava_jump_shot_timer_tick{ticks==1}:
    room_2i_shot_4_blink:
      action: stop
    blink_light:
      key: room_2i_shot_1_blink
      loops: -1
      show_tokens:
        led: led_enter_secret_passage
        color: 8F0000
  timer_lava_jump_shot_timer_tick{ticks==2}:
    room_2i_shot_1_blink:
      action: stop
    blink_light:
      key: room_2i_shot_2_blink
      loops: -1
      show_tokens:
        led: led_enter_left_orbit
        color: 8F0000
  timer_lava_jump_shot_timer_tick{ticks==3}:
    room_2i_shot_2_blink:
      action: stop
    blink_light:
      key: room_2i_shot_3_blink
      loops: -1
      show_tokens:
        led: led_enter_ramp
        color: 8F0000
  timer_lava_jump_shot_timer_tick{ticks==4}:
    room_2i_shot_3_blink:
      action: stop
    blink_light:
      key: room_2i_shot_4_blink
      loops: -1
      show_tokens:
        led: led_enter_right_orbit
        color: 8F0000

event_player:
  mode_room_2i_lava_jump_started:
    cmd_backbox_show:
      show_type: fire

variable_player:
  mode_room_2i_lava_jump_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2i
      action: set

