#config_version=5
mode:
  start_events: select_landing_site_norfair_selected, room_2i_continue
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2j_enter, room_2m_enter
  priority: 300

timers:
  lava_jump_shot_timer:
    start_value: 1
    end_value: 4
    restart_on_complete: true
    tick_interval: 10s
    control_events:
      - event: mode_room_2i_lava_jump_started
        action: start

shots:
  lava_jump_first_shot:
    switch: s_left_passage
    profile: lava_jump_blink
    show_tokens:
      led: led_enter_secret_passage
      color: '8F0000'
  lava_jump_second_shot:
    switch: s_orbit_l
    profile: lava_jump_blink
    show_tokens:
      led: led_enter_left_orbit
      color: '8F0000'
  lava_jump_third_shot:
    switch: s_ramp_enter
    profile: lava_jump_blink
    show_tokens:
      led: led_enter_ramp
      color: '8F0000'
  lava_jump_fourth_shot:
    switch: s_orbit_r
    profile: lava_jump_blink
    show_tokens:
      led: led_enter_right_orbit
      color: '8F0000'
  lava_jump_jackpot_shot:
    switch: s_side_ramp_made
    profile: lava_jump_blink
    enable_events: lava_jump_initial_shots_lit_complete
    disable_events: lava_jump_jackpot_shot_hit
    reset_events: lava_jump_jackpot_shot_hit
    show_tokens:
      led: led_enter_side_ramp
      color: '8F0000'
  room_2i_exit_east_shot:
    hit_events: rollover_shot_hit
    profile: exit_door
    enable_events: mode_room_2i_lava_jump_started
    disable_events: room_2i_exit_east_shot_hit
    reset_events: room_2i_exit_east_shot_hit
    show_tokens:
      led: led_rollover
      color: door_blue
  room_2i_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: mode_room_2i_lava_jump_started
    disable_events: room_2i_exit_south_shot_hit
    reset_events: room_2i_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue

shot_profiles:
  lava_jump_blink:
    rotation_pattern: r, r, r, r
    states:
    - name: unlit
      show: blink_light
      loops: -1
      speed: 10
    - name: lit
      show: led_color

shot_groups:
  lava_jump_initial_shots:
    shots: lava_jump_first_shot, lava_jump_second_shot, lava_jump_third_shot, lava_jump_fourth_shot
    rotate_events: timer_lava_jump_shot_timer_tick
    reset_events: lava_jump_jackpot_shot_hit

show_player:
  mode_room_2i_lava_jump_started:
    gi_fire:
      speed: 16
      loops: -1

animations:
  room_2i_backglass_scroll_up:
    - property: y
      value: 1280
      relative: true
      duration: 5s
    - property: y
      value: -1280
      relative: true
      duration: 0s
      repeat: true
  room_2i_backglass_scroll_down:
    - property: y
      value: -1280
      relative: true
      duration: 5s
    - property: y
      value: 1280
      relative: true
      duration: 0s
      repeat: true

slides:
  room_2i_backglass_slide:
    widgets:
      - type: image
        image: room_2i_lava_jump_backglass
        opacity: 0.5
        y: -1
        anchor_y: top
        animations:
          show_slide: room_2i_backglass_scroll_up
      - type: image
        image: room_2i_lava_jump_backglass
        opacity: 0.5
        y: 1279
        anchor_y: top
        animations:
          show_slide: room_2i_backglass_scroll_up
      - type: image
        image: room_2i_lava_jump_backglass
        y: 1280
        anchor_y: bottom
        animations:
          show_slide: room_2i_backglass_scroll_down
      - type: image
        image: room_2i_lava_jump_backglass
        y: 0
        anchor_y: bottom
        animations:
          show_slide: room_2i_backglass_scroll_down
    transition: fade
    transition_out: fade
  room_2i_splash_slide:
    widgets:
      - type: image
        image: room_2i_splash_title
      - type: image
        image: room_2i_splash_background
        fps: 17

slide_player:
  mode_room_2i_lava_jump_started:
    room_2i_backglass_slide:
      target: backglass
    room_2i_splash_slide:
      target: dmd
      expire: 1.5s

event_player:
  mode_room_2i_lava_jump_started:
    cmd_backbox_show:
      show_type: fire
  room_2i_exit_east_shot_hit.1: drop_targets_save
  room_2i_exit_east_shot_hit.2: room_2j_enter
  room_2i_exit_south_shot_hit.1: drop_targets_save
  room_2i_exit_south_shot_hit.2: room_2m_enter

variable_player:
  mode_room_2i_lava_jump_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2i
      action: set
  lava_jump_jackpot_shot_hit:
    score: (150000 + (current_player.area_bonus_ne * 25000)) * current_player.multiplier
  lava_jump_initial_shots_lit_hit:
    score: 80000 * current_player.multiplier

