#config_version=5
mode:
    start_events: select_landing_site_norfair_selected
    stop_events: game_ending, ball_ending
    # restart_on_next_ball: true
    priority: 300

slides:
  room_2i_backglass_slide:
    widgets:
      - type: image
        image: room_2i_lava_jump_backglass
    transition: fade
    transition_out: fade
  room_2i_splash_slide:
    widgets:
      - type: image
        image: room_2i_splash_title
      - type: image
        image: room_2i_splash_background
        fps: 17

slide_player:
  mode_room_2i_lava_jump_started:
    room_2i_backglass_slide:
      target: backglass
    room_2i_splash_slide:
      target: dmd
      expire: 1.5s

variable_player:
  mode_room_2i_lava_jump_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2i
      action: set

