#config_version=5
mode:
  code: bao_base.BaoBase
  start_events: bao_base_started
  stop_events: bao_base_ended
  priority: 200

sequences:
   bao_progress_sequence:
      events:
         - bao_enable_stage_2
         - bao_enable_stage_3
         - bao_enable_stage_4
      persist_state: True
      reset_on_complete: True
      disable_on_complete: False

counters:
  bao_critical_counter:
    count_events: bao_critical_shot_group_hit
    starting_count: 1
    count_complete_value: 10
    events_when_complete: bao_critical_mass
    disable_events: bao_enable_stage_4
    enable_events: bao_enable_stage_3
    reset_events: game_start, bao_enable_stage_4
    persist_state: true

shot_profiles:
  bao_charge_targets:
    states:
      - name: unlit
        show: off
      - name: level_1
        show: led_color
        show_tokens:
          color: '0000FF'
      - name: level_2
        show: led_color
        show_tokens:
          color: '8000FF'
      - name: level_3
        show: led_color
        show_tokens:
          color: FF00FF
  bao_charged_scoop:
    states:
      - name: lit
        show: led_color

shots:
  bao_charge_1_shot:
    switch: s_purple_1
    profile: bao_charge_targets
    enable_events: bao_enable_stage_1
    disable_events: mode_bao_base_started, bao_enable_stage_2
    show_tokens:
      led: led_upgrade_bank_1
  bao_charge_2_shot:
    switch: s_purple_2
    profile: bao_charge_targets
    enable_events: bao_enable_stage_1
    disable_events: mode_bao_base_started, bao_enable_stage_2
    show_tokens:
      led: led_upgrade_bank_2
  bao_charge_3_shot:
    switch: s_purple_3
    profile: bao_charge_targets
    enable_events: bao_enable_stage_1
    disable_events: mode_bao_base_started, bao_enable_stage_2
    show_tokens:
      led: led_upgrade_bank_3
  bao_charged_scoop_shot:
    switch: s_scoop
    profile: bao_charged_scoop
    enable_events: bao_enable_stage_2
    disable_events: mode_bao_base_started, bao_enable_stage_3
    show_tokens:
      led: led_enter_scoop
      color: 'FFFF00'

shot_groups:
  bao_charge_shot_group:
    shots: bao_charge_1_shot, bao_charge_2_shot, bao_charge_3_shot
    reset_events: bao_enable_stage_2
    enable_events: bao_enable_stage_1
    disable_events: bao_enable_stage_2
  bao_critical_shot_group:
    shots: pop_1_shot, pop_2_shot, pop_3_shot
    reset_events: bao_enable_stage_4
    enable_events: bao_enable_stage_3
    disable_events: bao_enable_stage_4

ball_holds:
  bao_charged_scoop_shot:
    balls_to_hold: 1
    hold_devices: bd_scoop
    enable_events: bao_enable_stage_2
    disable_events: mode_bao_base_started, bao_enable_stage_3
    release_all_events: bao_critical_should_start

slides:
  bao_base_backglass_slide:
    widgets:
      - type: text
        text: (player1|score)
        number_grouping: true
        min_digits: 2
        y: 296
        x: 173
        anchor_x: right
        font_name: segmented
        font_size: 24
      - type: text
        text: (player2|score)
        number_grouping: true
        min_digits: 2
        y: 296
        x: 343
        anchor_x: right
        font_name: segmented
        font_size: 24
      - type: text
        text: (player3|score)
        number_grouping: true
        min_digits: 2
        y: 296
        x: 513
        anchor_x: right
        font_name: segmented
        font_size: 24
      - type: text
        text: (player4|score)
        number_grouping: true
        min_digits: 2
        y: 296
        x: 683
        anchor_x: right
        font_name: segmented
        font_size: 24
      - type: rectangle
        width: 150
        height: 34
        color: black
        y: 300
        x: 105
      - type: rectangle
        width: 150
        height: 34
        color: black
        y: 300
        x: 275
      - type: rectangle
        width: 150
        height: 34
        color: black
        y: 300
        x: 445
      - type: rectangle
        width: 150
        height: 34
        color: black
        y: 300
        x: 615
      - type: image
        image: bao_backbox_secret
    transition: fade
    transition_out: fade

slide_player:
  mode_bao_base_started:
    bao_base_backglass_slide:
      target: backglass

show_player:
  mode_bao_base_started:
    gi_solid:
      loops: -1
      show_tokens:
        color: 'C0C0C0'
  pop_1_shot_hit:
    blink_light:
      key: pop_bumpers_blink_1
      loops: 1
      speed: 20
      show_tokens:
        led: led_pop_2
        color: FFFFFF
  pop_2_shot_hit:
    blink_light:
      key: pop_bumpers_blink_2
      loops: 1
      speed: 20
      show_tokens:
        led: led_pop_3
        color: FFFFFF
  pop_3_shot_hit:
    blink_light:
      key: pop_bumpers_blink_3
      loops: 1
      speed: 20
      show_tokens:
        led: led_pop_1
        color: FFFFFF
  bao_charged_scoop_shot_hit:
    bao_scoop_hit:
      loops: -1
      speed: 50
    bao_scoop_critical:
      loops: 0
      priority: 9000
      events_when_stopped: bao_critical_should_start
  bao_critical_should_start:
    bao_scoop_hit:
      action: stop
  bao_enable_stage_3:
    bao_pops_critical:
      loops: -1
      speed: 20

event_player:
  mode_bao_base_started{device.sequences.bao_progress_sequence.value == 0}: bao_enable_stage_1
  mode_bao_base_started{device.sequences.bao_progress_sequence.value == 1}: bao_enable_stage_2
  mode_bao_base_started{device.sequences.bao_progress_sequence.value == 2}: bao_enable_stage_3
  mode_bao_base_started{device.sequences.bao_progress_sequence.value == 3}: bao_enable_stage_4
  mode_bao_base_started{current_player.number == 1 and current_player.ball == 1}: bao_base_initialize, cmd_drop_one_down, cmd_drop_two_down, cmd_drop_three_up
  bao_charge_shot_group_level_3_complete: bao_enable_stage_2
  bao_critical_should_start: bao_enable_stage_3, scoop_autofire_should_enable
  bao_critical_mass: bao_enable_stage_4
  bao_enable_stage_2: scoop_autofire_should_disable
  s_behind_drop_2_active{machine.bao_balls_locked == 0 and game.balls_in_play == 1}: cmd_drop_two_up, cmd_drop_three_up, bao_base_lock_a_ball
  s_behind_drop_1_active{machine.bao_balls_locked == 1 and game.balls_in_play == 1}: cmd_drop_one_up, bao_base_lock_a_ball
  drop_target_drop_one_down{machine.bao_balls_locked == 2}: bao_base_release_locked_balls
  drop_target_drop_two_down{machine.bao_balls_locked > 1}: cmd_drop_two_up
  drop_target_drop_three_down: cmd_drop_three_up
  bao_base_release_locked_balls: cmd_drop_one_down, cmd_drop_two_down
  mode_bao_base_ending{current_player.number == game.num_players and current_player.ball == game.balls_per_game}: cmd_drop_one_down, cmd_drop_two_down
