#config_version=5
mode:
  start_events: room_1d_continue, room_1d_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1c_enter, room_1l_enter
  priority: 300

slides:
  room_1d_the_lake_backglass_slide:
    widgets:
      - type: image
        image: room_1d_the_lake_backglass
    transition: fade
    transition_out: fade
  room_1d_the_lake_splash_slide:
    widgets:
      - type: image
        image: room_1d_the_lake_splash

slide_player:
  mode_room_1d_the_lake_started:
    room_1d_the_lake_backglass_slide:
      target: backglass
    room_1d_the_lake_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1d_the_lake_started:
    room_2d_underwater:
      loops: -1
      speed: 10
  show_mode_status_report:
    room_1d_the_lake_status_report:
      loops: 0
  flipper_cradle_release:
    room_1d_the_lake_status_report:
      action: stop

event_player:
  mode_room_1d_the_lake_started:
    cmd_backbox_show:
      show_type: gradient
      color_start: "0000FF"
      color_end: "00FF00"
    drop_targets_continue:

variable_player:
  mode_room_1d_the_lake_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1d
      action: set
