#config_version=5

# replace 1j with room code
# replace room_1j_phantoon with mode name

mode:
  start_events: room_1j_continue, room_1j_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1i_enter, room_1j_exit
  priority: 300

sequences:
  room_1j_phantoon_open_eye_sequence:
    events:
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
      - room_1j_phantoon_eye_shot_group_hit
    events_when_complete: room_1j_open_eye
    persist_state: True
    reset_on_complete: False
    disable_on_complete: True

multiballs:
  room_1j_phantoon_boss_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 20s
    start_events: mode_room_1j_phantoon_start_multiball

shot_profiles:
  room_1j_weak_spot:
    states:
      - name: lit
        sync_ms: 4000
        show: fade_one_light

shots:
  room_1j_boss_eye_open_center_1_shot:
    switch: s_purple_1
    profile: room_1j_weak_spot
    enable_events: mode_room_1j_phantoon_battle, mode_room_1j_phantoon_recovered
    disable_events: mode_room_1j_phantoon_over, mode_room_1j_phantoon_vulnerable
    show_tokens:
      led: led_upgrade_bank_1
      color: purple
  room_1j_boss_eye_open_center_2_shot:
    switch: s_purple_2
    profile: room_1j_weak_spot
    enable_events: mode_room_1j_phantoon_battle, mode_room_1j_phantoon_recovered
    disable_events: mode_room_1j_phantoon_over, mode_room_1j_phantoon_vulnerable
    show_tokens:
      led: led_upgrade_bank_2
      color: purple
  room_1j_boss_eye_open_center_3_shot:
    switch: s_purple_3
    profile: room_1j_weak_spot
    enable_events: mode_room_1j_phantoon_battle, mode_room_1j_phantoon_recovered
    disable_events: mode_room_1j_phantoon_over, mode_room_1j_phantoon_vulnerable
    show_tokens:
      led: led_upgrade_bank_3
      color: purple

shot_groups:
  room_1j_phantoon_eye_shot_group:
    shots: room_1j_boss_eye_open_center_1_shot, room_1j_boss_eye_open_center_2_shot, room_1j_boss_eye_open_center_3_shot
    enable_events: mode_room_1j_phantoon_battle, mode_room_1j_phantoon_recovered
    disable_events: mode_room_1j_phantoon_over, mode_room_1j_phantoon_vulnerable

animations:
  room_1j_phantoon_standard:
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
      repeat: true

slides:
  room_1j_phantoon_backglass_slide:
    widgets:
      - type: image
        image: room_1j_phantoon_backglass
        animations:
          show_slide: room_1j_phantoon_standard
    transition: fade
    transition_out: fade
  room_1j_phantoon_splash_slide:
    widgets:
      - type: image
        image: room_1j_phantoon_splash

slide_player:
  mode_room_1j_phantoon_started:
    room_1j_phantoon_backglass_slide:
      target: backglass
    room_1j_phantoon_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1j_phantoon_started:
    room_1j_phantoon_gi:
      loops: -1
      speed: 70
  show_mode_status_report:
    room_1j_phantoon_status_report:
      loops: 0
  flipper_cradle_release:
    room_1j_phantoon_status_report:
      action: stop
  room_1j_play_eye_open:
    room_1j_phantoon_eye_open:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_0:
    room_1j_phantoon_eye_0:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_1:
    room_1j_phantoon_eye_1:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_2:
    room_1j_phantoon_eye_2:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_3:
    room_1j_phantoon_eye_3:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_4:
    room_1j_phantoon_eye_4:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_5:
    room_1j_phantoon_eye_5:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_6:
    room_1j_phantoon_eye_6:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_7:
    room_1j_phantoon_eye_7:
      key: phantoon_eye_show
      loops: -1
  room_1j_play_eye_8:
    room_1j_phantoon_eye_8:
      key: phantoon_eye_show
      loops: -1

event_player:
  mode_room_1j_phantoon_started:
    cmd_backbox_show:
      show_type: plasma
      color1: "008080"
      color2: "007070"
      color3: "006070"
      color4: "005070"
      color5: "004060"
      color6: "003060"
      color7: "002040"
      color8: "808080"
      decay_r: 2.0
      decay_g: 1.7
      decay_b: 1.5
    drop_targets_continue:
    cmd_map_position:
      room: '1j'
      visit: True
  mode_room_1j_phantoon_started{current_player.boss_phantoon_hp < 1}: mode_room_1j_phantoon_over, mode_room_1j_phantoon_open_door, room_1j_show_defeated_backglass
  mode_room_1j_phantoon_started{current_player.boss_phantoon_hp > 0}: mode_room_1j_phantoon_battle, metroid_exclusive_started, spin_jumps_disable
  mode_room_1j_phantoon_battle{current_player.boss_phantoon_multiball_played == 0}: mode_room_1j_phantoon_start_multiball
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 0}: room_1j_play_eye_0
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 1}: room_1j_play_eye_1
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 2}: room_1j_play_eye_2
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 3}: room_1j_play_eye_3
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 4}: room_1j_play_eye_4
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 5}: room_1j_play_eye_5
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 6}: room_1j_play_eye_6
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 7}: room_1j_play_eye_7
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value == 8}: room_1j_play_eye_8
  mode_room_1j_phantoon_battle{device.sequences.room_1j_phantoon_open_eye_sequence.value >= 9}: room_1j_play_eye_open
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 1}: room_1j_play_eye_1
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 2}: room_1j_play_eye_2
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 3}: room_1j_play_eye_3
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 4}: room_1j_play_eye_4
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 5}: room_1j_play_eye_5
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 6}: room_1j_play_eye_6
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 7}: room_1j_play_eye_7
  logicblock_room_1j_phantoon_open_eye_sequence_updated{value == 8}: room_1j_play_eye_8
  room_1j_open_eye: room_1j_play_eye_open

variable_player:
  mode_room_1j_phantoon_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1j
      action: set
  mode_room_1j_phantoon_start_multiball:
    boss_phantoon_multiball_played:
      int: 1
      action: set
