#config_version=5
mode:
    start_events: select_landing_site_brinstar_selected, room_1r_continue
    stop_events: game_ending, ball_ending
    priority: 300

show_player:
  mode_room_1r_space_pirate_battle_started:
    gi_solid:
      loops: -1
      show_tokens:
        color: '8000C0'

slides:
  room_1r_backglass_slide:
    widgets:
      - type: image
        image: room_1r_space_pirate_battle_backglass
    transition: fade
    transition_out: fade
  room_1r_splash_slide:
    widgets:
      - type: image
        image: room_1r_splash

slide_player:
  mode_room_1r_space_pirate_battle_started:
    room_1r_backglass_slide:
      target: backglass
    room_1r_splash_slide:
      target: dmd
      expire: 1.5s

variable_player:
  mode_room_1r_space_pirate_battle_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1r
      action: set
