#config_version=5
mode:
    start_events: select_landing_site_brinstar_selected, room_1r_continue
    stop_events: game_ending, ball_ending
    priority: 300

timers:
  room_1r_light_shot_timer:
    start_value: 1
    end_value: 8
    restart_on_complete: true
    tick_interval: 4s
    control_events:
      - event: mode_room_1r_space_pirate_battle_started
        action: start

shots:
  room_1r_start_shot_1:
    switch: s_shatz
    profile: room_1r_blink
    enable_events: room_1r_shot_1_activate
    disable_events: room_1r_shot_2_activate
    reset_events: room_1r_shot_2_activate
    show_tokens:
      led: led_zero_suit
      color: 'FF40FF'
  room_1r_start_shot_2:
    switch: s_left_passage
    profile: room_1r_blink
    enable_events: room_1r_shot_2_activate
    disable_events: room_1r_shot_3_activate
    reset_events: room_1r_shot_3_activate
    show_tokens:
      led: led_enter_secret_passage
      color: 'FF40FF'
  room_1r_start_shot_3:
    switch: s_orbit_l
    profile: room_1r_blink
    enable_events: room_1r_shot_3_activate
    disable_events: room_1r_shot_4_activate
    reset_events: room_1r_shot_4_activate
    show_tokens:
      led: led_enter_left_orbit
      color: 'FF40FF'

shot_profiles:
  room_1r_blink:
    states:
    - name: lit
      show: blink_light
      loops: -1

multiballs:
  room_1r_battle:
    ball_count: 2
    ball_count_type: total
    start_events: room_1r_multiball_should_start

show_player:
  mode_room_1r_space_pirate_battle_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '8000C0'
        color2: "8080C0"

slides:
  room_1r_backglass_slide:
    widgets:
      - type: image
        image: room_1r_space_pirate_battle_backglass
    transition: fade
    transition_out: fade
  room_1r_splash_slide:
    widgets:
      - type: image
        image: room_1r_splash

slide_player:
  mode_room_1r_space_pirate_battle_started:
    room_1r_backglass_slide:
      target: backglass
    room_1r_splash_slide:
      target: dmd
      expire: 1.5s

event_player:
  mode_room_1r_space_pirate_battle_started{current_player.room_1r_multiball_started == 0}: room_1r_multiball_should_start
  timer_room_1r_light_shot_timer_tick{ticks == 1}: room_1r_shot_1_activate
  timer_room_1r_light_shot_timer_tick{ticks == 2}: room_1r_shot_2_activate
  timer_room_1r_light_shot_timer_tick{ticks == 3}: room_1r_shot_3_activate
  timer_room_1r_light_shot_timer_tick{ticks == 4}: room_1r_shot_4_activate
  timer_room_1r_light_shot_timer_tick{ticks == 5}: room_1r_shot_5_activate
  timer_room_1r_light_shot_timer_tick{ticks == 6}: room_1r_shot_6_activate
  timer_room_1r_light_shot_timer_tick{ticks == 7}: room_1r_shot_7_activate
  timer_room_1r_light_shot_timer_tick{ticks == 8}: room_1r_shot_8_activate

variable_player:
  mode_room_1r_space_pirate_battle_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1r
      action: set
  multiball_room_1r_battle_started:
    room_1r_multiball_started:
      int: 1
      action: set
