#config_version=5
mode:
    start_events: room_1b_achieved, room_1b_already_complete
    stop_events: game_ending, ball_ending, metroid_base_ended, room_1c_enter, room_1a_enter, room_1b_exit
    priority: 300

multiballs:
  gunship:
    ball_count: 4
    ball_count_type: total
    shoot_again: 20s
    start_events: room_1b_victory_scan_achieved

counters:
  room_1b_victory_counter:
    count_events: room_1b_landing_site_qualify_multiball_shot_hit
    events_when_hit: room_1b_victory_scan_progress
    starting_count: 0
    count_complete_value: 200
    direction: up
    events_when_complete: room_1b_victory_scan_achieved
    reset_events: game_start
    persist_state: true
    reset_on_complete: false
    disable_on_complete: true

shots:
  room_1b_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1b_exit_east_shot_hit, metroid_close_doors
    reset_events: room_1b_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_1b_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1b_exit_west_shot_hit, metroid_close_doors
    reset_events: room_1b_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1b_landing_site_qualify_multiball_shot:
    switches:
      - s_left_passage
      - s_pop_1
      - s_pop_2
      - s_pop_3
      - s_thin_orange
      - s_captive_ball
      - s_upper_sling
      - s_scoop
      - s_lower_right_bank_1
      - s_lower_right_bank_2
      - s_lower_right_bank_3
      - s_right_outlane
      - s_right_inlane
      - s_left_outlane
      - s_left_inlane
      - s_rollover_button
      - s_left_sling
      - s_right_sling
      - s_missile_bank_1
      - s_missile_bank_2
      - s_missile_bank_3
      - s_shatz
      - s_vuk
      - s_pop_sling
      - s_pop_subway
      - s_purple_1
      - s_purple_2
      - s_purple_3
      - s_orbit_r
      - s_orbit_l
      - s_ramp_enter
      - s_behind_drop_1
      - s_behind_drop_2
      - s_behind_drop_3
      - s_side_ramp_made
      - s_spinner
      - s_left_target_1
      - s_left_target_2
      - s_left_target_3
      - s_top_lane_1
      - s_top_lane_2
      - s_top_lane_3
    enable_events: mode_room_1b_gunship_victory_started
    # disable_events: room_1b_exit_west_shot_hit
    # reset_events: room_1b_exit_west_shot_hit

show_player:
  mode_room_1b_gunship_victory_started:
    gi_solid:
      loops: -1
      show_tokens:
        color: '606070'
  show_mode_status_report:
    room_1b_victory_status_report:
      loops: 0
  flipper_cradle_release:
    room_1b_victory_status_report:
      action: stop

slide_player:
  player_room_1b_victory_scan_percent{value % 10 == 0}: room_1b_victory_progress_slide
  mode_room_1b_gunship_victory_started:
    room_1b_victory_backglass_slide:
      target: backglass

slides:
  room_1b_victory_progress_slide:
    widgets:
      - type: text
        text: Planet (value)% Scanned
        color: yellow
        style: dmd_med
    expire: 1s
  room_1b_victory_backglass_slide:
    widgets:
      - type: image
        image: gunship_flying
        y: 520
      - type: image
        image: room_1b_backglass_landed
    transition:
      type: push
      duration: 1s
      direction: down
    transition_out: fade

event_player:
  mode_room_1b_gunship_victory_started:
    cmd_backbox_show:
      show_type: two_tone
      min_cutoff: 6
      max_cutoff: 8
      color1: "040404"
      color2: "04100C"
    drop_targets_continue:
    cmd_map_position:
      room: '1b'
      visit: True
    cmd_play_map_music:
      music: music_crateria_quiet
  mode_room_1b_gunship_victory_started{game.balls_in_play == 1}: metroid_open_doors
  show_mode_status_report:
    room_1b_victory_status_report:
      loops: 0
  flipper_cradle_release:
    room_1b_victory_status_report:
      action: stop
  room_1b_exit_east_shot_hit.1: drop_targets_save
  room_1b_exit_east_shot_hit.2: room_1c_enter
  room_1b_exit_west_shot_hit.1: drop_targets_save
  room_1b_exit_west_shot_hit.2: room_1a_enter

variable_player:
  logicblock_room_1b_victory_counter_updated:
    room_1b_victory_scan_percent:
      int: value / 2
      action: set
  room_1b_victory_scan_achieved:
    room_1b_victory_step_1:
      int: 1
      action: set
