#config_version=5
mode:
  start_events: gorens_lament_should_start
  stop_events: gorens_lament_should_end
  priority: 100

sounds:
  gorens_lament_01:
    file: gorens_lament_01.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_02:
    file: gorens_lament_02.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_03:
    file: gorens_lament_03.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_04:
    file: gorens_lament_04.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_05:
    file: gorens_lament_05.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_06:
    file: gorens_lament_06.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_07:
    file: gorens_lament_07.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_08:
    file: gorens_lament_08.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_09:
    file: gorens_lament_09.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_10:
    file: gorens_lament_10.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_11:
    file: gorens_lament_11.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_12:
    file: gorens_lament_12.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_13:
    file: gorens_lament_13.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_14:
    file: gorens_lament_14.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_15:
    file: gorens_lament_15.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_16:
    file: gorens_lament_16.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_17:
    file: gorens_lament_17.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_18:
    file: gorens_lament_18.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_19:
    file: gorens_lament_19.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_20:
    file: gorens_lament_20.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_21:
    file: gorens_lament_21.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_22:
    file: gorens_lament_22.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_23:
    file: gorens_lament_23.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_24:
    file: gorens_lament_24.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_25:
    file: gorens_lament_25.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_intro_1:
    file: gorens_lament_intro_1.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_intro_2:
    file: gorens_lament_intro_2.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_intro_3:
    file: gorens_lament_intro_3.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_intro_4:
    file: gorens_lament_intro_4.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_outtro_1:
    file: gorens_lament_outtro_1.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
  gorens_lament_outtro_2:
    file: gorens_lament_outtro_2.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None
