#config_version=5
mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 100

sequences:
   miniboss_progress_sequence:
      events:
         - miniboss_targets_level_1_shot_group_lit_complete
         - miniboss_targets_level_2_shot_group_lit_complete
         - miniboss_targets_level_3_shot_group_lit_complete
         - miniboss_final_shot_hit
      persist_state: True
      reset_on_complete: True
      disable_on_complete: False

shot_profiles:
  miniboss_targets:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color
  miniboss_scoop:
    states:
      - name: lit
        show: fade_one_light

shots:
  miniboss_level_1_1_shot:
    switch: s_purple_1
    profile: miniboss_targets
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: FF0000
  miniboss_level_1_2_shot:
    switch: s_purple_2
    profile: miniboss_targets
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: FF0000
  miniboss_level_1_3_shot:
    switch: s_purple_3
    profile: miniboss_targets
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: FF0000
  miniboss_level_2_1_shot:
    switch: s_purple_1
    profile: miniboss_targets
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: FF8000
  miniboss_level_2_2_shot:
    switch: s_purple_2
    profile: miniboss_targets
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: FF8000
  miniboss_level_2_3_shot:
    switch: s_purple_3
    profile: miniboss_targets
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: FF8000
  miniboss_level_3_1_shot:
    switch: s_purple_1
    profile: miniboss_targets
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: 00FF00
  miniboss_level_3_2_shot:
    switch: s_purple_2
    profile: miniboss_targets
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: 00FF00
  miniboss_level_3_3_shot:
    switch: s_purple_3
    profile: miniboss_targets
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: 00FF00
  miniboss_level_4_1_shot:
    switch: s_purple_1
    profile: miniboss_scoop
    enable_events: miniboss_enable_level_4
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: 00FF80
  miniboss_level_4_2_shot:
    switch: s_purple_2
    profile: miniboss_scoop
    enable_events: miniboss_enable_level_4
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: 00FF80
  miniboss_level_4_3_shot:
    switch: s_purple_3
    profile: miniboss_scoop
    enable_events: miniboss_enable_level_4
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: 00FF80
  miniboss_final_shot:
    switch: s_scoop
    profile: miniboss_scoop
    enable_events: miniboss_enable_level_4
    disable_events: mode_miniboss_starting, miniboss_final_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: 00FF80

shot_groups:
  miniboss_targets_level_1_shot_group:
    shots: miniboss_level_1_1_shot, miniboss_level_1_2_shot, miniboss_level_1_3_shot
    reset_events: miniboss_targets_level_1_shot_group_lit_complete
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting, mode_miniboss_ending, miniboss_targets_level_1_shot_group_lit_complete
  miniboss_targets_level_2_shot_group:
    shots: miniboss_level_2_1_shot, miniboss_level_2_2_shot, miniboss_level_2_3_shot
    reset_events: miniboss_targets_level_2_shot_group_lit_complete
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting, mode_miniboss_ending, miniboss_targets_level_2_shot_group_lit_complete
  miniboss_targets_level_3_shot_group:
    shots: miniboss_level_3_1_shot, miniboss_level_3_2_shot, miniboss_level_3_3_shot
    reset_events: miniboss_targets_level_3_shot_group_lit_complete
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting, mode_miniboss_ending, miniboss_targets_level_3_shot_group_lit_complete

event_player:
  mode_miniboss_started{device.sequences.miniboss_progress_sequence.value == 0}: miniboss_enable_level_1
  mode_miniboss_started{device.sequences.miniboss_progress_sequence.value == 1}: miniboss_enable_level_2
  mode_miniboss_started{device.sequences.miniboss_progress_sequence.value == 2}: miniboss_enable_level_3
  mode_miniboss_started{device.sequences.miniboss_progress_sequence.value == 3}: miniboss_enable_level_4
  logicblock_miniboss_progress_sequence_updated{value == 0}: miniboss_enable_level_1
  logicblock_miniboss_progress_sequence_updated{value == 1}: miniboss_enable_level_2
  logicblock_miniboss_progress_sequence_updated{value == 2}: miniboss_enable_level_3
  logicblock_miniboss_progress_sequence_updated{value == 3}: miniboss_enable_level_4
  miniboss_targets_level_1_shot_group_lit_complete: miniboss_targets_completed
  miniboss_targets_level_2_shot_group_lit_complete: miniboss_targets_completed
  miniboss_targets_level_3_shot_group_lit_complete: miniboss_targets_completed

show_player:
  miniboss_targets_level_1_shot_group_lit_complete:
    blink_3_lights:
      loops: 3
      priority: 500
      speed: 5
      show_tokens:
        led_1: led_upgrade_bank_1
        led_2: led_upgrade_bank_2
        led_3: led_upgrade_bank_3
        color_1: 'FF0000'
        color_2: stop
  miniboss_targets_level_2_shot_group_lit_complete:
    blink_3_lights:
      loops: 3
      priority: 500
      speed: 5
      show_tokens:
        led_1: led_upgrade_bank_1
        led_2: led_upgrade_bank_2
        led_3: led_upgrade_bank_3
        color_1: 'FF8000'
        color_2: stop
  miniboss_targets_level_3_shot_group_lit_complete:
    blink_3_lights:
      loops: 3
      priority: 500
      speed: 5
      show_tokens:
        led_1: led_upgrade_bank_1
        led_2: led_upgrade_bank_2
        led_3: led_upgrade_bank_3
        color_1: '00FF00'
        color_2: stop
  miniboss_targets_completed:
    miniboss_targets_completed:
      loops: 0

variable_player:
  miniboss_level_1_1_shot_hit:
    score: 100 * current_player.multiplier
  miniboss_level_1_2_shot_hit:
    score: 100 * current_player.multiplier
  miniboss_level_1_3_shot_hit:
    score: 100 * current_player.multiplier
  miniboss_level_2_1_shot_hit:
    score: 1000 * current_player.multiplier
  miniboss_level_2_2_shot_hit:
    score: 1000 * current_player.multiplier
  miniboss_level_2_3_shot_hit:
    score: 1000 * current_player.multiplier
  miniboss_level_3_1_shot_hit:
    score: 5000 * current_player.multiplier
  miniboss_level_3_2_shot_hit:
    score: 5000 * current_player.multiplier
  miniboss_level_3_3_shot_hit:
    score: 5000 * current_player.multiplier
  miniboss_level_4_1_shot_hit:
    score: 10000 * current_player.multiplier
  miniboss_level_4_2_shot_hit:
    score: 10000 * current_player.multiplier
  miniboss_level_4_3_shot_hit:
    score: 10000 * current_player.multiplier 
  miniboss_final_shot_hit:
    score: 50000 * current_player.multiplier
  miniboss_targets_completed:
    score:
      int: 1000 * current_player.multiplier

