#config_version=5
mode:
  start_events: mode_base_starting
  priority: 100

shot_profiles:
  miniboss_targets:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color

shots:
  miniboss_level_1_1_shot:
    switch: s_purple_1
    profile: miniboss_targets
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: FF0000
  miniboss_level_1_2_shot:
    switch: s_purple_2
    profile: miniboss_targets
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: FF0000
  miniboss_level_1_3_shot:
    switch: s_purple_3
    profile: miniboss_targets
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: FF0000
  miniboss_level_2_1_shot:
    switch: s_purple_1
    profile: miniboss_targets
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: FF8000
  miniboss_level_2_2_shot:
    switch: s_purple_2
    profile: miniboss_targets
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: FF8000
  miniboss_level_2_3_shot:
    switch: s_purple_3
    profile: miniboss_targets
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: FF8000
  miniboss_level_3_1_shot:
    switch: s_purple_1
    profile: miniboss_targets
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_1
      color: 00FF00
  miniboss_level_3_2_shot:
    switch: s_purple_2
    profile: miniboss_targets
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_2
      color: 00FF00
  miniboss_level_3_3_shot:
    switch: s_purple_3
    profile: miniboss_targets
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_starting
    show_tokens:
      led: led_upgrade_bank_3
      color: 00FF00

shot_groups:
  miniboss_targets_level_1_shot_group:
    shots: miniboss_level_1_1_shot, miniboss_level_1_2_shot, miniboss_level_1_3_shot
    reset_events: miniboss_targets_level_1_shot_group_lit_complete
    enable_events: miniboss_enable_level_1
    disable_events: mode_miniboss_ending
  miniboss_targets_level_2_shot_group:
    shots: miniboss_level_2_1_shot, miniboss_level_2_2_shot, miniboss_level_2_3_shot
    reset_events: miniboss_targets_level_2_shot_group_lit_complete
    enable_events: miniboss_enable_level_2
    disable_events: mode_miniboss_ending, miniboss_targets_level_2_shot_group_lit_complete
  miniboss_targets_level_3_shot_group:
    shots: miniboss_level_3_1_shot, miniboss_level_3_2_shot, miniboss_level_3_3_shot
    reset_events: miniboss_targets_level_3_shot_group_lit_complete
    enable_events: miniboss_enable_level_3
    disable_events: mode_miniboss_ending, miniboss_targets_level_3_shot_group_lit_complete

event_player:
  mode_miniboss_started: miniboss_enable_level_1
  miniboss_targets_level_1_shot_group_lit_complete: miniboss_targets_completed, miniboss_enable_level_2
  miniboss_targets_level_2_shot_group_lit_complete: miniboss_targets_completed, miniboss_enable_level_3
  miniboss_targets_level_3_shot_group_lit_complete: miniboss_targets_completed, miniboss_enable_level_1

show_player:
  miniboss_targets_completed:
    miniboss_targets_completed:
      loops: 0

variable_player:
  miniboss_level_1_1_shot_hit:
    score: 100 * current_player.multiplier
  miniboss_level_1_2_shot_hit:
    score: 100 * current_player.multiplier
  miniboss_level_1_3_shot_hit:
    score: 100 * current_player.multiplier
  miniboss_level_2_1_shot_hit:
    score: 1000 * current_player.multiplier
  miniboss_level_2_2_shot_hit:
    score: 1000 * current_player.multiplier
  miniboss_level_2_3_shot_hit:
    score: 1000 * current_player.multiplier
  miniboss_level_3_1_shot_hit:
    score: 5000 * current_player.multiplier
  miniboss_level_3_2_shot_hit:
    score: 5000 * current_player.multiplier
  miniboss_level_3_3_shot_hit:
    score: 5000 * current_player.multiplier
  miniboss_targets_completed:
    score:
      int: 1000 * current_player.multiplier

