#config_version=5
mode:
  start_events: room_1m_continue, room_1m_enter
  stop_events: game_ending, ball_ending, metroid_base_ended
  priority: 300

shot_profiles:
  room_1m_start_multiball:
    states:
      - name: lit
        show: fade_one_light
  room_1m_captive:
    states:
      - name: lit
        show: led_color

shots:
  room_1m_generator_start_multiball_shot:
    switch: s_thin_orange
    profile: room_1m_start_multiball
    disable_events: room_1m_generator_start_multiball_shot_hit
    enable_events: mode_room_1m_generator_started
    show_tokens:
      led: led_thin_orange
      color: 'FF8000'
  room_1m_generator_captive_shot:
    switch: s_captive_ball
    profile: room_1m_captive
    enable_events: multiball_room_1m_generator_multiball_started
    disable_events: multiball_room_1m_generator_multiball_ended
    show_tokens:
      led: led_captive_ball
      color: '004040'

timers:
  room_1m_test_ball_locked:
    start_value: 1
    end_value: 3
    tick_interval: 1.0s
    control_events:
      - event: room_1m_test_lock
        action: restart

multiballs:
  room_1m_generator_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 30s
    start_events: room_1m_generator_start_multiball_shot_hit

slides:
  room_1m_generator_backglass_slide:
    widgets:
      - type: image
        image: room_1m_generator_backglass
    transition: fade
    transition_out: fade
  room_1m_generator_splash_slide:
    widgets:
      - type: image
        image: room_1m_generator_splash

slide_player:
  mode_room_1m_generator_started:
    room_1m_generator_backglass_slide:
      target: backglass
    room_1m_generator_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1m_generator_started:
    room_1m_generator_gi:
      loops: -1
      speed: 30
  show_mode_status_report:
    room_1m_generator_status_report:
      loops: 0
  flipper_cradle_release:
    room_1m_generator_status_report:
      action: stop
  multiball_room_1m_generator_multiball_started:
    blink_light:
      key: room_1m_ball_save_blink
      loops: -1
      speed: 2
      show_tokens:
        led: led_ball_save
        color: ff4700
  multiball_room_1m_generator_multiball_shoot_again_ended:
    room_1m_ball_save_blink:
      action: stop
  room_1m_add_charge:
    blink_3_lights:
      loops: 0
      priority: 500
      speed: 8
      show_tokens:
        led_1: led_drop_1
        led_2: led_drop_2
        led_3: led_drop_3
        color_1: 'FFFF00'
        color_2: '000000'

sounds:
  room_1m_charge:
    file: room_1m_charge.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 0.7
    max_queue_time: None

sound_player:
  mode_room_1m_generator_started: shoot_the_flashing_target
  room_1m_generator_start_multiball_shot_hit: multiball
  room_1m_ball_locked: shoot_the_drop_target
  room_1m_add_charge: room_1m_charge

event_player:
  mode_room_1m_generator_started:
    cmd_backbox_show:
      show_type: gradient
      color_start: "100080"
      color_end: "005020"
    drop_targets_continue:
    chozo_multiball_disable:
  multiball_room_1m_generator_multiball_started: drop_target_mode_should_end
  mode_drop_targets_stopped: cmd_drop_three_up
  s_behind_drop_1_active{device.multiballs.room_1m_generator_multiball.balls_added_live > 0}: cmd_drop_one_up, room_1m_test_lock
  timer_room_1m_test_ball_locked_complete{device.switches.s_behind_drop_1.state}: room_1m_ball_locked, cmd_drop_three_down
  timer_room_1m_test_ball_locked_complete{not device.switches.s_behind_drop_1.state}: room_1m_ball_released, cmd_drop_three_up, cmd_drop_one_down
  multiball_room_1m_generator_multiball_ended: cmd_drop_one_down
  drop_target_drop_one_down{device.multiballs.room_1m_generator_multiball.balls_added_live > 0 and player.room_1m_captured > 0}: cmd_drop_one_up
  s_vuk_active: room_1m_ball_released, cmd_drop_one_down, cmd_drop_three_up
  s_vuk_active{current_player.room_1m_captured > 0}: room_1m_add_big_charge
  s_behind_drop_2_active{current_player.room_1m_captured > 0}: room_1m_add_charge
  s_behind_drop_3_active{current_player.room_1m_captured > 0}: room_1m_add_charge

variable_player:
  mode_room_1m_generator_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1m
      action: set
    room_1m_captured:
      int: 0
      action: set
  room_1m_ball_locked:
    room_1m_captured:
      int: 1
      action: set
  room_1m_ball_released:
    room_1m_captured:
      int: 0
      action: set
  room_1m_add_charge:
    room_1m_charge: 1
  room_1m_add_big_charge:
    room_1m_charge: 5
