#config_version=5
mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 100

shot_profiles:
  missiles:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color

shots:
  missile_bank_1_shot:
    switch: s_missile_bank_1
    profile: missiles
    show_tokens:
      led: led_missile_bank_1
      color: "9900ff"
  missile_bank_2_shot:
    switch: s_missile_bank_2
    profile: missiles
    show_tokens:
      led: led_missile_bank_2
      color: "9900ff"
  missile_bank_3_shot:
    switch: s_missile_bank_3
    profile: missiles
    show_tokens:
      led: led_missile_bank_3
      color: "9900ff"

shot_groups:
  missiles_shot_group:
    shots: missile_bank_1_shot, missile_bank_2_shot, missile_bank_3_shot
    reset_events: missiles_shot_group_lit_complete
    enable_events: mode_missiles_started
    disable_events: mode_missiles_ending

sounds:
  missile_hit:
    file: missile_hit.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 1.0
    max_queue_time: None
  missile_already_hit:
    file: missile_already_hit.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 1.0
    max_queue_time: None


event_player:
  missiles_shot_group_lit_complete: missile_collected
  missiles_shot_group_lit_hit: missile_play_missed_sound
  mode_missiles_started{current_player.missiles == 0}: missiles_play_lights_0
  mode_missiles_started{current_player.missiles == 1}: missiles_play_lights_1
  mode_missiles_started{current_player.missiles == 2}: missiles_play_lights_2
  mode_missiles_started{current_player.missiles == 3}: missiles_play_lights_3
  mode_missiles_started{current_player.missiles > 3}: missiles_play_lights_4
  player_missiles{value == 0}: missiles_play_lights_0
  player_missiles{value == 1}: missiles_play_lights_1
  player_missiles{value == 2}: missiles_play_lights_2
  player_missiles{value == 3}: missiles_play_lights_3
  player_missiles{value > 3}: missiles_play_lights_4


show_player:
  missile_collected:
    missiles_collected:
      loops: 0
  missiles_play_lights_0:
    missiles_indicator:
      action: stop
  missiles_play_lights_1:
    indicator_1:
      loops: -1
      key: missiles_indicator
      show_tokens:
        color: '200000'
        led1: led_missile_count_nw
  missiles_play_lights_2:
    indicator_2:
      loops: -1
      key: missiles_indicator
      show_tokens:
        color: '200000'
        led1: led_missile_count_nw
        led2: led_missile_count_ne
  missiles_play_lights_3:
    indicator_3:
      loops: -1
      key: missiles_indicator
      show_tokens:
        color: '200000'
        led1: led_missile_count_nw
        led2: led_missile_count_ne
        led3: led_missile_count_se
  missiles_play_lights_4:
    indicator_4:
      loops: -1
      key: missiles_indicator
      show_tokens:
        color: '200000'
        led1: led_missile_count_nw
        led2: led_missile_count_ne
        led3: led_missile_count_se
        led4: led_missile_count_sw

variable_player:
  missile_bank_1_shot_hit:
   score: 1000 * current_player.multiplier
  missile_bank_2_shot_hit:
   score: 1000 * current_player.multiplier
  missile_bank_3_shot_hit:
   score: 1000 * current_player.multiplier
  missile_collected:
    missiles: 1
    score: (2500 + (500 * current_player.missiles)) * current_player.multiplier

sound_player:
  missile_collected: missile_collected
  missiles_shot_group_unlit_hit: missile_hit
  missile_play_missed_sound: missile_already_hit
