#config_version=5
mode:
  start_events: mode_base_starting
  priority: 100

shot_profiles:
  missiles:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color

shots:
  purple_1_shot:
    switch: s_purple_1
    profile: missiles
    show_tokens:
      led: led_upgrade_bank_1
      color: FF0000
  purple_2_shot:
    switch: s_purple_2
    profile: missiles
    show_tokens:
      led: led_upgrade_bank_2
      color: FF0000
  purple_3_shot:
    switch: s_purple_3
    profile: missiles
    show_tokens:
      led: led_upgrade_bank_3
      color: FF0000

shot_groups:
  missiles_shot_group:
    shots: purple_1_shot, purple_2_shot, purple_3_shot
    reset_events: missiles_shot_group_lit_complete
    enable_events: mode_missiles_started
    disable_events: mode_missiles_ending

event_player:
  missiles_shot_group_lit_complete: missile_collected

show_player:
  missile_collected:
    missiles_collected:
      loops: 0

variable_player:
  purple_1_shot_hit:
    score:
      int: (100 + (100 * current_player.missiles)) * current_player.multiplier
  purple_2_shot_hit:
    score:
      int: (100 + (100 * current_player.missiles)) * current_player.multiplier
  purple_3_shot_hit:
    score:
      int: (100 + (100 * current_player.missiles)) * current_player.multiplier
  missile_collected:
    missiles: 1
    score:
      int: (500 + (200 * current_player.missiles)) * current_player.multiplier
