#config_version=5

# https://commons.wikimedia.org/wiki/File:Callao_Cave_Chapel.jpg

mode:
  start_events: room_1g_continue, room_1g_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1f_enter, room_1g_exit
  priority: 300

shots:
  room_1g_exit_west_shot:
    switch: s_vuk
    profile: exit_door
    enable_events: mode_room_1g_the_pit_started
    disable_events: room_1g_exit_west_shot_hit
    reset_events: room_1g_exit_west_shot_hit
    show_tokens:
      led: gi_strip_9
      color: door_blue

slides:
  room_1g_the_pit_backglass_slide:
    widgets:
      - type: image
        image: room_1g_the_pit_backglass
    transition: fade
    transition_out: fade
  room_1g_the_pit_splash_slide:
    widgets:
      - type: image
        image: room_1g_the_pit_splash

slide_player:
  mode_room_1g_the_pit_started:
    room_1g_the_pit_backglass_slide:
      target: backglass
    room_1g_the_pit_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1g_the_pit_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
    small_theater_chase:
      key: room_1g_drop_show
      loops: -1
      speed: 6
      priority: 50
      show_tokens:
        color: door_blue
        led_1: led_drop_1
        led_2: gi_back_right
        led_3: led_drop_2
        led_4: gi_back_right
        led_5: led_drop_3
        led_6: gi_back_right
  show_mode_status_report:
    room_1g_the_pit_status_report:
      loops: 0
  flipper_cradle_release:
    room_1g_the_pit_status_report:
      action: stop

event_player:
  mode_room_1g_the_pit_started:
    cmd_backbox_show:
      show_type: gradient
      color_start: "101000"
      color_end: "000000"
    drop_targets_continue:
    cmd_map_position:
      room: '1g'
      visit: True
    cmd_play_map_music:
      music: music_crateria
  room_1g_exit_west_shot_hit.1: drop_targets_save
  room_1g_exit_west_shot_hit.2: room_1f_enter

variable_player:
  mode_room_1g_the_pit_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1g
      action: set
