#config_version=5

# https://commons.wikimedia.org/wiki/File:World_War_II_Oil_Storage_Tunnels_in_Darwin,_Northern_Territory,_Australia.jpg

mode:
  start_events: room_1n_continue, room_1n_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1l_enter, room_1p_enter, room_1n_exit
  priority: 300

shots:
  room_1n_exit_north_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_1n_the_hull_started
    disable_events: room_1n_exit_north_shot_hit
    reset_events: room_1n_exit_north_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1n_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: mode_room_1n_the_hull_started
    disable_events: room_1n_exit_south_shot_hit
    reset_events: room_1n_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue

slides:
  room_1n_the_hull_backglass_slide:
    widgets:
      - type: image
        image: room_1n_the_hull_backglass
    transition: fade
    transition_out: fade
  room_1n_the_hull_powered_backglass_slide:
    widgets:
      - type: image
        image: room_1n_the_hull_powered_backglass
    transition: fade
    transition_out: fade
  room_1n_the_hull_splash_slide:
    widgets:
      - type: image
        image: room_1n_the_hull_splash

slide_player:
  mode_room_1n_the_hull_started_no_charge:
    room_1n_the_hull_backglass_slide:
      target: backglass
  mode_room_1n_the_hull_started_charge:
    room_1n_the_hull_powered_backglass_slide:
      target: backglass
  mode_room_1n_the_hull_started:
    room_1n_the_hull_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1n_the_hull_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1n_the_hull_status_report:
      loops: 0
  flipper_cradle_release:
    room_1n_the_hull_status_report:
      action: stop

event_player:
  mode_room_1n_the_hull_started:
    cmd_backbox_show:
      show_type: spectrum
      color1: '400000'
      color2: '000000'
      color3: '402000'
    drop_targets_continue:
    cmd_map_position:
      room: '1n'
      visit: True
  mode_room_1n_the_hull_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1n_the_hull_started_no_charge
  mode_room_1n_the_hull_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1n_the_hull_started_charge
  room_1n_exit_north_shot_hit.1: drop_targets_save
  room_1n_exit_north_shot_hit.2: room_1l_enter
  room_1n_exit_south_shot_hit.1: drop_targets_save
  room_1n_exit_south_shot_hit.2: room_1p_enter

variable_player:
  mode_room_1n_the_hull_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1n
      action: set
