#config_version=5

# https://commons.wikimedia.org/wiki/File:World_War_II_Oil_Storage_Tunnels_in_Darwin,_Northern_Territory,_Australia.jpg

mode:
  start_events: room_1n_continue, room_1n_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1l_enter, room_1p_enter, room_1n_exit
  priority: 300


timers:
  room_1n_light_shot_timer:
    start_value: 1
    end_value: 4
    restart_on_complete: true
    tick_interval: 8s
    control_events:
      - event: room_1n_start_timer
        action: restart
      - event: mode_room_1n_the_hull_started
        action: stop


shot_profiles:
  room_1n_robot:
    states:
      - name: lit
        show: blink_light
        speed: 4
        show_tokens:
          color: 'a9e82c'

shots:
  room_1n_exit_north_shot:
    switches: s_ramp_enter
    profile: exit_door_optimum
    enable_events: metroid_open_doors
    disable_events: room_1n_exit_north_shot_hit, metroid_close_doors
    reset_events: room_1n_exit_north_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1n_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1n_exit_south_shot_hit, metroid_close_doors
    reset_events: room_1n_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1n_work_robot_shot_1:
    switch: s_left_passage
    profile: room_1n_robot
    enable_events: room_1k_show_robot_1
    disable_events: mode_room_1n_the_hull_started, room_1k_hide_robot_1
    show_tokens:
      led: led_enter_secret_passage
  room_1n_work_robot_shot_2:
    hit_events: left_orbit_hit
    profile: room_1n_robot
    enable_events: room_1k_show_robot_2
    disable_events: mode_room_1n_the_hull_started, room_1k_hide_robot_2
    show_tokens:
      led: led_enter_left_orbit
  room_1n_work_robot_shot_3:
    hit_events: right_orbit_hit
    profile: room_1n_robot
    enable_events: room_1k_show_robot_3
    disable_events: mode_room_1n_the_hull_started, room_1k_hide_robot_3
    show_tokens:
      led: led_enter_right_orbit

slides:
  room_1n_the_hull_backglass_slide:
    widgets:
      - type: image
        image: room_1n_the_hull_backglass
    transition: fade
    transition_out: fade
  room_1n_the_hull_powered_backglass_slide:
    widgets:
      - type: image
        image: room_1n_the_hull_powered_backglass
    transition: fade
    transition_out: fade
  room_1n_the_hull_splash_slide:
    widgets:
      - type: image
        image: room_1n_the_hull_splash

slide_player:
  mode_room_1n_the_hull_started_no_charge:
    room_1n_the_hull_backglass_slide:
      target: backglass
  mode_room_1n_the_hull_started_charge:
    room_1n_the_hull_powered_backglass_slide:
      target: backglass
  mode_room_1n_the_hull_started:
    room_1n_the_hull_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1n_the_hull_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  room_1n_work_robot_shot_1_hit:
    special_score_green:
      loops: 0
  room_1n_work_robot_shot_2_hit:
    special_score_green:
      loops: 0
  room_1n_work_robot_shot_3_hit:
    special_score_green:
      loops: 0
  show_mode_status_report:
    room_1n_the_hull_status_report:
      loops: 0
  flipper_cradle_release:
    room_1n_the_hull_status_report:
      action: stop

event_player:
  mode_room_1n_the_hull_started:
    cmd_backbox_show:
      show_type: spectrum
      color1: '400000'
      color2: '000000'
      color3: '402000'
    drop_targets_continue:
    cmd_map_position:
      room: '1n'
      visit: True
    metroid_open_doors:
    room_1n_start_timer:
  mode_room_1n_the_hull_started_no_charge:
    cmd_play_map_music:
      music: music_wrecked_ship
  mode_room_1n_the_hull_started_charge:
    cmd_play_map_music:
      music: music_wrecked_ship_generator
  mode_room_1n_the_hull_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1n_the_hull_started_no_charge
  mode_room_1n_the_hull_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1n_the_hull_started_charge
  timer_room_1n_light_shot_timer_tick{ticks == 1}: room_1k_show_robot_1, room_1k_hide_robot_3
  timer_room_1n_light_shot_timer_tick{ticks == 2}: room_1k_show_robot_2, room_1k_hide_robot_1
  timer_room_1n_light_shot_timer_tick{ticks == 3}: room_1k_show_robot_3, room_1k_hide_robot_2
  room_1n_exit_north_shot_hit.1: drop_targets_save
  room_1n_exit_north_shot_hit.2: room_1l_enter
  room_1n_exit_south_shot_hit.1: drop_targets_save
  room_1n_exit_south_shot_hit.2: room_1p_enter
  room_1n_work_robot_shot_1_hit: room_1n_add_robot_1
  room_1n_work_robot_shot_2_hit: room_1n_add_robot_2
  room_1n_work_robot_shot_3_hit: room_1n_add_robot_3

variable_player:
  mode_room_1n_the_hull_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1n
      action: set
  room_1n_work_robot_shot_1_hit:
    score: (((current_player.area_bonus_sw + 1) * 50000) + (current_player.wrecked_ship_charge * 5000) + (current_player.room_1n_robots_1 * 10420)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_sw + 1) * 50000) + (current_player.wrecked_ship_charge * 5000) + (current_player.room_1n_robots_1 * 10420)) * current_player.multiplier
      action: set
  room_1n_work_robot_shot_2_hit:
    score: (((current_player.area_bonus_nw + 1) * 100000) + (current_player.wrecked_ship_charge * 5000) + (current_player.room_1n_robots_2 * 10800)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_nw + 1) * 100000) + (current_player.wrecked_ship_charge * 5000) + (current_player.room_1n_robots_2 * 10800)) * current_player.multiplier
      action: set
  room_1n_work_robot_shot_3_hit:
    score: (((current_player.area_bonus_ne + 1) * 75000) + (current_player.wrecked_ship_charge * 5000) + (current_player.room_1n_robots_3 * 10600)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_ne + 1) * 75000) + (current_player.wrecked_ship_charge * 5000) + (current_player.room_1n_robots_3 * 10600)) * current_player.multiplier
      action: set
  room_1n_add_robot_1:
    room_1n_robots_1: 1
  room_1n_add_robot_2:
    room_1n_robots_2: 1
  room_1n_add_robot_3:
    room_1n_robots_3: 1
