#config_version=5

mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 800

multiballs:
  zero_suit_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 20s
    start_events: zero_suit_multiball_should_start

shot_profiles:
  zero_suit:
    states:
      - name: lit
        show: single_rainbow
        speed: 45

shots:
  zero_suit_start_shot:
    switch: s_shatz
    profile: zero_suit
    enable_events: zero_suit_enable_shot
    disable_events: mode_zero_suit_multiball_started, zero_suit_disable_shot, zero_suit_start_shot_hit
    show_tokens:
      led: led_zero_suit


achievements:
  zero_suit_bridge:
    show_tokens:
      led: led_goal_1
      color: 'C02000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: bridge_should_explode
    select_events: power_bomb_collected
    enable_events: zero_suit_initialize
    reset_events: zero_suit_reset
    sync_ms: 1000
  zero_suit_chozo:
    show_tokens:
      led: led_goal_2
      color: '00C000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: chozo_multiball_bashed
    select_events: captive_shot_hit
    enable_events: zero_suit_initialize
    reset_events: zero_suit_reset
    sync_ms: 1000
  zero_suit_miniboss:
    show_tokens:
      led: led_goal_3
      color: '0000C0'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: miniboss_battle_mode_should_start
    select_events: miniboss_enable_level_3
    enable_events: zero_suit_initialize
    reset_events: zero_suit_reset
    sync_ms: 1000
  zero_suit_room:
    show_tokens:
      led: led_goal_4
      color: 'B0C000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: cmd_map_complete
    select_events: cmd_map_position
    enable_events: zero_suit_initialize
    reset_events: zero_suit_reset
    sync_ms: 1000

achievement_groups:
  zero_suit_achievements:
    achievements: zero_suit_bridge, zero_suit_chozo, zero_suit_miniboss, zero_suit_room
    enable_events: zero_suit_initialize
    events_when_all_completed: zero_suit_win_all

sound_player:
  zero_suit_enable_shot: shoot_the_zero_suit

event_player:
  mode_zero_suit_multiball_started{current_player.ball == 1}: zero_suit_initialize
  mode_zero_suit_multiball_started{current_player.zero_suit_ready == 1}: zero_suit_check_for_boss
  zero_suit_check_for_boss{current_player.continue_room != '1j' and current_player.continue_room != '1x' and current_player.continue_room != '2g' and current_player.continue_room != '2q'}: zero_suit_enable_shot
  zero_suit_check_for_boss{current_player.continue_room == '1j' and current_player.boss_phantoon_hp < 1}: zero_suit_enable_shot
  zero_suit_check_for_boss{current_player.continue_room == '1x' and current_player.boss_kraid_hp < 1}: zero_suit_enable_shot
  zero_suit_check_for_boss{current_player.continue_room == '2g' and current_player.boss_draygon_hp < 1}: zero_suit_enable_shot
  zero_suit_check_for_boss{current_player.continue_room == '2q' and current_player.boss_ridley_hp < 1}: zero_suit_enable_shot
  zero_suit_win_all{device.playfields.playfield.balls == 1}: zero_suit_enable_shot
  multiball_chozo_ended{device.playfields.playfield.balls == 1 and current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  mode_room_1j_phantoon_open_door{current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  mode_room_1x_kraid_open_door{current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  mode_room_2g_draygon_open_door{current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  mode_room_2q_ridley_open_door{current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  multiball_gunship_ended{device.playfields.playfield.balls == 1 and current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  multiball_room_1m_generator_multiball_ended{device.playfields.playfield.balls == 1 and current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  multiball_room_1r_battle_ended{device.playfields.playfield.balls == 1 and current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  multiball_twitch_bit_donation_multiball_ended{device.playfields.playfield.balls == 1 and current_player.zero_suit_ready == 1}: zero_suit_enable_shot
  multiball_chozo_started: zero_suit_disable_shot
  multiball_room_1j_phantoon_boss_multiball_started: zero_suit_disable_shot
  multiball_room_1x_kraid_boss_multiball_started: zero_suit_disable_shot
  multiball_room_2g_draygon_boss_multiball_started: zero_suit_disable_shot
  multiball_room_2q_ridley_boss_multiball_started: zero_suit_disable_shot
  multiball_gunship_started: zero_suit_disable_shot
  multiball_room_1m_generator_multiball_started: zero_suit_disable_shot
  multiball_room_1r_battle_started: zero_suit_disable_shot
  multiball_twitch_bit_donation_multiball_started: zero_suit_disable_shot
  zero_suit_start_shot_hit: zero_suit_multiball_should_start, metroid_exclusive_started
  multiball_zero_suit_multiball_ended: metroid_exclusive_ended, zero_suit_reset
  


variable_player:
  zero_suit_win_all:
    zero_suit_ready:
      action: set
      int: 1
  multiball_zero_suit_multiball_started:
    zero_suit_ready:
      action: set
      int: 0
