#config_version=5

mode:
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 800

multiballs:
  zero_suit_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 20s
    start_events: zero_suit_multiball_should_start

shot_profiles:
  zero_suit:
    states:
      - name: lit
        show: single_rainbow
        speed: 45

shots:
  zero_suit_start_shot:
    switch: s_shatz
    profile: zero_suit
    enable_events: zero_suit_enable_shot
    disable_events: mode_zero_suit_multiball_started
    show_tokens:
      led: led_zero_suit


achievements:
  zero_suit_bridge:
    show_tokens:
      led: led_goal_1
      color: 'C02000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: bridge_should_explode
    select_events: power_bomb_collected
    enable_events: zero_suit_initialize
    sync_ms: 1000
  zero_suit_chozo:
    show_tokens:
      led: led_goal_2
      color: '00C000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: chozo_multiball_bashed
    select_events: captive_shot_hit
    enable_events: zero_suit_initialize
    sync_ms: 1000
  zero_suit_miniboss:
    show_tokens:
      led: led_goal_3
      color: '0000C0'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: miniboss_battle_mode_should_start
    select_events: miniboss_enable_level_3
    enable_events: zero_suit_initialize
    sync_ms: 1000
  zero_suit_room:
    show_tokens:
      led: led_goal_4
      color: 'B0C000'
    show_when_selected: blink_light
    show_when_completed: led_color
    complete_events: cmd_map_complete
    select_events: cmd_map_position
    enable_events: zero_suit_initialize
    sync_ms: 1000

achievement_groups:
  zero_suit_achievements:
    achievements: zero_suit_bridge, zero_suit_chozo, zero_suit_miniboss, zero_suit_room
    enable_events: zero_suit_initialize
    events_when_all_completed: zero_suit_win_all

event_player:
  mode_zero_suit_multiball_started{current_player.ball == 1}: zero_suit_initialize
  zero_suit_win_all{device.playfields.playfield.balls == 1}: zero_suit_enable_shot
