#config_version=5
mode:
  start_events: room_2j_lake_of_fire_continue, room_2j_continue, room_2j_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2i_enter
  priority: 300

shots:
  room_2j_exit_west_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: mode_room_2j_lake_of_fire_started
    disable_events: room_2j_exit_west_shot_hit
    reset_events: room_2j_exit_west_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue


slides:
  room_2j_lake_of_fire_backglass_slide:
    widgets:
      - type: image
        image: room_2j_lake_of_fire_backglass
    transition: fade
    transition_out: fade
  room_2j_lake_of_fire_splash_slide:
    widgets:
      - type: image
        image: room_2j_lake_of_fire_splash

slide_player:
  mode_room_2j_lake_of_fire_started:
    room_2j_lake_of_fire_backglass_slide:
      target: backglass
    room_2j_lake_of_fire_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2j_lake_of_fire_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: 'FF0000'
        color2: 'FF0000'
  show_mode_status_report:
    room_2j_lake_of_fire_status_report:
      loops: 0
  flipper_cradle_release:
    room_2j_lake_of_fire_status_report:
      action: stop

event_player:
  mode_room_2j_lake_of_fire_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2j'
      visit: True
  room_2j_exit_west_shot_hit.1: drop_targets_save
  room_2j_exit_west_shot_hit.2: room_2i_enter

variable_player:
  mode_room_2j_lake_of_fire_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2j
      action: set
