#config_version=5
mode:
  start_events: room_2j_lake_of_fire_continue, room_2j_continue, room_2j_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2i_enter, room_2k_enter, room_2j_exit
  priority: 300


shot_profiles:
  room_2j_mode_shot:
    advance_on_hit: False
    states:
      - name: bad
        show: two_color_blink
        loops: -1
        speed: 1.5
        show_tokens:
          color1: '808000'
          color2: '805000'
      - name: good
        show: two_color_blink
        loops: -1
        speed: 3
        show_tokens:
          color1: '00FFFF'
          color2: '00FF00'
  room_2j_advance_shot:
    states:
      - name: lit
        show: small_theater_chase
        loops: -1
        speed: 40
        priority: 100
        show_tokens:
          color: 'FFFFFF'


shots:
  room_2j_exit_west_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_2j_exit_west_shot_hit, metroid_close_doors
    reset_events: room_2j_exit_west_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_2j_exit_east_shot:
    switch: s_ramp_enter
    profile: exit_door_optimum
    enable_events: metroid_open_doors
    disable_events: room_2j_exit_east_shot_hit, metroid_close_doors
    reset_events: room_2j_exit_east_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_2j_shot_1:
    switch: s_scoop
    profile: room_2j_mode_shot
    advance_events: room_2j_light_first_shot
    show_tokens:
      led: led_enter_scoop
  room_2j_shot_2:
    switch: s_left_passage
    profile: room_2j_mode_shot
    show_tokens:
      led: led_enter_secret_passage
  room_2j_shot_3:
    hit_events: right_orbit_hit
    profile: room_2j_mode_shot
    show_tokens:
      led: led_enter_right_orbit
  room_2j_shot_4:
    switch: s_side_ramp_made
    profile: room_2j_mode_shot
    show_tokens:
      led: led_enter_side_ramp
  room_2j_advance_shot_1:
    hit_events: left_sling_shot_hit
    profile: room_2j_advance_shot
    show_tokens:
      led_1: gi_left_sling_bottom
      led_2: gi_left_sling_top
      led_3: led_null
      led_4: led_null
      led_5: gi_left_sling_top
      led_6: gi_left_sling_bottom
  room_2j_advance_shot_2:
    hit_events: right_sling_shot_hit
    profile: room_2j_advance_shot
    show_tokens:
      led_1: gi_right_sling_bottom
      led_2: gi_right_sling_top
      led_3: led_null
      led_4: led_null
      led_5: gi_left_sling_top
      led_6: gi_left_sling_bottom
  room_2j_advance_shot_3:
    hit_events: upper_left_sling_shot_hit
    profile: room_2j_advance_shot
    show_tokens:
      led_1: gi_missile_bank
      led_2: gi_middle_sling
      led_3: led_null
      led_4: led_null
      led_5: gi_middle_sling
      led_6: gi_missile_bank
  room_2j_advance_shot_4:
    hit_events: upper_right_sling_shot_hit
    profile: room_2j_advance_shot
    show_tokens:
      led_1: gi_under_side_ramp
      led_2: led_null
      led_3: gi_under_side_ramp
      led_4: led_null
      led_5: gi_under_side_ramp
      led_6: led_null



shot_groups:
  room_2j_collect_shots:
    shots: room_2j_shot_1, room_2j_shot_2, room_2j_shot_3, room_2j_shot_4
    enable_events: mode_room_2j_lake_of_fire_started
    disable_events: mode_room_2j_lake_of_fire_ending
    reset_events: mode_room_2j_lake_of_fire_started
    rotate_events: room_2j_rotate


slides:
  room_2j_lake_of_fire_backglass_slide:
    widgets:
      - type: image
        image: room_2j_lake_of_fire_backglass
    transition: fade
    transition_out: fade
  room_2j_lake_of_fire_splash_slide:
    widgets:
      - type: image
        image: room_2j_lake_of_fire_splash

slide_player:
  mode_room_2j_lake_of_fire_started:
    room_2j_lake_of_fire_backglass_slide:
      target: backglass
    room_2j_lake_of_fire_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2j_lake_of_fire_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: 'FF0000'
        color2: 'FF0000'
  show_mode_status_report:
    room_2j_lake_of_fire_status_report:
      loops: 0
  flipper_cradle_release:
    room_2j_lake_of_fire_status_report:
      action: stop
  room_2j_collect_shots_good_hit:
    room_2j_correct_hit:
      speed: 50
      loops: 0
  player_room_2j_super_jackpot:
    special_score_red:
      loops: 0



event_player:
  mode_room_2j_lake_of_fire_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2j'
      visit: True
    cmd_play_map_music:
      music: music_norfair
    metroid_open_doors:
    room_2j_light_first_shot:
  room_2j_advance_shot_1_hit: room_2j_rotate
  room_2j_advance_shot_2_hit: room_2j_rotate
  room_2j_advance_shot_3_hit: room_2j_rotate
  room_2j_advance_shot_4_hit: room_2j_rotate
  room_2j_exit_west_shot_hit.1: drop_targets_save
  room_2j_exit_west_shot_hit.2: room_2i_enter
  room_2j_exit_east_shot_hit.1: drop_targets_save
  room_2j_exit_east_shot_hit.2: room_2k_enter

variable_player:
  mode_room_2j_lake_of_fire_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2j
      action: set
  room_2j_rotate:
    room_2j_super_jackpot: 20000 * current_player.multiplier
  player_room_2j_super_jackpot:
    room_special_score:
      int: current_player.room_2j_super_jackpot
      action: set

