#config_version=5

# https://www.metroid-database.com/bestiary/bestiary.php?b=264

mode:
  start_events: room_2g_continue, room_2g_enter
  stop_events: game_ending, ball_ending, metroid_base_ended
  priority: 300

animations:
  room_2g_draygon_standard:
    - property: x
      value: 100
      relative: true
      duration: 1s
    - property: y
      value: 100
      relative: true
      duration: 1s
      timing: with_previous
    - property: x
      value: 100
      relative: true
      duration: 1s
    - property: y
      value: -100
      relative: true
      duration: 1s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1s
    - property: y
      value: -100
      relative: true
      duration: 1s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1s
    - property: y
      value: 100
      relative: true
      duration: 1s
      timing: with_previous
      repeat: true

slides:
  room_2g_draygon_backglass_slide:
    widgets:
      - type: image
        image: room_2g_draygon_backglass
        animations:
          show_slide: room_2g_draygon_standard
    transition: fade
    transition_out: fade
  room_2g_draygon_splash_slide:
    widgets:
      - type: image
        image: room_2g_draygon_splash

slide_player:
  mode_room_2g_draygon_started:
    room_2g_draygon_backglass_slide:
      target: backglass
    room_2g_draygon_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2g_draygon_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_2g_draygon_status_report:
      loops: 0
  flipper_cradle_release:
    room_2g_draygon_status_report:
      action: stop

event_player:
  mode_room_2g_draygon_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2g'
      visit: True

variable_player:
  mode_room_2g_draygon_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2g
      action: set
