#config_version=5

# https://www.metroid-database.com/bestiary/bestiary.php?b=264

mode:
  start_events: room_2g_continue, room_2g_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2g_exit
  priority: 300

multiballs:
  room_2g_draygon_boss_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 20s
    start_events: mode_room_2g_draygon_start_multiball

shots:
  room_2g_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: mode_room_2g_draygon_open_door
    disable_events: mode_room_2g_draygon_started, mode_room_2g_draygon_battle
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_2g_exit_west_shot:
    switch: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_2g_draygon_open_door
    disable_events: mode_room_2g_draygon_started, mode_room_2g_draygon_battle
    show_tokens:
      led: led_enter_ramp
      color: door_blue


animations:
  room_2g_draygon_standard:
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
      repeat: true

slides:
  room_2g_draygon_backglass_slide:
    widgets:
      - type: image
        image: room_2g_draygon_backglass
        x: 310
        y: 590
        animations:
          show_slide: room_2g_draygon_standard
    transition: fade
    transition_out: fade
  room_2g_draygon_splash_slide:
    widgets:
      - type: image
        image: room_2g_draygon_splash

slide_player:
  mode_room_2g_draygon_started:
    room_2g_draygon_backglass_slide:
      target: backglass
    room_2g_draygon_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2g_draygon_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '4080FF'
        color2: '4080C0'
  show_mode_status_report:
    room_2g_draygon_status_report:
      loops: 0
  flipper_cradle_release:
    room_2g_draygon_status_report:
      action: stop

event_player:
  mode_room_2g_draygon_started:
    cmd_backbox_show:
      show_type: pour
      count: 8
      min_length: 3
      max_length: 10
      color: "000040"
    drop_targets_continue:
    cmd_map_position:
      room: '2g'
      visit: True
  mode_room_2g_draygon_started{current_player.boss_draygon_hp < 1}: mode_room_2g_draygon_over, mode_room_2g_draygon_open_door, room_2g_show_defeated_backglass
  mode_room_2g_draygon_started{current_player.boss_draygon_hp > 0}: mode_room_2g_draygon_battle, metroid_exclusive_started
  mode_room_2g_draygon_battle{current_player.boss_draygon_multiball_played == 0}: mode_room_2g_draygon_start_multiball

  multiball_room_2g_draygon_boss_multiball_ended{current_player.boss_kraid_hp < 1}: mode_room_2g_draygon_open_door, boss_defeated_music



variable_player:
  mode_room_2g_draygon_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2g
      action: set
  mode_room_2g_draygon_start_multiball:
    boss_draygon_multiball_played:
      int: 1
      action: set
