#config_version=5

# https://www.metroid-database.com/bestiary/bestiary.php?b=264

mode:
  start_events: room_2g_continue, room_2g_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2g_exit
  priority: 300

multiballs:
  room_2g_draygon_boss_multiball:
    ball_count: 4
    ball_count_type: total
    shoot_again: 20s
    start_events: mode_room_2g_draygon_start_multiball


timers:
  room_2g_draygon_vulnerable_timer:
    start_value: 0
    end_value: 10
    tick_interval: 1.0s
    control_events:
      - event: mode_room_2g_draygon_started
        action: stop
      - event: room_2g_draygon_should_die
        action: stop
      - event: mode_room_2g_draygon_vulnerable
        action: restart


shot_profiles:
  room_2g_weak_spot:
    states:
      - name: lit
        sync_ms: 4000
        show: fade_one_light
  room_2g_strong_spot:
    states:
      - name: lit
        sync_ms: 4000
        show: fade_one_light
        speed: 2
  room_2g_vulnerable_spot:
    states:
    - name: lit
      show: blink_light
      loops: -1


shots:
  room_2g_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: mode_room_2g_draygon_open_door
    disable_events: mode_room_2g_draygon_started, mode_room_2g_draygon_battle
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue
  room_2g_exit_west_shot:
    switch: s_ramp_enter
    profile: exit_door
    enable_events: mode_room_2g_draygon_open_door
    disable_events: mode_room_2g_draygon_started, mode_room_2g_draygon_battle
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_2g_boss_weak_captive_shot:
    switch: s_captive_ball
    profile: room_2g_weak_spot
    enable_events: mode_room_2g_draygon_battle
    disable_events: mode_room_2g_draygon_over
    show_tokens:
      led: led_captive_ball
      color: yellow
  room_2g_boss_strong_side_ramp_shot:
    switch: s_side_ramp_made
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_enter_side_ramp
      color: blue
  room_2g_boss_strong_secret_shot:
    switch: s_left_passage
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_enter_secret_passage
      color: blue
  room_2g_boss_strong_back_ramp_shot:
    switch: s_ramp_enter
    profile: room_2g_weak_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_enter_ramp
      color: blue
  room_2g_boss_strong_rollover_shot:
    switch: s_rollover_button
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_rollover
      color: blue
  room_2g_boss_strong_scoop_shot:
    switch: s_scoop
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_enter_scoop
      color: blue
  room_2g_boss_strong_right_orbit_shot:
    hit_events: right_orbit_hit
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_enter_right_orbit
      color: blue
  room_2g_boss_strong_left_orbit_shot:
    hit_events: left_orbit_hit
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_enter_left_orbit
      color: blue
  room_2g_boss_strong_center_1_shot:
    switch: s_purple_1
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_upgrade_bank_1
      color: blue
  room_2g_boss_strong_center_2_shot:
    switch: s_purple_2
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_upgrade_bank_2
      color: blue
  room_2g_boss_strong_center_3_shot:
    switch: s_purple_3
    profile: room_2g_strong_spot
    enable_events: mode_room_2g_draygon_battle, mode_room_2g_draygon_recovered
    disable_events: mode_room_2g_draygon_over, mode_room_2g_draygon_vulnerable
    show_tokens:
      led: led_upgrade_bank_3
      color: blue


animations:
  room_2g_draygon_standard:
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: 100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: -100
      relative: true
      duration: 1.0s
      timing: with_previous
    - property: x
      value: -100
      relative: true
      duration: 1.0s
    - property: y
      value: 100
      relative: true
      duration: 1.0s
      timing: with_previous
      repeat: true

slides:
  room_2g_draygon_backglass_slide:
    widgets:
      - type: image
        image: room_2g_draygon_backglass
        x: 310
        y: 590
        animations:
          show_slide: room_2g_draygon_standard
    transition: fade
    transition_out: fade
  room_2g_draygon_splash_slide:
    widgets:
      - type: image
        image: room_2g_draygon_splash

slide_player:
  mode_room_2g_draygon_started:
    room_2g_draygon_backglass_slide:
      target: backglass
    room_2g_draygon_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2g_draygon_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '4080FF'
        color2: '4080C0'
  show_mode_status_report:
    room_2g_draygon_status_report:
      loops: 0
  flipper_cradle_release:
    room_2g_draygon_status_report:
      action: stop

event_player:
  mode_room_2g_draygon_started:
    cmd_backbox_show:
      show_type: pour
      count: 8
      min_length: 3
      max_length: 10
      color: "000040"
    drop_targets_continue:
    cmd_map_position:
      room: '2g'
      visit: True
  mode_room_2g_draygon_started{current_player.boss_draygon_hp < 1}: mode_room_2g_draygon_over, mode_room_2g_draygon_open_door, room_2g_show_defeated_backglass
  mode_room_2g_draygon_started{current_player.boss_draygon_hp > 0}: mode_room_2g_draygon_battle, metroid_exclusive_started
  mode_room_2g_draygon_battle{current_player.boss_draygon_multiball_played == 0}: mode_room_2g_draygon_start_multiball
  room_2g_boss_weak_captive_shot_hit: draygon_hit_strong

  multiball_room_2g_draygon_boss_multiball_ended{current_player.boss_draygon_hp < 1}: mode_room_2g_draygon_open_door, boss_defeated_music
  draygon_hit_strong:
    mode_room_2g_draygon_vulnerable:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: 'FF0000'
      speed: 1
      repeat: 2
      direction: up
  timer_room_2g_draygon_vulnerable_timer_complete: mode_room_2g_draygon_recovered



variable_player:
  mode_room_2g_draygon_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2g
      action: set
  mode_room_2g_draygon_start_multiball:
    boss_draygon_multiball_played:
      int: 1
      action: set
