#config_version=5

# https://commons.wikimedia.org/wiki/File:Biosphere_2_-_1998_b.jpg

mode:
  start_events: room_1w_continue, room_1w_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1u_enter, room_1x_enter, room_1w_exit
  priority: 300

shots:
  room_1w_exit_north_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: mode_room_1w_biosphere_started
    disable_events: room_1w_exit_north_shot_hit
    reset_events: room_1w_exit_north_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_1w_exit_east_shot:
    hit_events: right_orbit_hit
    profile: exit_door
    enable_events: mode_room_1w_biosphere_started
    disable_events: room_1w_exit_east_shot_hit
    reset_events: room_1w_exit_east_shot_hit
    show_tokens:
      led: led_enter_right_orbit
      color: door_blue

slides:
  room_1w_biosphere_backglass_slide:
    widgets:
      - type: image
        image: room_1w_biosphere_backglass
    transition: fade
    transition_out: fade
  room_1w_biosphere_splash_slide:
    widgets:
      - type: image
        image: room_1w_biosphere_splash

slide_player:
  mode_room_1w_biosphere_started:
    room_1w_biosphere_backglass_slide:
      target: backglass
    room_1w_biosphere_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1w_biosphere_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1w_biosphere_status_report:
      loops: 0
  flipper_cradle_release:
    room_1w_biosphere_status_report:
      action: stop

event_player:
  mode_room_1w_biosphere_started:
    cmd_backbox_show:
      show_type: plasma
      color1: "002020"
      color2: "001818"
      color3: "001010"
      color4: "000C0C"
      color5: "000A0A"
      color6: "000808"
      color7: "000404"
      color8: "000202"
      decay_r: 2.0
      decay_g: 1.7
      decay_b: 1.8
      invert: True
    drop_targets_continue:
    cmd_map_position:
      room: '1w'
      visit: True
    cmd_play_map_music:
      music: music_brinstar_calm
  room_1w_exit_north_shot_hit.1: drop_targets_save
  room_1w_exit_north_shot_hit.2: room_1u_enter
  room_1w_exit_east_shot_hit.1: drop_targets_save
  room_1w_exit_east_shot_hit.2: room_1x_enter

variable_player:
  mode_room_1w_biosphere_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1w
      action: set
