#config_version=5
mode:
  priority: 1000
  start_events: game_ending
  code: match.MyMatch
  game_mode: False
  use_wait_queue: true

mode_settings:
  non_match_number_step: 10

queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: slide_no_match_slide_removed
    pass_args: true
  match_has_match:
    post: has_match
    wait_for: slide_match_slide_removed
    pass_args: true

shows:
  no_match_show:
    - duration: 3.5s
      slides:
        no_match_drama_slide:
          widgets:
            - type: text
              text: (winner_number)
              opacity: 0.0
              color: red
              style: dmd_big
              animations:
                show_slide:
                  - property: opacity
                    value: 0
                    duration: 1s
                  - property: opacity
                    value: 1
                    duration: 2s
            - type: image
              image: match_explosion
              fps: 17
    - duration: 3s
      slides:
        no_match_slide:
          widgets:
            - type: text
              text: NO MATCH
              color: 009cff
              style: dmd_big
            - type: text
              text: (match_number0)
              y: 31
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: top
            - type: text
              text: (match_number1)
              y: 31
              x: right-10
              anchor_x: right
              anchor_y: top
              style: dmd_med
            - type: text
              text: (match_number2)
              y: 0
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: bottom
              number_grouping: true
            - type: text
              text: (match_number3)
              y: 0
              x: right-10
              anchor_x: right
              anchor_y: bottom
              style: dmd_med

  has_match_show:
    - duration: 3.5s
      slides:
        match_drama_slide:
          widgets:
            - type: text
              text: (winner_number)
              opacity: 0.0
              color: red
              style: dmd_big
              animations:
                show_slide:
                  - property: opacity
                    value: 0
                    duration: 1s
                  - property: opacity
                    value: 1
                    duration: 2s
            - type: image
              image: match_explosion
              fps: 17
    - duration: 3s
      slides:
        match_slide:
          widgets:
            - type: text
              text: MATCH
              color: red
              style: dmd_big
              y: 21
            - type: text
              text: (winner_number)
              color: red
              style: dmd_big
              y: 11
            - type: text
              text: (match_number0)
              y: 31
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: top
            - type: text
              text: (match_number1)
              y: 31
              x: right-10
              anchor_x: right
              anchor_y: top
              style: dmd_med
            - type: text
              text: (match_number2)
              y: 0
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: bottom
              number_grouping: true
            - type: text
              text: (match_number3)
              y: 0
              x: right-10
              anchor_x: right
              anchor_y: bottom
              style: dmd_med
