#config_version=5
mode:
  priority: 1000
  start_events: game_ending
  code: match.MyMatch
  game_mode: False
  use_wait_queue: true

mode_settings:
  non_match_number_step: 10

queue_relay_player:
  match_no_match:
    post: no_match
    wait_for: slide_no_match_slide_removed
    pass_args: true
  match_has_match:
    post: has_match
    wait_for: slide_match_slide_removed
    pass_args: true

sounds:
  matched:
    file: matched.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 1.0
    max_queue_time: None
  no_match:
    file: no_match.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 1.0
    max_queue_time: None
  match_drama:
    file: match_drama.wav
    streaming: False
    track: sfx
    priority: 50
    volume: 1.0
    max_queue_time: None

shows:
  no_match_show:
    - duration: 3.5s
      sounds: match_drama
      slides:
        no_match_drama_slide:
          widgets:
            - type: text
              text: (winner_number)
              number_grouping: true
              min_digits: 2
              opacity: 0.0
              color: red
              style: big
              animations:
                show_slide:
                  - property: opacity
                    value: 0
                    duration: .5s
                  - property: opacity
                    value: 1
                    duration: 2.5s
            - type: image
              image: match_explosion
              start_frame: 0
              fps: 17
    - duration: 3s
      sounds: no_match
      slides:
        no_match_slide:
          widgets:
            - type: text
              text: NO MATCH
              color: dmd_blue
              style: big
            - type: text
              text: (match_number0)
              number_grouping: true
              min_digits: 2
              y: 31
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: top
            - type: text
              text: (match_number1)
              number_grouping: true
              min_digits: 2
              y: 31
              x: right-10
              anchor_x: right
              anchor_y: top
              style: dmd_med
            - type: text
              text: (match_number2)
              number_grouping: true
              min_digits: 2
              y: 0
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (match_number3)
              number_grouping: true
              min_digits: 2
              y: 0
              x: right-10
              anchor_x: right
              anchor_y: bottom
              style: dmd_med

  has_match_show:
    - duration: 3.5s
      sounds: match_drama
      slides:
        match_drama_slide:
          widgets:
            - type: text
              text: (winner_number)
              number_grouping: true
              min_digits: 2
              opacity: 0.0
              color: red
              style: big
              animations:
                show_slide:
                  - property: opacity
                    value: 0
                    duration: .5s
                  - property: opacity
                    value: 1
                    duration: 2.5s
            - type: image
              image: match_explosion
              start_frame: 0
              fps: 17
    - duration: 3s
      sounds: matched
      slides:
        match_slide:
          widgets:
            - type: text
              text: MATCH
              color: red
              style: big
              y: 22
            - type: text
              text: (winner_number)
              number_grouping: true
              min_digits: 2
              color: red
              style: big
              y: 11
            - type: text
              text: (match_number0)
              number_grouping: true
              min_digits: 2
              y: 31
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: top
            - type: text
              text: (match_number1)
              number_grouping: true
              min_digits: 2
              y: 31
              x: right-10
              anchor_x: right
              anchor_y: top
              style: dmd_med
            - type: text
              text: (match_number2)
              number_grouping: true
              min_digits: 2
              y: 0
              x: 10
              style: dmd_med
              anchor_x: left
              anchor_y: bottom
            - type: text
              text: (match_number3)
              number_grouping: true
              min_digits: 2
              y: 0
              x: right-10
              anchor_x: right
              anchor_y: bottom
              style: dmd_med
