#config_version=5
mode:
  start_events: mode_base_starting
  priority: 100

shot_profiles:
  power_bombs:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color

shots:
  power_bomb_1_shot:
    switch: s_lower_right_bank_1
    profile: power_bombs
    show_tokens:
      led: led_bomb_bank_1
      color: "FFFF00"
  power_bomb_2_shot:
    switch: s_lower_right_bank_2
    profile: power_bombs
    show_tokens:
      led: led_bomb_bank_2
      color: "FFFF00"
  power_bomb_3_shot:
    switch: s_lower_right_bank_3
    profile: power_bombs
    show_tokens:
      led: led_bomb_bank_3
      color: "FFFF00"

shot_groups:
  power_bombs_shot_group:
    shots: power_bomb_1_shot, power_bomb_2_shot, power_bomb_3_shot
    reset_events:
      power_bombs_shot_group_lit_complete:  1s
    enable_events: mode_power_bombs_started
    disable_events: mode_power_bombs_ending

event_player:
  power_bombs_shot_group_lit_complete: power_bomb_collected

show_player:
  power_bomb_collected:
    power_bombs_collected:
      loops: 0

variable_player:
  power_bomb_1_shot_hit:
    score:
      int: (500 + (500 * current_player.power_bombs)) * current_player.multiplier
  power_bomb_2_shot_hit:
    score:
      int: (500 + (500 * current_player.power_bombs)) * current_player.multiplier
  power_bomb_3_shot_hit:
    score:
      int: (500 + (500 * current_player.power_bombs)) * current_player.multiplier
  power_bomb_collected:
    power_bombs: 1
    score:
      int: (2000 + (1000 * current_player.power_bombs)) * current_player.multiplier

sound_player:
  power_bomb_collected: power_bomb_collected
