#config_version=5

# Probably NOT ACCEPTABLE
# https://commons.wikimedia.org/wiki/File:Lanzarote_5_Luc_Viatour.jpg

mode:
  start_events: room_1y_continue, room_1y_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1v_enter, room_2c_enter, room_1x_enter, room_1y_exit
  priority: 300

shots:
  room_1y_exit_north_shot:
    switches: s_ramp_enter
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1y_exit_north_shot_hit, metroid_close_doors
    reset_events: room_1y_exit_north_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue
  room_1y_exit_east_shot:
    hit_events: rollover_shot_hit
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1y_exit_east_shot_hit, metroid_close_doors
    reset_events: room_1y_exit_east_shot_hit
    show_tokens:
      led: led_rollover
      color: door_blue
  room_1y_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1y_exit_west_shot_hit, metroid_close_doors
    reset_events: room_1y_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue


slides:
  room_1y_subterranean_isle_backglass_slide:
    widgets:
      - type: image
        image: room_1y_subterranean_isle_backglass
    transition: fade
    transition_out: fade
  room_1y_subterranean_isle_splash_slide:
    widgets:
      - type: image
        image: room_1y_subterranean_isle_splash

slide_player:
  mode_room_1y_subterranean_isle_started:
    room_1y_subterranean_isle_backglass_slide:
      target: backglass
    room_1y_subterranean_isle_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1y_subterranean_isle_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: 'FFFF00'
    light_bar_solid:
      loops: -1
      show_tokens:
        color: light_bar_basic
  show_mode_status_report:
    room_1y_subterranean_isle_status_report:
      loops: 0
  flipper_cradle_release:
    room_1y_subterranean_isle_status_report:
      action: stop

event_player:
  mode_room_1y_subterranean_isle_started:
    cmd_backbox_show:
      show_type: gradient
      color_start: "604060"
      color_end: "182400"
    drop_targets_continue:
    cmd_map_position:
      room: '1y'
      visit: True
    cmd_play_map_music:
      music: music_brinstar_side_entrance
    metroid_open_doors:
  room_1y_exit_north_shot_hit.1: drop_targets_save
  room_1y_exit_north_shot_hit.2: room_1v_enter
  room_1y_exit_east_shot_hit.1: drop_targets_save
  room_1y_exit_east_shot_hit.2: room_2c_enter
  room_1y_exit_west_shot_hit.1: drop_targets_save
  room_1y_exit_west_shot_hit.2: room_1x_enter

variable_player:
  mode_room_1y_subterranean_isle_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1y
      action: set
