#config_version=5

mode:
  start_events: room_2k_continue, room_2k_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_2j_enter
  priority: 300

shots:
  room_2k_exit_west_shot:
    hit_events: left_orbit_hit
    profile: exit_door
    enable_events: mode_room_2k_larvae_nest_started
    disable_events: room_2k_exit_west_shot_hit
    reset_events: room_2k_exit_west_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue


slides:
  room_2k_larvae_nest_backglass_slide:
    widgets:
      - type: image
        image: room_2k_larvae_nest_backglass
    transition: fade
    transition_out: fade
  room_2k_larvae_nest_splash_slide:
    widgets:
      - type: image
        image: room_2k_larvae_nest_splash

slide_player:
  mode_room_2k_larvae_nest_started:
    room_2k_larvae_nest_backglass_slide:
      target: backglass
    room_2k_larvae_nest_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_2k_larvae_nest_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_2k_larvae_nest_status_report:
      loops: 0
  flipper_cradle_release:
    room_2k_larvae_nest_status_report:
      action: stop

event_player:
  mode_room_2k_larvae_nest_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '2k'
      visit: True
  room_2k_exit_west_shot_hit.1: drop_targets_save
  room_2k_exit_west_shot_hit.2: room_2j_enter

variable_player:
  mode_room_2k_larvae_nest_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 2k
      action: set
