#config_version=5
mode:
  start_events: mode_base_starting
  priority: 100

shot_profiles:
  lanes:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color

shots:
  left_outlane_shot:
    switch: s_left_outlane
    profile: lanes
    show_tokens:
      led: led_left_outlane
      color: 8040FF
  left_inlane_shot:
    switch: s_left_inlane
    profile: lanes
    show_tokens:
      led: led_left_inlane
      color: 8040FF
  right_outlane_shot:
    switch: s_right_outlane
    profile: lanes
    show_tokens:
      led: led_right_outlane
      color: 8040FF
  right_inlane_shot:
    switch: s_right_inlane
    profile: lanes
    show_tokens:
      led: led_right_inlane
      color: 8040FF

shot_groups:
  lanes_shot_group:
    shots: left_outlane_shot, left_inlane_shot, right_inlane_shot, right_outlane_shot
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events: lanes_shot_group_lit_complete
    enable_events: mode_lanes_started
    disable_events: mode_lanes_ending

show_player:
  lanes_shot_group_lit_complete:
    lanes_complete:
      loops: 0

variable_player:
  left_outlane_shot_hit:
    lanes: 1
    score:
      int: (100 + (10 * current_player.lanes)) * current_player.multiplier
  left_inlane_shot_hit:
    lanes: 1
    score:
      int: (100 + (10 * current_player.lanes)) * current_player.multiplier
  right_outlane_shot_hit:
    lanes: 1
    score:
      int: (100 + (10 * current_player.lanes)) * current_player.multiplier
  right_inlane_shot_hit:
    lanes: 1
    score:
      int: (100 + (10 * current_player.lanes)) * current_player.multiplier
  lanes_shot_group_lit_complete:
    kickbacks: 1
    score:
      int: (1000 + (10 * current_player.lanes)) * current_player.multiplier
