#config_version=5
mode:
  code: lanes.Lanes
  start_events: metroid_base_started
  stop_events: metroid_base_ended
  priority: 100

shot_profiles:
  lanes:
    states:
      - name: unlit
        show: off
      - name: lit
        show: led_color
  virtual_kickback:
    states:
      - name: lit
        show: led_color

shots:
  left_outlane_shot:
    switch: s_left_outlane
    profile: lanes
    show_tokens:
      led: led_left_outlane
      color: 8040FF
  left_inlane_shot:
    switch: s_left_inlane
    profile: lanes
    show_tokens:
      led: led_left_inlane
      color: 8040FF
  right_outlane_shot:
    switch: s_right_outlane
    profile: lanes
    show_tokens:
      led: led_right_outlane
      color: 8040FF
  right_inlane_shot:
    switch: s_right_inlane
    profile: lanes
    show_tokens:
      led: led_right_inlane
      color: 8040FF
  left_ballsave_shot:
    switch: s_left_outlane
    profile: virtual_kickback
    enable_events: lanes_enable_left_ball_save, lanes_enable_ball_save
    disable_events: lanes_disable_ball_save, lanes_enable_right_ball_save
    show_tokens:
      led: led_left_kickback
      color: 'FF8000'
  right_ballsave_shot:
    switch: s_right_outlane
    profile: virtual_kickback
    enable_events: lanes_enable_right_ball_save
    disable_events: lanes_disable_ball_save, lanes_enable_ball_save, lanes_enable_left_ball_save
    show_tokens:
      led: led_right_kickback
      color: 'FF8000'

shot_groups:
  lanes_shot_group:
    shots: left_outlane_shot, left_inlane_shot, right_inlane_shot, right_outlane_shot
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events: lanes_shot_group_lit_complete
    enable_events: mode_lanes_started
    disable_events: mode_lanes_ending

show_player:
  lanes_shot_group_lit_complete:
    lanes_complete:
      loops: 0
      priority: 300

event_player:
  mode_lanes_starting: lanes_disable_ball_save
  left_ballsave_shot_hit: lanes_check_kickbacks
  right_ballsave_shot_hit: lanes_check_kickbacks
  lanes_shot_group_lit_complete{current_player.lanes_last_shot > 0 and current_player.kickbacks == 0}: lanes_collect_ball_save
  lanes_shot_group_lit_complete{current_player.lanes_last_shot > 0 and current_player.kickbacks > 0}: lanes_check_kickbacks
  lanes_shot_group_lit_complete{current_player.lanes_last_shot == 0}: lanes_check_kickbacks
  lanes_check_kickbacks{current_player.kickbacks < 1}: lanes_disable_ball_save
  lanes_check_kickbacks{current_player.kickbacks > 0}: lanes_enable_ball_save
  s_left_flipper_active{current_player.kickbacks > 0 and current_player.kickback_active == 0}: lanes_enable_right_ball_save
  s_left_flipper_active{current_player.kickbacks > 0 and current_player.kickback_active == 1}: lanes_enable_left_ball_save
  s_right_flipper_active{current_player.kickbacks > 0 and current_player.kickback_active == 0}: lanes_enable_left_ball_save
  s_right_flipper_active{current_player.kickbacks > 0 and current_player.kickback_active == 1}: lanes_enable_right_ball_save

variable_player:
  left_outlane_shot_hit:
    lanes: 1
    score: (100 + (10 * current_player.lanes)) * current_player.multiplier
    lanes_last_shot:
      action: set
      int: 1
  left_inlane_shot_hit:
    lanes: 1
    score: (100 + (10 * current_player.lanes)) * current_player.multiplier
    lanes_last_shot:
      action: set
      int: 0
  right_outlane_shot_hit:
    lanes: 1
    score: (100 + (10 * current_player.lanes)) * current_player.multiplier
    lanes_last_shot:
      action: set
      int: 2
  right_inlane_shot_hit:
    lanes: 1
    score: (100 + (10 * current_player.lanes)) * current_player.multiplier
    lanes_last_shot:
      action: set
      int: 0
  lanes_shot_group_lit_complete:
    kickbacks: 1
    score: (1000 + (10 * current_player.lanes)) * current_player.multiplier
  lanes_enable_ball_save:
    kickback_active:
      action: set
      int: 0
  lanes_enable_left_ball_save:
    kickback_active:
      action: set
      int: 0
  lanes_enable_right_ball_save:
    kickback_active:
      action: set
      int: 1
  mode_lanes_started:
    lanes_last_shot:
      action: set
      int: 0
