#config_version=5
mode:
    start_events: mode_base_starting
    priority: 300

multiballs:
  chozo:
    ball_count: 3
    ball_count_type: total
    shoot_again: 20s
    start_or_add_a_ball_events: chozo_multiball_bashed

counters:
  captive_ball_counter:
    count_events: captive_shot_hit
    events_when_hit: chozo_multiball_progress
    starting_count: 4 + (2 * current_player.chozo_multiballs)
    count_complete_value: 0
    direction: down
    events_when_complete: chozo_multiball_bashed
    reset_events: game_start
    persist_state: true
    reset_on_complete: true
    disable_on_complete: false

shots:
  chozo_multiball_jackpot_one_shot:
    switch: s_ramp_enter
    profile: chozo_multiball_jackpot
    enable_events: multiball_chozo_started
    disable_events: multiball_chozo_ended
    show_tokens:
      led: led_enter_ramp
      color: 'C00000'
  chozo_multiball_jackpot_two_shot:
    switch: s_side_ramp_made
    profile: chozo_multiball_jackpot
    enable_events: multiball_chozo_started
    disable_events: multiball_chozo_ended
    show_tokens:
      led: led_enter_side_ramp
      color: 'C00000'
  chozo_multiball_jackpot_collect_shot:
    switch: s_vuk
    profile: chozo_multiball_jackpot
    enable_events: multiball_chozo_started
    disable_events: multiball_chozo_ended
    show_tokens:
      led: gi_strip_9
      color: '7000C0'

shot_profiles:
  chozo_multiball_jackpot:
    states:
      - name: lit
        show: fade_one_light

show_player:
  chozo_multiball_progress:
    chozo_multiball_progress:
      loops: 0
  chozo_multiball_bashed:
    chozo_multiball_started:
      loops: 0
  multiball_chozo_shoot_again_ended:
    chozo_ball_save_blink:
      action: stop
  multiball_chozo_started:
    blink_light:
      key: chozo_ball_save_blink
      loops: -1
      speed: 2
      show_tokens:
        led: led_ball_save
        color: ff4700
    small_theater_chase:
      key: chozo_multiball_drop_show
      loops: -1
      speed: 6
      show_tokens:
        color: '7000C0'
        led_1: led_drop_1
        led_2: led_drop_2
        led_3: led_drop_3
        led_4: led_drop_1
        led_5: led_drop_2
        led_6: led_drop_3
  multiball_chozo_ended:
    chozo_multiball_drop_show:
      action: stop

variable_player:
  logicblock_captive_ball_counter_updated:
    captive_ball_counter_value:
      int: value
      action: set
  chozo_multiball_bashed:
    chozo_multiballs: 1
    chozo_multiball_jackpot_progress:
      action: set
      int: 25000 * (current_player.chozo_multiballs + 1)
  chozo_multiball_jackpot_one_shot_hit:
    chozo_multiball_jackpot_progress: 100000
  chozo_multiball_jackpot_two_shot_hit:
    chozo_multiball_jackpot_progress: 175000
  chozo_multiball_jackpot_collect_shot_hit:
    score: current_player.chozo_multiball_jackpot_progress
  chozo_multiball_reset_jackpot:
    chozo_multiball_jackpot_progress:
      action: set
      int: 25000 * (current_player.chozo_multiballs + 1)

sound_player:
  chozo_multiball_bashed: multiball
  chozo_multiball_progress: ball_locked

event_player:
  multiball_chozo_started: cmd_drop_all_drops
  chozo_multiball_jackpot_collect_shot_hit: chozo_multiball_reset_jackpot
