#config_version=5

mode:
    start_events: select_landing_site_wrecked_ship_selected, room_1l_continue, room_1l_enter
    stop_events: game_ending, ball_ending, metroid_base_ended, room_1m_enter, room_1d_enter, room_1n_enter, room_1k_enter, room_1l_exit
    priority: 300

shots:
  room_1l_exit_east_shot:
    switches: s_vuk
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1l_exit_east_shot_hit, metroid_close_doors
    reset_events: room_1l_exit_east_shot_hit
    show_tokens:
      led: gi_strip_9
      color: door_blue
  room_1l_exit_west_shot:
    switches: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1l_exit_west_shot_hit, metroid_close_doors
    reset_events: room_1l_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1l_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1l_exit_south_shot_hit, metroid_close_doors
    reset_events: room_1l_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1l_exit_north_shot:
    hit_events: left_orbit_hit
    profile: exit_door_optimum
    enable_events: mode_room_1l_entryway_started_no_charge, room_1l_open_no_charge_doors
    disable_events: mode_room_1l_entryway_started, room_1l_exit_north_shot_hit, metroid_close_doors
    reset_events: mode_room_1l_entryway_started, room_1l_exit_north_shot_hit
    show_tokens:
      led: led_enter_left_orbit
      color: door_blue
  room_1l_exit_north_powered_shot:
    switches: s_ramp_enter
    profile: exit_door_optimum
    enable_events: mode_room_1l_entryway_started_charge, room_1l_open_charge_doors
    disable_events: mode_room_1l_entryway_started, room_1l_exit_north_powered_shot_hit, metroid_close_doors
    reset_events: mode_room_1l_entryway_started, room_1l_exit_north_powered_shot_hit
    show_tokens:
      led: led_enter_ramp
      color: door_blue


show_player:
  mode_room_1l_entryway_started_no_charge:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: 'FF4040'
    light_bar_solid:
      loops: -1
      show_tokens:
        color: 'FF4040'
  mode_room_1l_entryway_started_charge:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: 'FFC060'
        color2: 'C00020'
    light_bar_solid:
      loops: -1
      show_tokens:
        color: 'FFC060'
  mode_room_1l_entryway_started:
    small_theater_chase:
      key: chozo_multiball_drop_show
      loops: -1
      speed: 6
      priority: 50
      show_tokens:
        color: door_blue
        led_1: led_drop_1
        led_2: gi_back_right
        led_3: led_drop_2
        led_4: gi_back_right
        led_5: led_drop_3
        led_6: gi_back_right
  room_1l_score_jackpot:
    special_score_green:
      loops: 0

slides:
  room_1l_backglass_slide:
    widgets:
      - type: image
        image: room_1l_entryway_backglass
    transition: fade
    transition_out: fade
  room_1l_backglass_power_slide:
    widgets:
      - type: image
        image: room_1l_entryway_power_backglass
    transition: fade
    transition_out: fade
  room_1l_splash_slide:
    widgets:
      - type: image
        image: room_1l_splash

slide_player:
  mode_room_1l_entryway_started_no_charge:
    room_1l_backglass_slide:
      target: backglass
  mode_room_1l_entryway_started_charge:
    room_1l_backglass_power_slide:
      target: backglass
  mode_room_1l_entryway_started:
    room_1l_splash_slide:
      target: dmd
      expire: 1.5s


event_player:
  mode_room_1l_entryway_started_no_charge:
    cmd_backbox_show:
      show_type: gradient
      color_start: "080606"
      color_end: "000000"
    cmd_play_map_music:
      music: music_wrecked_ship
    metroid_open_doors:
  mode_room_1l_entryway_started_charge:
    cmd_backbox_show:
      show_type: gradient
      color_start: "FF0000"
      color_end: "E0C020"
    cmd_play_map_music:
      music: music_wrecked_ship_generator
  mode_room_1l_entryway_started:
    drop_targets_continue:
    cmd_map_position:
      room: '1l'
      visit: True
  mode_room_1l_entryway_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1l_entryway_started_no_charge
  mode_room_1l_entryway_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1l_entryway_started_charge
  metroid_open_doors{current_player.wrecked_ship_powered_up == 0}: room_1l_open_no_charge_doors
  metroid_open_doors{current_player.wrecked_ship_powered_up == 1}: room_1l_open_charge_doors
  room_1l_exit_east_shot_hit.1:
    cmd_map_complete:
      room: '1l'
  room_1l_exit_east_shot_hit.2: drop_targets_save
  room_1l_exit_east_shot_hit.3: room_1m_enter
  room_1l_exit_west_shot_hit.1: drop_targets_save
  room_1l_exit_west_shot_hit.2: room_1d_enter
  room_1l_exit_south_shot_hit.1: drop_targets_save
  room_1l_exit_south_shot_hit.2: room_1n_enter
  room_1l_exit_north_shot_hit.1: drop_targets_save
  room_1l_exit_north_shot_hit.2: room_1k_enter
  room_1l_exit_north_powered_shot_hit.1: drop_targets_save
  room_1l_exit_north_powered_shot_hit.2: room_1k_enter
  drop_1_shot_hit: room_1l_score_jackpot
  drop_2_shot_hit: room_1l_score_jackpot
  drop_3_shot_hit: room_1l_score_jackpot


variable_player:
  mode_room_1l_entryway_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1l
      action: set
  room_1l_score_jackpot:
    lanes: 1
    score:
      int: (100000 + (5000 * current_player.drops) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
    room_special_score:
      int: (100000 + (5000 * current_player.drops) + (current_player.area_bonus_ne * 10000)) * current_player.multiplier
      action: set
