#config_version=5
mode:
    start_events: select_landing_site_wrecked_ship_selected, room_1l_continue
    stop_events: game_ending, ball_ending
    # restart_on_next_ball: true
    priority: 300

slides:
  room_1l_backglass_slide:
    widgets:
      - type: image
        image: room_1l_entryway_backglass
    transition: fade
    transition_out: fade
  room_1l_splash_slide:
    widgets:
      - type: image
        image: room_1l_splash

slide_player:
  mode_room_1l_entryway_started:
    room_1l_backglass_slide:
      target: backglass
    room_1l_splash_slide:
      target: dmd
      expire: 1.5s

variable_player:
  mode_room_1l_entryway_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1l
      action: set
