#config_version=5

mode:
  start_events: room_1q_continue, room_1q_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1p_enter, room_2a_enter
  priority: 300

shots:
  room_1q_exit_south_shot:
    switch: s_scoop
    profile: exit_door
    enable_events: mode_room_1q_impact_zone_started
    disable_events: room_1q_exit_south_shot_hit
    reset_events: room_1q_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1q_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: mode_room_1q_impact_zone_started
    disable_events: room_1q_exit_west_shot_hit
    reset_events: room_1q_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue

slides:
  room_1q_impact_zone_backglass_slide:
    widgets:
      - type: image
        image: room_1q_impact_zone_backglass
    transition: fade
    transition_out: fade
  room_1q_impact_zone_splash_slide:
    widgets:
      - type: image
        image: room_1q_impact_zone_splash

slide_player:
  mode_room_1q_impact_zone_started:
    room_1q_impact_zone_backglass_slide:
      target: backglass
    room_1q_impact_zone_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1q_impact_zone_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1q_impact_zone_status_report:
      loops: 0
  flipper_cradle_release:
    room_1q_impact_zone_status_report:
      action: stop

event_player:
  mode_room_1q_impact_zone_started:
    cmd_backbox_show:
      show_type: fire
    drop_targets_continue:
    cmd_map_position:
      room: '1q'
      visit: True
  room_1q_exit_south_shot_hit.1: drop_targets_save
  room_1q_exit_south_shot_hit.2: room_2a_enter
  room_1q_exit_west_shot_hit.1: drop_targets_save
  room_1q_exit_west_shot_hit.2: room_1p_enter

variable_player:
  mode_room_1q_impact_zone_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1q
      action: set
