#config_version=5

# https://commons.wikimedia.org/wiki/File:HN002Teguci_MtchSclptr.jpg

mode:
  start_events: room_1q_continue, room_1q_enter
  stop_events: game_ending, ball_ending, metroid_base_ended, room_1p_enter, room_2a_enter, room_1q_exit
  priority: 300


timers:
  room_1q_super_jackpot_timeout:
    start_value: 1
    end_value: 13
    tick_interval: 1.0s
    control_events:
      - event: room_1q_enable_super_jackpot_shot
        action: restart


shot_profiles:
  room_1q_collect:
    states:
      - name: collectable
        show: blink_light
        speed: 2
        loops: -1
        sync_ms: 1000
        show_tokens:
          color: 'FF5840'
      - name: collected
        show: led_color
        show_tokens:
          color: 'FF5840'
  room_1q_jackpot:
    states:
      - name: lit
        show: blink_3_colors
        speed: 2
        loops: -1
        sync_ms: 1000
        show_tokens:
          color1: 'FF0000'
          color2: '00FF00'
          color3: '0000FF'
  room_1q_super_jackpot:
    states:
      - name: lit
        show: blink_3_colors
        speed: 4
        loops: -1
        sync_ms: 1000
        show_tokens:
          color1: 'FFFF00'
          color2: '00FFFF'
          color3: 'FF00FF'


shots:
  room_1q_exit_south_shot:
    switch: s_scoop
    profile: exit_door_optimum
    enable_events: metroid_open_doors
    disable_events: room_1q_exit_south_shot_hit, metroid_close_doors
    reset_events: room_1q_exit_south_shot_hit
    show_tokens:
      led: led_enter_scoop
      color: door_blue
  room_1q_exit_west_shot:
    switch: s_left_passage
    profile: exit_door
    enable_events: metroid_open_doors
    disable_events: room_1q_exit_west_shot_hit, metroid_close_doors
    reset_events: room_1q_exit_west_shot_hit
    show_tokens:
      led: led_enter_secret_passage
      color: door_blue
  room_1q_collect_1_shot:
    switch: s_ramp_enter
    profile: room_1q_collect
    enable_events: room_1q_enable_rubble_shots
    disable_events: mode_room_1q_impact_zone_started, room_1q_disable_rubble_shots
    show_tokens:
      led: led_enter_ramp
  room_1q_collect_2_shot:
    hit_events: left_orbit_hit
    profile: room_1q_collect
    enable_events: room_1q_enable_rubble_shots
    disable_events: mode_room_1q_impact_zone_started, room_1q_disable_rubble_shots
    show_tokens:
      led: led_enter_left_orbit
  room_1q_collect_3_shot:
    switch: s_side_ramp_made
    profile: room_1q_collect
    enable_events: room_1q_enable_rubble_shots
    disable_events: mode_room_1q_impact_zone_started, room_1q_disable_rubble_shots
    show_tokens:
      led: led_enter_side_ramp
  room_1q_collect_4_shot:
    hit_events: right_orbit_hit
    profile: room_1q_collect
    enable_events: room_1q_enable_rubble_shots
    disable_events: mode_room_1q_impact_zone_started, room_1q_disable_rubble_shots
    show_tokens:
      led: led_enter_right_orbit
  room_1q_collect_jackpot_shot:
    switch: s_ramp_enter
    profile: room_1q_jackpot
    enable_events: room_1q_enable_jackpot_shot
    disable_events: mode_room_1q_impact_zone_started, room_1q_enable_rubble_shots, room_1q_enable_super_jackpot_shot, room_1q_collect_jackpot_shot_hit
    show_tokens:
      led: led_enter_ramp
  room_1q_collect_super_jackpot_shot:
    switch: s_ramp_enter
    profile: room_1q_super_jackpot
    enable_events: room_1q_enable_super_jackpot_shot
    disable_events: mode_room_1q_impact_zone_started, room_1q_enable_rubble_shots, room_1q_enable_jackpot_shot, room_1q_collect_super_jackpot_shot_hit
    show_tokens:
      led: led_enter_ramp


shot_groups:
  room_1q_collect_shot_group:
    shots: room_1q_collect_1_shot, room_1q_collect_2_shot, room_1q_collect_3_shot, room_1q_collect_4_shot
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
    reset_events: room_1q_jackpot_collected
    enable_events: room_1q_enable_rubble_shots, room_1q_super_jackpot_collected
    disable_events: mode_room_1q_impact_zone_ending, room_1q_disable_rubble_shots


slides:
  room_1q_impact_zone_backglass_slide:
    widgets:
      - type: image
        image: room_1q_impact_zone_backglass
    transition: fade
    transition_out: fade
  room_1q_impact_zone_backglass_powered_slide:
    widgets:
      - type: image
        image: room_1q_impact_zone_backglass_powered
    transition: fade
    transition_out: fade
  room_1q_impact_zone_splash_slide:
    widgets:
      - type: image
        image: room_1q_impact_zone_splash

slide_player:
  mode_room_1q_impact_zone_started_no_charge:
    room_1q_impact_zone_backglass_slide:
      target: backglass
  mode_room_1q_impact_zone_started_charge:
    room_1q_impact_zone_backglass_powered_slide:
      target: backglass
    room_1q_impact_zone_splash_slide:
      target: dmd
      expire: 1.5s

show_player:
  mode_room_1q_impact_zone_started:
    gi_solid_with_overhead:
      loops: -1
      show_tokens:
        color: '808080'
        color2: '808080'
  show_mode_status_report:
    room_1q_impact_zone_status_report:
      loops: 0
  flipper_cradle_release:
    room_1q_impact_zone_status_report:
      action: stop
  room_1q_collect_1_shot_collectable_hit:
    special_score_yellow:
      loops: 0
  room_1q_collect_2_shot_collectable_hit:
    special_score_yellow:
      loops: 0
  room_1q_collect_3_shot_collectable_hit:
    special_score_yellow:
      loops: 0
  room_1q_collect_4_shot_collectable_hit:
    special_score_yellow:
      loops: 0


sounds:
  1q_impact_zone_rubble:
    file: 1q_impact_zone_rubble.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  1q_impact_zone_jackpot:
    file: 1q_impact_zone_jackpot.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None
  1q_impact_zone_super_jackpot:
    file: 1q_impact_zone_super_jackpot.wav
    streaming: False
    track: sfx
    priority: 50
    max_queue_time: None


sound_player:
  room_1q_enable_jackpot_shot: shoot_the_back_ramp
  room_1q_enable_super_jackpot_shot: shoot_the_back_ramp
  room_1q_jackpot_collected: jackpot
  room_1q_super_jackpot_collected: super_jackpot
  room_1q_enable_rubble_shots: shoot_the_flashing_targets
  room_1q_collect_shot_group_collectable_hit: 1q_impact_zone_rubble
  room_1q_collect_jackpot_shot_hit: 1q_impact_zone_jackpot
  room_1q_collect_super_jackpot_shot_hit: 1q_impact_zone_super_jackpot


event_player:
  mode_room_1q_impact_zone_started:
    cmd_backbox_show:
      show_type: spectrum
      color1: '000000'
      color2: '501800'
      color3: '000000'
    drop_targets_continue:
    cmd_map_position:
      room: '1q'
      visit: True
    metroid_open_doors:
    room_1q_enable_rubble_shots:
  mode_room_1q_impact_zone_started_no_charge:
    cmd_play_map_music:
      music: music_wrecked_ship
  mode_room_1q_impact_zone_started_charge:
    cmd_play_map_music:
      music: music_wrecked_ship_generator
  mode_room_1q_impact_zone_started{current_player.wrecked_ship_powered_up == 0}: mode_room_1q_impact_zone_started_no_charge
  mode_room_1q_impact_zone_started{current_player.wrecked_ship_powered_up == 1}: mode_room_1q_impact_zone_started_charge
  room_1q_collect_shot_group_collected_complete: room_1q_disable_rubble_shots
  room_1q_disable_rubble_shots: room_1q_enable_jackpot_shot
  room_1q_collect_jackpot_shot_hit: room_1q_jackpot_collected
  room_1q_collect_super_jackpot_shot_hit: room_1q_super_jackpot_collected
  room_1q_jackpot_collected: room_1q_enable_super_jackpot_shot
  timer_room_1q_super_jackpot_timeout_complete: room_1q_enable_rubble_shots
  room_1q_exit_south_shot_hit.1: drop_targets_save
  room_1q_exit_south_shot_hit.2: room_2a_enter
  room_1q_exit_west_shot_hit.1: drop_targets_save
  room_1q_exit_west_shot_hit.2: room_1p_enter


variable_player:
  mode_room_1q_impact_zone_started:
    has_chosen_landing_site:
      int: 1
      action: set
    continue_room:
      string: 1q
      action: set
  room_1q_collect_1_shot_collectable_hit:
    score: (((current_player.area_bonus_nw + 1) * 50000) + (current_player.wrecked_ship_charge * 20000)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_nw + 1) * 50000) + (current_player.wrecked_ship_charge * 20000)) * current_player.multiplier
      action: set
  room_1q_collect_2_shot_collectable_hit:
    score: (((current_player.area_bonus_nw + 1) * 250000) + (current_player.wrecked_ship_charge * 20000)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_nw + 1) * 250000) + (current_player.wrecked_ship_charge * 20000)) * current_player.multiplier
      action: set
  room_1q_collect_3_shot_collectable_hit:
    score: (((current_player.area_bonus_ne + 1) * 200000) + (current_player.wrecked_ship_charge * 21000)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_ne + 1) * 200000) + (current_player.wrecked_ship_charge * 21000)) * current_player.multiplier
      action: set
  room_1q_collect_4_shot_collectable_hit:
    score: (((current_player.area_bonus_ne + 1) * 150000) + (current_player.wrecked_ship_charge * 20000)) * current_player.multiplier
    room_special_score:
      int: (((current_player.area_bonus_ne + 1) * 150000) + (current_player.wrecked_ship_charge * 20000)) * current_player.multiplier
      action: set
